force-app/main/default/objects/inspire1__Project__c/inspire1__Project__c.object-meta.xml
<CustomObject>
    <description>Inspire Planner - This object captures the detail of the project record</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/inspire1__Project__c/fields/inspire1__Actual_Finish_Date__c.field-meta.xml
<CustomField>
    <fullName>inspire1__Actual_Finish_Date__c</fullName>
    <description>Defines the actual date the project finished.  This is represented by the last task finish date.</description>
    <inlineHelpText>Defines the actual date the project finished.  This is represented by the last task finish date.</inlineHelpText>
    <label>Finish Date</label>
    <summarizedField>inspire1__Project_Tasks__c.inspire1__Finish_Date__c</summarizedField>
    <summaryFilterItems>
        <field>inspire1__Project_Tasks__c.inspire1__Time_Tracking_Only__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>inspire1__Project_Tasks__c.inspire1__Task_Type__c</field>
        <operation>equals</operation>
        <value>Task</value>
    </summaryFilterItems>
    <summaryForeignKey>inspire1__Project_Tasks__c.inspire1__Project__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/inspire1__Project__c/fields/inspire1__Opportunity1__c.field-meta.xml
<CustomField>
    <fullName>inspire1__Opportunity1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity related to Project.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/inspire1__Project_Tasks__c/inspire1__Project_Tasks__c.object-meta.xml
<CustomObject>
    <description>Inspire Planner - This object captures the tasks related to the project.</description>
    <label>Project Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/inspire1__Project_Tasks__c/fields/inspire1__Actual_Finish_Date__c.field-meta.xml
<CustomField>
    <fullName>inspire1__Actual_Finish_Date__c</fullName>
    <label>Actual Finish Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/inspire1__Project_Tasks__c/fields/inspire1__Done__c.field-meta.xml
<CustomField>
    <fullName>inspire1__Done__c</fullName>
    <description>% Done</description>
    <label>% Complete</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/inspire1__Project_Tasks__c/fields/inspire1__Project__c.field-meta.xml
<CustomField>
    <fullName>inspire1__Project__c</fullName>
    <label>Project</label>
    <referenceTo>inspire1__Project__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Inspire_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/inspire1__Project_Tasks__c/fields/inspire1__Status__c.field-meta.xml
<CustomField>
    <fullName>inspire1__Status__c</fullName>
    <description>Captures current status of task.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/inspire1__Project_Tasks__c/fields/Task_Category__c.field-meta.xml
<CustomField>
    <fullName>Task_Category__c</fullName>
    <label>Task Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Certificate Decision</fullName>
            </value>
            <value>
                <fullName>Conduct Audit</fullName>
            </value>
            <value>
                <fullName>Final Invoice Sent</fullName>
            </value>
            <value>
                <fullName>Final Payment Received</fullName>
            </value>
            <value>
                <fullName>Initial Invoice Sent</fullName>
            </value>
            <value>
                <fullName>Initial Payment Received</fullName>
            </value>
            <value>
                <fullName>WO Sent</fullName>
            </value>
            <value>
                <fullName>WO Signed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Final_Invoice_Amount__c.field-meta.xml
<CustomField>
    <fullName>Final_Invoice_Amount__c</fullName>
    <label>Final Invoice Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Final_Invoice_Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Final_Invoice_Paid_Amount__c</fullName>
    <label>Final Invoice Paid Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Final_Invoice_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Final_Invoice_Payment_Date__c</fullName>
    <label>Final Invoice Payment Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Final_Invoice_Send_Date__c.field-meta.xml
<CustomField>
    <fullName>Final_Invoice_Send_Date__c</fullName>
    <label>Final Invoice Send Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Initial_Invoice_Amount__c.field-meta.xml
<CustomField>
    <fullName>Initial_Invoice_Amount__c</fullName>
    <label>Initial Invoice Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Initial_Invoice_Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Initial_Invoice_Paid_Amount__c</fullName>
    <label>Initial Invoice Paid Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Initial_Invoice_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Initial_Invoice_Payment_Date__c</fullName>
    <label>Initial Invoice Payment Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Initial_Invoice_Send_Date__c.field-meta.xml
<CustomField>
    <fullName>Initial_Invoice_Send_Date__c</fullName>
    <label>Initial Invoice Send Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/WO_Sent_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>WO_Sent_Date_Time__c</fullName>
    <label>WO Sent Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/WO_Signed_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>WO_Signed_Date_Time__c</fullName>
    <label>WO Signed Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/SCS_ActualFinishDateAutomation.cls
/****************************************************New ORG CODE ***************************************************************** 
* Class  Name       : SCS_ActualFinishDateAutomation
* Division          : Food and Agriculture
* Version           : 1.1
* Code reviewed By  : N/A
* JIRA Ticket       : SF20FA-1325
* Functionality     : This class use in scs_ProjectTaskHandler and scs_opportunityHandler to update Actual Finish Date on project Task.

* Modification Log  :
-------------------------------------------------------------------------------------------------------------------------------------------------
* Developer Name                     Date                                Description
* -----------------------------------------------------------------------------------------------------------------------------------------------
* Umesh Kumar                        14-04-2023                          Initial version 
************************************************************************************************************************************/




public with sharing class SCS_ActualFinishDateAutomation {
    
    //call from SCS_Project Task Trigger handler on before event when record is created...
    public static void assignActualFinishDateOnProjectTask( List<inspire1__Project_Tasks__c> newTrigger){
        Set<Id> projectIdSet = new Set<Id>();
        for (inspire1__Project_Tasks__c record : newTrigger) {            
            if(record.Task_Category__c != null && record.inspire1__Project__c != null){
                projectIdSet.add(record.inspire1__Project__c);  
            } 
        }
        //If project id set in not empty...
        if(! projectIdSet.isEmpty()){
            Map<Id,inspire1__Project__c> projectMap = new Map<Id,inspire1__Project__c>([SELECT Id,inspire1__Opportunity1__c,inspire1__Opportunity1__r.WO_Sent_Date_Time__c,
            inspire1__Opportunity1__r.WO_Signed_Date_Time__c,inspire1__Opportunity1__r.Initial_Invoice_Send_Date__c,inspire1__Opportunity1__r.Initial_Invoice_Payment_Date__c,
            inspire1__Opportunity1__r.Final_Invoice_Send_Date__c,inspire1__Opportunity1__r.Final_Invoice_Payment_Date__c,inspire1__Opportunity1__r.Final_Invoice_Amount__c,
            inspire1__Opportunity1__r.Final_Invoice_Paid_Amount__c,inspire1__Opportunity1__r.Initial_Invoice_Amount__c,inspire1__Opportunity1__r.Initial_Invoice_Paid_Amount__c FROM inspire1__Project__c WHERE inspire1__Opportunity1__c !=null AND Id IN : projectIdSet]);
            for (inspire1__Project_Tasks__c record : newTrigger) {            
                if(record.Task_Category__c != null && record.inspire1__Project__c != null){
                    inspire1__Project__c project = projectMap.containsKey(record.inspire1__Project__c) ? projectMap.get(record.inspire1__Project__c) : null;  
                    if(project != null && project.inspire1__Opportunity1__c != null){
                        //If work order is send to client then complete the task...
                        if(record.Task_Category__c == 'WO Sent' && record.inspire1__Status__c != 'Completed' && project.inspire1__Opportunity1__r.WO_Sent_Date_Time__c != null){
                            record.inspire1__Status__c = 'Completed';
                            record.inspire1__Done__c = 100;
                            record.inspire1__Actual_Finish_Date__c = project.inspire1__Opportunity1__r.WO_Sent_Date_Time__c;
                            //If work order is signed by client then complete the task...
                        } else if(record.Task_Category__c == 'WO Signed' && record.inspire1__Status__c != 'Completed' && project.inspire1__Opportunity1__r.WO_Signed_Date_Time__c != null){
                            record.inspire1__Status__c = 'Completed';
                            record.inspire1__Done__c = 100;
                            record.inspire1__Actual_Finish_Date__c = project.inspire1__Opportunity1__r.WO_Signed_Date_Time__c;
                            //If initial invoice is send to client then complete the task...
                        } else if(record.Task_Category__c == 'Initial Invoice Sent' && record.inspire1__Status__c != 'Completed' && project.inspire1__Opportunity1__r.Initial_Invoice_Send_Date__c != null){
                            record.inspire1__Status__c = 'Completed';
                            record.inspire1__Done__c = 100;
                            record.inspire1__Actual_Finish_Date__c = project.inspire1__Opportunity1__r.Initial_Invoice_Send_Date__c;
                            //If initial invoice paid by client then complete the task...
                        } else if(record.Task_Category__c == 'Initial Payment Received' && record.inspire1__Status__c != 'Completed' && project.inspire1__Opportunity1__r.Initial_Invoice_Payment_Date__c != null){
                            if(record.inspire1__Status__c != 'Completed' && project.inspire1__Opportunity1__r.Initial_Invoice_Amount__c == project.inspire1__Opportunity1__r.Initial_Invoice_Paid_Amount__c){
                                record.inspire1__Status__c = 'Completed';
                                record.inspire1__Done__c = 100;
                            }
                            record.inspire1__Actual_Finish_Date__c = project.inspire1__Opportunity1__r.Initial_Invoice_Payment_Date__c;
                            //If final invoice is send to client then complete the task...
                        } else if(record.Task_Category__c == 'Final Invoice Sent' && project.inspire1__Opportunity1__r.Final_Invoice_Send_Date__c != null){
                            if(record.inspire1__Status__c != 'Completed'){
                                record.inspire1__Status__c = 'Completed' ;
                                record.inspire1__Done__c = 100;
                            }
                            record.inspire1__Actual_Finish_Date__c = project.inspire1__Opportunity1__r.Final_Invoice_Send_Date__c;
                            //If final invoice paid by client then complete the task...
                        } else if(record.Task_Category__c == 'Final Payment Received' && project.inspire1__Opportunity1__r.Final_Invoice_Payment_Date__c != null){
                            if(record.inspire1__Status__c != 'Completed' && project.inspire1__Opportunity1__r.Final_Invoice_Amount__c == project.inspire1__Opportunity1__r.Final_Invoice_Paid_Amount__c){
                                record.inspire1__Status__c = 'Completed';
                                record.inspire1__Done__c = 100;
                            }
                            record.inspire1__Actual_Finish_Date__c = project.inspire1__Opportunity1__r.Final_Invoice_Payment_Date__c;
                        }
                    }
                } 
            }
            
        }
    }
    //call from SCS_Opportunity Trigger handler after when record is update...
    public static void updateActualFinishDateOnProjectTask(List<Opportunity> newList,Map<Id,Opportunity> oldMap){
        Set<Id> oppoIdSet = new Set<Id>(); 
        for (Opportunity record : newList) { 
            Boolean  isWOSent = record.WO_Sent_Date_Time__c != oldMap.get(record.Id).WO_Sent_Date_Time__c ? true : false;
            Boolean  isWOSigned = record.WO_Signed_Date_Time__c != oldMap.get(record.Id).WO_Signed_Date_Time__c ? true : false;
            Boolean  isInitialInvoiceSent = record.Initial_Invoice_Send_Date__c != oldMap.get(record.Id).Initial_Invoice_Send_Date__c ? true : false;
            Boolean  isInitialInvoicePaid = record.Initial_Invoice_Payment_Date__c != oldMap.get(record.Id).Initial_Invoice_Payment_Date__c ? true : false;
            Boolean  isFinalInvoiceSent = record.Final_Invoice_Send_Date__c != oldMap.get(record.Id).Final_Invoice_Send_Date__c ? true : false;
            Boolean  isFinalInvoicePaid = record.Final_Invoice_Payment_Date__c != oldMap.get(record.Id).Final_Invoice_Payment_Date__c ? true : false;  
            if(isWOSent ||isWOSigned || isInitialInvoiceSent || isInitialInvoicePaid || isFinalInvoiceSent || isFinalInvoicePaid){
                oppoIdSet.add(record.Id);
            } 
        }
        //If opportunity id set in not empty...
        if(! oppoIdSet.isEmpty()){
            Map<Id,inspire1__Project__c> projectMap = new Map<Id,inspire1__Project__c>([SELECT Id FROM inspire1__Project__c WHERE inspire1__Opportunity1__c IN :oppoIdSet]);
            if(! projectMap.isEmpty()){
                List<inspire1__Project_Tasks__c> updatedTask = new List<inspire1__Project_Tasks__c>();
                List<inspire1__Project_Tasks__c> taskList = [SELECT Id,Task_Category__c,inspire1__Actual_Finish_Date__c,inspire1__Status__c,inspire1__Project__c,
                inspire1__Project__r.inspire1__Opportunity1__c,inspire1__Project__r.inspire1__Opportunity1__r.WO_Sent_Date_Time__c,inspire1__Project__r.inspire1__Opportunity1__r.WO_Signed_Date_Time__c,
                inspire1__Project__r.inspire1__Opportunity1__r.Initial_Invoice_Send_Date__c,inspire1__Project__r.inspire1__Opportunity1__r.Initial_Invoice_Payment_Date__c,
                inspire1__Project__r.inspire1__Opportunity1__r.Final_Invoice_Send_Date__c,inspire1__Project__r.inspire1__Opportunity1__r.Final_Invoice_Payment_Date__c,
                inspire1__Project__r.inspire1__Opportunity1__r.Final_Invoice_Amount__c,inspire1__Project__r.inspire1__Opportunity1__r.Final_Invoice_Paid_Amount__c,
                inspire1__Project__r.inspire1__Opportunity1__r.Initial_Invoice_Amount__c,inspire1__Project__r.inspire1__Opportunity1__r.Initial_Invoice_Paid_Amount__c FROM inspire1__Project_Tasks__c WHERE inspire1__Project__c IN : projectMap.keySet()];
                if(! taskList.isEmpty()){
                    for(inspire1__Project_Tasks__c record : taskList){
                        if(record.Task_Category__c != null && record.inspire1__Project__c != null && record.inspire1__Project__r.inspire1__Opportunity1__c != null){
                            //If work order is send to client then complete the task...
                            if(record.Task_Category__c == 'WO Sent' && record.inspire1__Status__c != 'Completed' && record.inspire1__Project__r.inspire1__Opportunity1__r.WO_Sent_Date_Time__c != null){
                                record.inspire1__Status__c = 'Completed';
                                record.inspire1__Actual_Finish_Date__c = record.inspire1__Project__r.inspire1__Opportunity1__r.WO_Sent_Date_Time__c;
                                //If work order is signed by client then complete the task...
                            } else if(record.Task_Category__c == 'WO Signed' && record.inspire1__Status__c != 'Completed' && record.inspire1__Project__r.inspire1__Opportunity1__r.WO_Signed_Date_Time__c != null){
                                record.inspire1__Status__c = 'Completed';
                                record.inspire1__Actual_Finish_Date__c = record.inspire1__Project__r.inspire1__Opportunity1__r.WO_Signed_Date_Time__c;
                                //If initial invoice is send to client then complete the task...
                            } else if(record.Task_Category__c == 'Initial Invoice Sent' && record.inspire1__Status__c != 'Completed' && record.inspire1__Project__r.inspire1__Opportunity1__r.Initial_Invoice_Send_Date__c != null){
                                record.inspire1__Status__c = 'Completed';
                                record.inspire1__Actual_Finish_Date__c = record.inspire1__Project__r.inspire1__Opportunity1__r.Initial_Invoice_Send_Date__c;
                                //If initial invoice paid by client then complete the task...
                            } else if(record.Task_Category__c == 'Initial Payment Received' && record.inspire1__Status__c != 'Completed' && record.inspire1__Project__r.inspire1__Opportunity1__r.Initial_Invoice_Payment_Date__c != null){
                                if(record.inspire1__Status__c != 'Completed' && record.inspire1__Project__r.inspire1__Opportunity1__r.Initial_Invoice_Amount__c == record.inspire1__Project__r.inspire1__Opportunity1__r.Initial_Invoice_Paid_Amount__c){
                                    record.inspire1__Status__c = 'Completed';
                                }
                                record.inspire1__Actual_Finish_Date__c = record.inspire1__Project__r.inspire1__Opportunity1__r.Initial_Invoice_Payment_Date__c;
                                //If final invoice is send to client then complete the task...
                            } else if(record.Task_Category__c == 'Final Invoice Sent' && record.inspire1__Project__r.inspire1__Opportunity1__r.Final_Invoice_Send_Date__c != null){
                                if(record.inspire1__Status__c != 'Completed'){ 
                                    record.inspire1__Status__c = 'Completed';
                                }
                                record.inspire1__Actual_Finish_Date__c = record.inspire1__Project__r.inspire1__Opportunity1__r.Final_Invoice_Send_Date__c;
                                //If final invoice paid by client then complete the task...
                            } else if(record.Task_Category__c == 'Final Payment Received' && record.inspire1__Project__r.inspire1__Opportunity1__r.Final_Invoice_Payment_Date__c != null){
                                if(record.inspire1__Status__c != 'Completed' && record.inspire1__Project__r.inspire1__Opportunity1__r.Final_Invoice_Amount__c == record.inspire1__Project__r.inspire1__Opportunity1__r.Final_Invoice_Paid_Amount__c){
                                    record.inspire1__Status__c = 'Completed';
                                }
                                record.inspire1__Actual_Finish_Date__c = record.inspire1__Project__r.inspire1__Opportunity1__r.Final_Invoice_Payment_Date__c;
                            }
                            updatedTask.add(record); 
                        }  
                    }
                }
                //update task with Actual Finish Date...
                if(! updatedTask.isEmpty()){
                    update  updatedTask;  
                }
            }
        }
    }
}