force-app/main/default/objects/inspire1__Project__c/inspire1__Project__c.object-meta.xml
<CustomObject>
    <description>Inspire Planner - This object captures the detail of the project record</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/inspire1__Project__c/fields/Schedule_Automation__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Automation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Schedule Automation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/inspire1__Project_Tasks__c/inspire1__Project_Tasks__c.object-meta.xml
<CustomObject>
    <description>Inspire Planner - This object captures the tasks related to the project.</description>
    <label>Project Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/inspire1__Project_Tasks__c/fields/Actual_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Start_Date__c</fullName>
    <label>Actual Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/inspire1__Project_Tasks__c/fields/inspire1__Duration__c.field-meta.xml
<CustomField>
    <fullName>inspire1__Duration__c</fullName>
    <description>Captures project duration (days).</description>
    <label>Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/inspire1__Project_Tasks__c/fields/inspire1__DurationUnit__c.field-meta.xml
<CustomField>
    <fullName>inspire1__DurationUnit__c</fullName>
    <description>Identifies if task is managed in days or hours.</description>
    <label>Duration Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>h</fullName>
            </value>
            <value>
                <fullName>d</fullName>
                <default>true</default>
                <label>d</label>
            </value>
            <value>
                <fullName>w</fullName>
            </value>
            <value>
                <fullName>mo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/inspire1__Project_Tasks__c/fields/inspire1__FinishDate__c.field-meta.xml
<CustomField>
    <fullName>inspire1__FinishDate__c</fullName>
    <description>Captures task finish date/time for tasks managed in hours.</description>
    <label>Finish Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/inspire1__Project_Tasks__c/fields/inspire1__Project__c.field-meta.xml
<CustomField>
    <fullName>inspire1__Project__c</fullName>
    <label>Project</label>
    <referenceTo>inspire1__Project__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Inspire_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/inspire1__Project_Tasks__c/fields/inspire1__RowNumber__c.field-meta.xml
<CustomField>
    <fullName>inspire1__RowNumber__c</fullName>
    <description>Row number of task.</description>
    <label>Row Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/inspire1__Project_Tasks__c/fields/inspire1__StartDate__c.field-meta.xml
<CustomField>
    <fullName>inspire1__StartDate__c</fullName>
    <description>Captures task finish date/time for tasks managed in hours.</description>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/inspire1__Project_Tasks__c/fields/inspire1__Status__c.field-meta.xml
<CustomField>
    <fullName>inspire1__Status__c</fullName>
    <description>Captures current status of task.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/inspire1__Project_Tasks__c/fields/IsParent__c.field-meta.xml
<CustomField>
    <fullName>IsParent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsParent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/inspire1__Project_Tasks__c/fields/Lag__c.field-meta.xml
<CustomField>
    <fullName>Lag__c</fullName>
    <label>Lag (Days)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/inspire1__Project_Tasks__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <label>Parent</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/inspire1__Project_Tasks__c/fields/Schedule_Automation__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Automation__c</fullName>
    <formula>inspire1__Project__r.Schedule_Automation__c</formula>
    <label>Schedule Automation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/inspire1__Project_Tasks__c/fields/Weekend_Are_Workday__c.field-meta.xml
<CustomField>
    <fullName>Weekend_Are_Workday__c</fullName>
    <formula>inspire1__Project__r.inspire1__WeekendAreWorkday__c</formula>
    <label>Weekend Are Workday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SCS_ProjectTaskTriggerHelper.cls
/****************************************************New ORG CODE ***************************************************************** 
* Class  Name       : SCS_ProjectTaskTriggerHelper
* Division          : Food and Agriculture
* Version           : 1.1
* Code reviewed By  : N/A
* JIRA Ticket       : SF20FA-1330
* Functionality     : This helper use in SCS_ProjectTaskTriggerHandler class to update project task.

* Modification Log  :
-------------------------------------------------------------------------------------------------------------------------------------------------
* Developer Name                     Date                                Description
* -----------------------------------------------------------------------------------------------------------------------------------------------
* Umesh Kumar                        11-04-2023                          Initial version 
* Umesh Kumar                        11-04-2023                          Update IsParent field on parent task.
* Umesh Kumar                        11-04-2023                          Update child task status and start date.
* Umesh Kumar                        11-04-2023                          Removed child relation.if parent task is deleted.
************************************************************************************************************************************/


public with sharing class SCS_ProjectTaskTriggerHelper {
    
    //call from trigger handler when record is created...
    public static void updateIsParentField( List<inspire1__Project_Tasks__c> newTrigger ){
        Set<Integer> rowNumberSet = new Set<Integer>();
        Set<Id> projectIdSet = new Set<Id>();
        for ( inspire1__Project_Tasks__c record: newTrigger ) {            
            if(record.Parent__c != null){
                String parentString = record.Parent__c;
                parentString = parentString.trim();
                if(parentString.isNumeric()){
                    rowNumberSet.add(Integer.valueOf(parentString));
                    projectIdSet.add(record.inspire1__Project__c);
                }
            } 
        } 
        //update Isparent field on parent task...
        if(! rowNumberSet.isEmpty() && ! projectIdSet.isEmpty()){
            List<inspire1__Project_Tasks__c> parentTaskList = new List<inspire1__Project_Tasks__c>();
            for(inspire1__Project_Tasks__c record :[SELECT Id FROM inspire1__Project_Tasks__c WHERE IsParent__c = false AND inspire1__RowNumber__c IN : rowNumberSet AND inspire1__Project__c IN :projectIdSet]){
                parentTaskList.add(new inspire1__Project_Tasks__c(Id = record.Id,IsParent__c = true));
            }
            if(! parentTaskList.isEmpty()){
                update parentTaskList;
            } 
        }
    }
    //Call from trigger handler when record is update...
    public static void updateProjectTask(List<inspire1__Project_Tasks__c> newTrigger ,Map<Id,inspire1__Project_Tasks__c> oldMap){
        Set<Id> projectIdSet = new Set<Id>();
        Set<String> rowNumberSet = new Set<String>();
        Map<String,String> mapOfRowNumber = new Map<String,String>();
        for (inspire1__Project_Tasks__c record: newTrigger ){
            //If status change then return true...
            Boolean isStatusChange = record.inspire1__Status__c != oldMap.get(record.Id).inspire1__Status__c ? true : false;
            //If Task row number is change...
            Boolean isRowNumberChange = record.inspire1__RowNumber__c != oldMap.get(record.Id).inspire1__RowNumber__c ? true : false;
            //If parent task status change to complete...
            if(record.IsParent__c && record.inspire1__Status__c == 'Completed' && isStatusChange && record.Schedule_Automation__c){
                rowNumberSet.add(String.valueOf(record.inspire1__RowNumber__c));
                projectIdSet.add(record.inspire1__Project__c);
                //If row number is change...
            } else if(isRowNumberChange && isStatusChange == false && record.IsParent__c){
                mapOfRowNumber.put(String.valueOf(oldMap.get(record.Id).inspire1__RowNumber__c),String.valueOf(record.inspire1__RowNumber__c));
                projectIdSet.add(record.inspire1__Project__c);
            }
        }
        //Update child task parent field when row number is change...
        if(! mapOfRowNumber.isEmpty() && ! projectIdSet.isEmpty()){
            updateParentNumber(mapOfRowNumber,projectIdSet);
        }
        //Update child task status and start date when parent project task status is completed...
        if(! rowNumberSet.isEmpty() && ! projectIdSet.isEmpty()){
            updateChildStatus(rowNumberSet,projectIdSet);
        }
    }
    //Call from trigger handler when parent task deleted...
    public static void parentTaskDelete(List<inspire1__Project_Tasks__c> oldList){
        Set<Id> projectIdSet = new Set<Id>();
        Map<String,String> mapOfRowNumber = new Map<String,String>();
        for (inspire1__Project_Tasks__c record: oldList ){
            mapOfRowNumber.put(String.valueOf(record.inspire1__RowNumber__c),'RemovedRelation');
            projectIdSet.add(record.inspire1__Project__c);
        }
        //Removed Relation from child...
        if(! mapOfRowNumber.isEmpty() && ! projectIdSet.isEmpty()){
            updateParentNumber(mapOfRowNumber,projectIdSet);
        }  
    }
    
    //Update child task parent field when parent task drag & drop...
    public static void updateParentNumber(Map<String,String> mapOfRowNumber,Set<Id> projectIdSet){
        if(! mapOfRowNumber.isEmpty() && ! projectIdSet.isEmpty()){
            List<inspire1__Project_Tasks__c> updatedParentField = new List<inspire1__Project_Tasks__c>();
            for(inspire1__Project_Tasks__c record: [SELECT Id,Parent__c FROM inspire1__Project_Tasks__c  WHERE inspire1__Project__c IN :projectIdSet AND Parent__c IN :mapOfRowNumber.keySet()]){
                if(String.isNotBlank(record.Parent__c)){
                    String parent = record.Parent__c;
                    parent = parent.trim();
                    if(mapOfRowNumber.containsKey(parent)){
                        record.Parent__c =  mapOfRowNumber.get(parent) == 'RemovedRelation' ? null : mapOfRowNumber.get(parent);
                        updatedParentField.add(record);
                    }
                }
            }
            if(! updatedParentField.isEmpty()){   
                update updatedParentField;
            }
        }  
    }  
    //Update child task status and start date when parent project task status is completed...
    public static void updateChildStatus(Set<String> rowNumberSet,Set<Id> projectIdSet){								
        if(! rowNumberSet.isEmpty() && ! projectIdSet.isEmpty()){
            List<inspire1__Project_Tasks__c> updatedChildTasks = new List<inspire1__Project_Tasks__c>();
            BusinessHours bsHours = [SELECT Id FROM BusinessHours WHERE Name = 'SCS Business Hours'];
            for(inspire1__Project_Tasks__c record: [SELECT Id,inspire1__Status__c,inspire1__StartDate__c,inspire1__FinishDate__c,Lag__c,inspire1__Duration__c,inspire1__DurationUnit__c,Weekend_Are_Workday__c,Actual_Start_Date__c FROM inspire1__Project_Tasks__c WHERE inspire1__Status__c = 'Not Started' AND inspire1__Project__c IN :projectIdSet AND Parent__c IN :rowNumberSet]){
                record.inspire1__Status__c = 'In Progress';
                Integer lag = 0;
                DateTime dt = System.now();
                record.Actual_Start_Date__c = dt;
                if(String.isNotBlank(record.Lag__c)){
                    String lagString = record.Lag__c;
                    lagString = lagString.trim();
                    lag = lagString.isNumeric() ? Integer.valueOf(lagString): 0;  
                } 
                dt = bsHours !=null && record.Weekend_Are_Workday__c == false ? BusinessHours.add(bsHours.Id,dt,86400000*lag) : dt.addDays(lag);
                record.inspire1__StartDate__c = dt;
                if(record.inspire1__Duration__c != null && record.inspire1__DurationUnit__c != null && record.inspire1__DurationUnit__c == 'd'){
                   lag = lag + Integer.valueOf(record.inspire1__Duration__c);
                   dt = bsHours !=null && record.Weekend_Are_Workday__c == false ? BusinessHours.add(bsHours.Id,dt,86400000*lag) : dt.addDays(lag);
                }
                record.inspire1__FinishDate__c = dt;
                updatedChildTasks.add(record);
            }
            if(! updatedChildTasks.isEmpty()){   
                update updatedChildTasks;
            }
        }
    }
}