force-app/main/default/objects/inspire1__Project__c/inspire1__Project__c.object-meta.xml
<CustomObject>
    <description>Inspire Planner - This object captures the detail of the project record</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/inspire1__Project__c/fields/inspire1__Opportunity1__c.field-meta.xml
<CustomField>
    <fullName>inspire1__Opportunity1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity related to Project.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/fileforcem1__Sharepoint_Folder_Id__c.field-meta.xml
<CustomField>
    <fullName>fileforcem1__Sharepoint_Folder_Id__c</fullName>
    <description>Field that holds SharePoint&apos;s folder Id.</description>
    <inlineHelpText>Field that holds SharePoint&apos;s folder Id.</inlineHelpText>
    <label>SharePoint Folder Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Certificate__c/Opportunity_Certificate__c.object-meta.xml
<CustomObject>
    <label>Opportunity Certificate</label>
    <nameField>
        <displayFormat>OC-{0000}</displayFormat>
        <label>Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Certificates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Certificate__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Certificates</relationshipLabel>
    <relationshipName>Opportunity_Certificates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreateSharepointFolderLWCController.cls
/*
@Author : MAANTIC
@CreatedDate : 14th April 2023
@Description : This class is the controller class of Create sharepoint folder lightning web component.
@CreatedBy : Sohit Tripathi
*/
/****************************** New ORG CODE *****************************************************/

public class CreateSharepointFolderLWCController {
    
    @AuraEnabled(cacheable=true)
    public static sObject checkParentFolder(String recordId){
        System.debug('I am in dev console');
        try{
            if(recordId.startsWith('a0e')){
            return [SELECT Id, inspire1__Opportunity1__r.fileforcem1__Sharepoint_Folder_Id__c FROM inspire1__Project__c WHERE Id=:recordId];
            }
            else if(recordId.startsWith('a2C')){
                return [SELECT Id, Opportunity__r.fileforcem1__Sharepoint_Folder_Id__c FROM Opportunity_Certificate__c WHERE Id=:recordId];
            }
            else{return null;}
        }
        catch(Exception e){throw new AuraHandledException(e.getMessage());}
    }
        
}