force-app/main/default/objects/inspire1__Attribute_Assignment__c/inspire1__Attribute_Assignment__c.object-meta.xml
<CustomObject>
    <description>Inspire Planner - Captures assignment of attributes to Users or Contacts.</description>
    <label>Attribute Assignment</label>
    <nameField>
        <displayFormat>RAA-{000000}</displayFormat>
        <label>Assignment No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attribute Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/inspire1__Attribute_Assignment__c/fields/inspire1__Contact__c.field-meta.xml
<CustomField>
    <fullName>inspire1__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact the attribute is assigned to.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Attribute Assignments</relationshipLabel>
    <relationshipName>Attribute_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/inspire1__Attribute_Assignment__c/fields/inspire1__Resource_Attribute__c.field-meta.xml
<CustomField>
    <fullName>inspire1__Resource_Attribute__c</fullName>
    <description>Resource attribute related to assignment.</description>
    <label>Resource Attribute</label>
    <referenceTo>inspire1__Resource_Attribute__c</referenceTo>
    <relationshipLabel>Attribute Assignments</relationshipLabel>
    <relationshipName>Attribute_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/inspire1__Resource_Attribute__c/inspire1__Resource_Attribute__c.object-meta.xml
<CustomObject>
    <description>Inspire Planner - Captures attributes that can be assigned to a resource such as skill, expertise, certification, geographic region, etc.</description>
    <label>Resource Attribute</label>
    <nameField>
        <label>Attribute Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/inspire1__Resource_Attribute__c/fields/inspire1__Type__c.field-meta.xml
<CustomField>
    <fullName>inspire1__Type__c</fullName>
    <description>Defines the type of attribute</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Department</fullName>
            </value>
            <value>
                <fullName>Job Title</fullName>
            </value>
            <value>
                <fullName>Language</fullName>
            </value>
            <value>
                <fullName>Region</fullName>
            </value>
            <value>
                <fullName>Skill</fullName>
                <default>true</default>
                <label>Skill</label>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Expertise</fullName>
                <isActive>false</isActive>
                <label>Expertise</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SCS_SchedularDeleteAttriAssignment_Test.cls
/**************************************************** New ORG CODE ***************************************************************** 
* Class Name        : SCS_SchedularDeleteAttriAssignment_Test
* Related class     : SCS_SchedularDeleteAttributeAssignment and SCS_DeleteAttributeAssignment
* Version           : 1.0
* Functionality     : 

* Modification Log  : This test class test the functionality of SCS_SchedularDeleteAttributeAssignment and SCS_DeleteAttributeAssignment
-------------------------------------------------------------------------------------------------------------------------------------------------
* Developer Name                     Date                                Description
* -----------------------------------------------------------------------------------------------------------------------------------------------
* Umesh Kumar                        08-06-2023                          Initial version 
************************************************************************************************************************************/


@isTest
public class SCS_SchedularDeleteAttriAssignment_Test {
    
    //Setup data...
    @testSetup static void setup() {
        //Insert sales user...
        List<User> userList = SCS_TestDataFactory.createUser('System Administrator',1);
        userList[0].Username ='scsadministrator@scsuser.com';
        insert userList;
        //Execute with respect to sales user...
        System.runAs(userList[0]){
            //Insert account...
            List<Account> accountList = SCS_TestDataFactory.createAccounts(SNM_TestConstant.customerAccRTId,1);
            insert accountList;
            //Insert Contact...
            List<Contact> contactList = SCS_TestDataFactory.createContacts(accountList[0].Id,SNM_TestConstant.customerConRTId,1);
            insert contactList;
            //Insert Resource Attribute...
            inspire1__Resource_Attribute__c resourceAttribute = new inspire1__Resource_Attribute__c (Name = 'RATEST',inspire1__Type__c = 'Skill');
            insert resourceAttribute;
            //Insert Attribute Assignment...
            inspire1__Attribute_Assignment__c attributeAssignment = new inspire1__Attribute_Assignment__c ();
            attributeAssignment.inspire1__Contact__c = contactList[0].Id;
            attributeAssignment.inspire1__Resource_Attribute__c = resourceAttribute.Id;
            Date dt = Date.today();
            dt = dt.addDays(-1);
            attributeAssignment.EndDate__c = dt;
            insert attributeAssignment;
        }
    }
    
    @isTest static void testAttributeAssignmentDeletionSchedular() {
        Test.startTest();
        //Query sales user...
        User usr =[SELECT Id FROM User WHERE Username = 'scsadministrator@scsuser.com' LIMIT 1];
        System.runAs(usr){
            SCS_SchedularDeleteAttributeAssignment obj = new SCS_SchedularDeleteAttributeAssignment();
            obj.execute(null);
        }
        Test.stopTest();
        //Get records ...
        List<inspire1__Attribute_Assignment__c> recordList =[SELECT Id FROM inspire1__Attribute_Assignment__c];
        //Verify the response...
        System.assertEquals(0,recordList.size(),'Record should be deleted');
    }
    
}