force-app/main/default/objects/ContentVersion/fields/Sent__c.field-meta.xml
<CustomField>
    <fullName>Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/inspire1__Project__c/inspire1__Project__c.object-meta.xml
<CustomObject>
    <description>Inspire Planner - This object captures the detail of the project record</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Certificate__c/Opportunity_Certificate__c.object-meta.xml
<CustomObject>
    <label>Opportunity Certificate</label>
    <nameField>
        <displayFormat>OC-{0000}</displayFormat>
        <label>Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Certificates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SCS_ContentDocumentLinkTriggerHelper.cls
public with sharing class SCS_ContentDocumentLinkTriggerHelper {
    
    //This method uploads the file in sharepoint folder
    public static void uploadFileInSharePoint(List<ContentDocumentLink> newList){
        
        List<ContentDocumentLink> contentDocList = new List<ContentDocumentLink>();
        for(ContentDocumentLink contentDocLink : newList) {
            String strObjPrefix = String.valueOf(contentDocLink.LinkedEntityId).substring(0, 3);
            if(strObjPrefix == Account.sObjectType.getDescribe().getKeyPrefix() || strObjPrefix == Opportunity.sObjectType.getDescribe().getKeyPrefix() || strObjPrefix == inspire1__Project__c.sObjectType.getDescribe().getKeyPrefix() || strObjPrefix == Opportunity_Certificate__c.sObjectType.getDescribe().getKeyPrefix()) {
                System.debug('strObjPrefix-9- '+strObjPrefix);
                contentDocList.add(contentDocLink);
            }
        }
        
        if(contentDocList != null && !contentDocList.isEmpty()){
            System.enqueuejob(new sFilesQueable(contentDocList));
        }
    }
    
    //This method update the content version of the file when file is sent from Email Message
    /*public static void updateContentVersion(List<ContentDocumentLink> newList){
        List<ContentVersion> conVerListToUpdate = new List<ContentVersion>();
        Set<Id> contentDocIdSet = new Set<Id>();
        for(ContentDocumentLink contentDocLink : newList) {
            String strObjPrefix = String.valueOf(contentDocLink.LinkedEntityId).substring(0, 3);
            if(strObjPrefix == EmailMessage.sObjectType.getDescribe().getKeyPrefix()){
                contentDocIdSet.add(contentDocLink.ContentDocumentId);
            }
        }
        
        if(!contentDocIdSet.isEmpty()){
            for(ContentVersion conVer : [SELECT Id, Title, FileExtension, ContentDocumentId, FirstPublishLocationId FROM ContentVersion WHERE ContentDocumentId IN:contentDocIdSet]){
                conVer.Sent__c = true;
                conVerListToUpdate.add(conVer);
            }
        }
        
        if(!conVerListToUpdate.isEmpty()){
            update conVerListToUpdate;
        }
    }*/

}