force-app/main/default/objects/fw1__Invoice__c/fw1__Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/fw1__Invoice__c/fields/fw1__Opportunity__c.field-meta.xml
<CustomField>
    <fullName>fw1__Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/fw1__Invoice__c/fields/fw1__Status__c.field-meta.xml
<CustomField>
    <fullName>fw1__Status__c</fullName>
    <formula>IF( fw1__Is_Voided__c, 
    $Label.fw1__Voided, 
    IF( fw1__Installments_Reconfiguration_Needed__c , 
        $Label.fw1__Reconfigure_Installments, 
        IF( fw1__Is_Overdue__c, 
            $Label.fw1__Overdue, 
            fw1__Status_Sys__c
        ) 
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fw1__Invoice__c/fields/fw1__Total_Invoice_Amount__c.field-meta.xml
<CustomField>
    <fullName>fw1__Total_Invoice_Amount__c</fullName>
    <formula>ROUND( 
fw1__Total_Installment_Fees__c +
fw1__Total_Additional_Charges__c + 
fw1__Revolving_Balance__c + 
fw1__Net_Amount__c + 
fw1__Tax_Amount__c +  
fw1__Shipping_And_Handling__c + 
((IF(fw1__Net_Amount__c &gt; fw1__Total_Non_Installment__c, 
     fw1__Net_Amount__c - fw1__Total_Non_Installment__c, 
     0))  *   fw1__Installment_Fee__c ),2)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Invoice Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/fw1__Invoice__c/fields/fw1__Total_Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>fw1__Total_Paid_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Paid Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/fw1__Invoice__c/fields/Invoice_Type__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Type__c</fullName>
    <label>Invoice Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Event__e/Invoice_Event__e.object-meta.xml
<CustomObject>
    <label>Invoice_Event</label>
    <pluralLabel>Invoice_Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Invoice_Event__e/fields/Invoice_Id__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Id__c</fullName>
    <label>Invoice Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Final_Invoice_Amount__c.field-meta.xml
<CustomField>
    <fullName>Final_Invoice_Amount__c</fullName>
    <label>Final Invoice Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Final_Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Final_Invoice_Number__c</fullName>
    <label>Final Invoice Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Final_Invoice_Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Final_Invoice_Paid_Amount__c</fullName>
    <label>Final Invoice Paid Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Final_Invoice_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Final_Invoice_Payment_Date__c</fullName>
    <label>Final Invoice Payment Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Final_Invoice_Send_Date__c.field-meta.xml
<CustomField>
    <fullName>Final_Invoice_Send_Date__c</fullName>
    <label>Final Invoice Send Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/fw1__Total_Invoice_Amount__c.field-meta.xml
<CustomField>
    <fullName>fw1__Total_Invoice_Amount__c</fullName>
    <label>Total Invoice Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/fw1__Total_Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>fw1__Total_Paid_Amount__c</fullName>
    <label>Total Paid Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Initial_Invoice_Amount__c.field-meta.xml
<CustomField>
    <fullName>Initial_Invoice_Amount__c</fullName>
    <label>Initial Invoice Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Initial_Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Initial_Invoice_Number__c</fullName>
    <label>Initial Invoice Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Initial_Invoice_Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Initial_Invoice_Paid_Amount__c</fullName>
    <label>Initial Invoice Paid Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Initial_Invoice_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Initial_Invoice_Payment_Date__c</fullName>
    <label>Initial Invoice Payment Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Initial_Invoice_Send_Date__c.field-meta.xml
<CustomField>
    <fullName>Initial_Invoice_Send_Date__c</fullName>
    <label>Initial Invoice Send Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Invoice_Type__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Type__c</fullName>
    <label>Invoice Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial</fullName>
            </value>
            <value>
                <fullName>Final</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SCS_InvoiceTriggerHelper.cls
/****************************************************New ORG CODE ***************************************************************** 
* Class  Name       : SCS_InvoiceTriggerHelper
* Division          : Food and Agriculture
* Version           : 1.1
* Code reviewed By  : N/A
* JIRA Ticket       : SF20FA-1315
* Functionality     : This helper use in SCS_InvoiceTriggerHandler class to update initial and final invoice amount on opportunity.

* Modification Log  :
-------------------------------------------------------------------------------------------------------------------------------------------------
* Developer Name                     Date                                Description
* -----------------------------------------------------------------------------------------------------------------------------------------------
* Umesh Kumar                        13-04-2023                          Initial version 
* Umesh Kumar                        13-04-2023                          Update initial and final invoice amount on opportunity when status is sent or paid.
************************************************************************************************************************************/

public with sharing class SCS_InvoiceTriggerHelper {
    //call from trigger handler when invoice record is update...
    public static void fireEventToupdateInitialOrFinalAmount(List<fw1__Invoice__c> newTrigger,Map<Id,fw1__Invoice__c> oldMap){
        List<Invoice_Event__e> invoiceIds = new List<Invoice_Event__e>();
        for(fw1__Invoice__c record : newTrigger){
            if(record.fw1__Opportunity__c != null && record.fw1__Status__c != oldMap.get(record.Id).fw1__Status__c && ( record.fw1__Status__c == 'Sent' || record.fw1__Status__c == 'Paid')){
                invoiceIds.add(new Invoice_Event__e(Invoice_Id__c = record.Id));
            }
        }
        if(! invoiceIds.isEmpty()){
            EventBus.publish(invoiceIds);
            system.debug('Fire Event');
        }
    }
    
    public static void updateAmountAndDate(Set<Id> opportunitySet,List<fw1__Invoice__c> newInvoiceList){
        //if opportunity set in not empty...
        if(! opportunitySet.isEmpty() && ! newInvoiceList.isEmpty()){
            //Query the all invoice related opportunity using opportunity set...
            Map<Id,Opportunity> opportunityMap = new Map<Id,Opportunity>([SELECT Id,Initial_Invoice_Number__c,Initial_Invoice_Amount__c,Initial_Invoice_Paid_Amount__c,Final_Invoice_Number__c,Final_Invoice_Amount__c,Final_Invoice_Paid_Amount__c,Invoice_Type__c,Initial_Invoice_Send_Date__c,Final_Invoice_Send_Date__c,Initial_Invoice_Payment_Date__c,Final_Invoice_Payment_Date__c FROM Opportunity WHERE Id IN :opportunitySet]);
            for(fw1__Invoice__c invRecord : newInvoiceList){
                if(invRecord.fw1__Opportunity__c != null){
                    Opportunity oppRecord = opportunityMap.containsKey(invRecord.fw1__Opportunity__c) ? opportunityMap.get(invRecord.fw1__Opportunity__c) : null;
                    if(oppRecord !=null){
                        //if invoice sent to customer...
                        if(invRecord.fw1__Status__c == 'Sent'){
                            //if initial invoice sent to customer then add initial invoice amount on opportunity...
                            if(oppRecord.Initial_Invoice_Number__c == null){
                                oppRecord.Initial_Invoice_Number__c = invRecord.Name;
                                oppRecord.Initial_Invoice_Amount__c = invRecord.fw1__Total_Invoice_Amount__c;
                                oppRecord.Initial_Invoice_Send_Date__c = System.now();
                                oppRecord.Invoice_Type__c = 'Initial';
                                //if final invoice sent to customer then add final invoice amount on opportunity...
                            } else if(oppRecord.Initial_Invoice_Number__c!=null && ! oppRecord.Initial_Invoice_Number__c.contains(invRecord.Name)){
                                oppRecord.Final_Invoice_Number__c = oppRecord.Final_Invoice_Number__c != null ? oppRecord.Final_Invoice_Number__c+','+invRecord.Name : invRecord.Name;
                                oppRecord.Final_Invoice_Amount__c =  oppRecord.Final_Invoice_Amount__c != null ? oppRecord.Final_Invoice_Amount__c + invRecord.fw1__Total_Invoice_Amount__c : invRecord.fw1__Total_Invoice_Amount__c;
                                oppRecord.Final_Invoice_Send_Date__c = System.now();
                                oppRecord.Invoice_Type__c = 'Final';
                            }
                            //if invoice paid by customer...
                        } else if(invRecord.fw1__Status__c == 'Paid'){
                            //if initial invoice paid by customer then add initial invoice amount on opportunity...
                            if(oppRecord.Initial_Invoice_Number__c != null && oppRecord.Initial_Invoice_Number__c.contains(invRecord.Name)){
                                oppRecord.Initial_Invoice_Paid_Amount__c =  invRecord.fw1__Total_Paid_Amount__c;
                                oppRecord.Initial_Invoice_Payment_Date__c = System.now();
                                //if final invoice paid by customer then add final invoice amount on opportunity...
                            } else if(oppRecord.Final_Invoice_Number__c != null && oppRecord.Final_Invoice_Number__c.contains(invRecord.Name) && oppRecord.Invoice_Type__c == 'Final'){
                                oppRecord.Final_Invoice_Paid_Amount__c =  oppRecord.Final_Invoice_Paid_Amount__c != null ? oppRecord.Final_Invoice_Paid_Amount__c + invRecord.fw1__Total_Paid_Amount__c : invRecord.fw1__Total_Paid_Amount__c;
                                oppRecord.Final_Invoice_Payment_Date__c = System.now();
                            }
                        }
                        opportunityMap.put(oppRecord.Id,oppRecord);
                    } 
                }
            }
            //update opportunity with initial amount or final amount...
            if(! opportunityMap.isEmpty()){
                update opportunityMap.values();
            } 
        }
    }
}