force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>SCS Global Services departments</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/ECS.recordType-meta.xml
<RecordType>
    <fullName>ECS</fullName>
    <active>true</active>
    <businessProcess>SCS Global Services Sales Process</businessProcess>
    <label>ECS</label>
</RecordType>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Contact_Role__c/Program_Contact_Role__c.object-meta.xml
<CustomObject>
    <label>Program Contact Role</label>
    <nameField>
        <displayFormat>PCR-{000}</displayFormat>
        <label>Program Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Contact_Role__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Contact Roles</relationshipLabel>
    <relationshipName>Program_Contact_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProgramContactRole_Test.cls
@isTest
public class ProgramContactRole_Test {
    
    @testSetup static void setup() {


        Id accRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Customer').getRecordTypeId();
        Id oppRTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('ECS').getRecordTypeId();
        Id conRTId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Customer').getRecordTypeId();

        List<Account> accountList = SCS_TestDataFactory.createAccounts(accRTId,1);
        accountList[0].BillingCountry= 'United States';
        insert accountList;
        //Create Program record...
        List<Program__c> proList = SCS_TestDataFactory.createPrograms(1);
        proList[0].name = 'SQF';
        insert proList;
        //Create Campaign record... 
        List<Campaign> campaign = SCS_TestDataFactory.createCampaing(1);
        insert campaign;
        //Create Contact record...
        List<Contact> conList = SCS_TestDataFactory.createContacts(accountList[0].Id,conRTId,1);
        insert conList;

        List<Program_Contact_Role__c> pcr = SCS_TestDataFactory.createProgramContactRole(conList[0].Id,proList[0].Id,1 );
        insert pcr;
    
    }

    @isTest static void testPCR() {

        Program__c prId = [SElect id from Program__c where CreatedDate = Today Limit 1];
        Account accId = [Select Id from Account Where CreatedDate = Today Limit 1];
        
        List<ProgramContactRole.ProgramContactRoleWrapper> progRoleList = ProgramContactRole.getProgramContactRoleData(prId.Id, accId.Id);

        System.assert(progRoleList.size() > 0); 

    }


}