force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>SCS Global Services departments</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/CustomerSite.recordType-meta.xml
<RecordType>
    <fullName>CustomerSite</fullName>
    <active>true</active>
    <label>Customer Site</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Auditor.recordType-meta.xml
<RecordType>
    <fullName>Auditor</fullName>
    <active>true</active>
    <label>Auditor</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Goal__c/Goal__c.object-meta.xml
<CustomObject>
    <label>Goal</label>
    <nameField>
        <displayFormat>G-{00000}</displayFormat>
        <label>Goal Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Goal__c/recordTypes/Program_Goal.recordType-meta.xml
<RecordType>
    <fullName>Program_Goal</fullName>
    <active>true</active>
    <label>Program Goal</label>
</RecordType>

force-app/main/default/objects/Goal__c/recordTypes/User_Goal.recordType-meta.xml
<RecordType>
    <fullName>User_Goal</fullName>
    <active>true</active>
    <label>User Goal</label>
</RecordType>

force-app/main/default/objects/inspire1__Project__c/inspire1__Project__c.object-meta.xml
<CustomObject>
    <description>Inspire Planner - This object captures the detail of the project record</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/inspire1__Project__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ISH</fullName>
            </value>
            <value>
                <fullName>P&amp;C - POM</fullName>
            </value>
            <value>
                <fullName>NPP</fullName>
            </value>
            <value>
                <fullName>Special Audit</fullName>
            </value>
            <value>
                <fullName>SCC - Independent Mill</fullName>
            </value>
            <value>
                <fullName>SCC - Other</fullName>
            </value>
            <value>
                <fullName>SCC - PKC</fullName>
            </value>
            <value>
                <fullName>SCC - Port</fullName>
            </value>
            <value>
                <fullName>SCC - Refinery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/inspire1__Project__c/recordTypes/SCS_Standard.recordType-meta.xml
<RecordType>
    <fullName>SCS_Standard</fullName>
    <active>true</active>
    <description>RT for SCS Standard Records</description>
    <label>SCS Standard</label>
</RecordType>

force-app/main/default/objects/inspire1__Project__c/recordTypes/Training_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Training_Opportunity</fullName>
    <active>true</active>
    <label>Training_Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/SCS_Standard.recordType-meta.xml
<RecordType>
    <fullName>SCS_Standard</fullName>
    <active>true</active>
    <businessProcess>SCS Standard Sales Process</businessProcess>
    <label>SCS Standard</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Training_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Training_Opportunity</fullName>
    <active>true</active>
    <businessProcess>SCS Global Services Sales Process</businessProcess>
    <label>Training Opportunity</label>
</RecordType>

force-app/main/default/objects/Scope__c/Scope__c.object-meta.xml
<CustomObject>
    <description>Program / Project Scope</description>
    <label>Scope</label>
    <nameField>
        <displayFormat>SC-{0000000}</displayFormat>
        <label>Scope #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scope</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scope__c/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Scope__c/recordTypes/Project.recordType-meta.xml
<RecordType>
    <fullName>Project</fullName>
    <active>true</active>
    <description>Project Scope</description>
    <label>Project</label>
</RecordType>

force-app/main/default/objects/Scope__c/recordTypes/Sub_Scope.recordType-meta.xml
<RecordType>
    <fullName>Sub_Scope</fullName>
    <active>true</active>
    <description>Use only for Program Specific Sub Scope Scope(Use Add Sub Scope button from Opportunity)</description>
    <label>Sub Scope</label>
</RecordType>

force-app/main/default/classes/SCS_ConstantRTypeReference.cls
/*
@Author : MAANTIC
@CreatedDate : 28th JULY 2022
@Description : Product Object Trigger Handler.
*/

public class SCS_ConstantRTypeReference {
    
    //Goal
    public static Id programGoal_Goal_RTId = Schema.SObjectType.Goal__c.getRecordTypeInfosByDeveloperName().get('Program_Goal').getRecordTypeId();
    public static Id userGoal_Goal_RTId = Schema.SObjectType.Goal__c.getRecordTypeInfosByDeveloperName().get('User_Goal').getRecordTypeId();
   
    //Account
    public static Id customerSite_Account_RTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('CustomerSite').getRecordTypeId();
    public static Id account_Account_RTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Customer').getRecordTypeId();
   
    //Contact
    public static Id standard_Contact_RTId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Customer').getRecordTypeId();
    public static Id auditor_Contact_RTId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Auditor').getRecordTypeId();
    //public static Id stakeholder_Contact_RTId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Stakeholder').getRecordTypeId();
    
    //Opportunity
    public static Id standard_RTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('SCS_Standard').getRecordTypeId();
    public static Id training_Oppo_RTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Training_Opportunity').getRecordTypeId();
    
    //Project
    public static Id standard_Project_RTId = Schema.SObjectType.inspire1__Project__c.getRecordTypeInfosByDeveloperName().get('SCS_Standard').getRecordTypeId();
    
    //Scope 
    public static Id scope_SubScopeRTId = Schema.SObjectType.Scope__c.getRecordTypeInfosByDeveloperName().get('Sub_Scope').getRecordTypeId();
    public static Id scope_opportunityRTId = Schema.SObjectType.Scope__c.getRecordTypeInfosByDeveloperName().get('Opportunity').getRecordTypeId();
    
}