force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>SCS Global Services departments</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/CustomerSite.recordType-meta.xml
<RecordType>
    <fullName>CustomerSite</fullName>
    <active>true</active>
    <label>Customer Site</label>
</RecordType>

force-app/main/default/objects/Certificate__c/Certificate__c.object-meta.xml
<CustomObject>
    <description>Certificate issued to Client</description>
    <label>Certificate</label>
    <nameField>
        <displayFormat>CRT-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certificates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certificate__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Certificates</relationshipLabel>
    <relationshipName>Certificates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Opportunity with or without products
Total Opportunity Amount</description>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Food_and_Agriculture.recordType-meta.xml
<RecordType>
    <fullName>Food_and_Agriculture</fullName>
    <active>true</active>
    <businessProcess>SCS Global Services Sales Process</businessProcess>
    <label>Food and Agriculture</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Natural_Resources.recordType-meta.xml
<RecordType>
    <fullName>Natural_Resources</fullName>
    <active>true</active>
    <businessProcess>SCS Global Services Sales Process</businessProcess>
    <label>Natural Resources</label>
</RecordType>

force-app/main/default/objects/Opportunity_Certificate__c/Opportunity_Certificate__c.object-meta.xml
<CustomObject>
    <label>Opportunity Certificate</label>
    <nameField>
        <displayFormat>OC-{0000}</displayFormat>
        <label>Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Certificates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Certificate__c/fields/Certificate__c.field-meta.xml
<CustomField>
    <fullName>Certificate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Certificate</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Certificate__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Certificate__c</referenceTo>
    <relationshipLabel>Opportunity Certificates</relationshipLabel>
    <relationshipName>Opportunity_Certificates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/SCSGlobal_CreateCertificateHelper_Test.cls
@isTest
public class SCSGlobal_CreateCertificateHelper_Test 
{
    
    @testSetup static void setup() 
    {
        //Create Sales user...
        Id accRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Customer').getRecordTypeId();
        Id naturalResourcesId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Natural_Resources').getRecordTypeId();
        Id accRTS_Id = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('CustomerSite').getRecordTypeId();
        Id oppRT_Id = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Food_and_Agriculture').getRecordTypeId();
        Id oppChRT_Id = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Food_and_Agriculture').getRecordTypeId();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorClass());
        //Create record...
        List<Account> accountList = SCS_TestDataFactory.createAccounts(accRTId,1);
		accountList[0].name = 'United PIPES';       
        accountList[0].BillingCountry= 'United States';
        insert accountList;
        
        List<Account> accListS = SCS_TestDataFactory.createAccounts(accRTS_Id,1);
        accListS[0].BillingCountry= 'United Kingdom';
        accListS[0].ParentId = accountList[0].id;
        insert accListS; 
        
        List<Program__c> proList = SCS_TestDataFactory.createPrograms(2);
        proList[0].name = 'SQF';
        proList[1].name = 'IRMA';
        insert proList; 
        
        List<Opportunity> oppList = SCS_TestDataFactory.createOpportunity('Enquiry',accountList[0].Id,proList[0].Id,naturalResourcesId ,Date.newInstance(2025,1,5),1);
        oppList[0].Type = 'New Business';
        oppList[0].TotalAmount__c = 1000;
        insert oppList;
        List<Certificate__c> certList =new List<Certificate__c>();
    	List<Opportunity_certificate__c> opcerlist = new List<Opportunity_certificate__c>();
        
        certList = SCS_TestDataFactory.createCertificate(1);
        insert certList;
        
        opcerlist = SCS_TestDataFactory.createOppsCertificate(certList[0], oppList);
        insert opcerlist;
        
        
        
    }
    
    public static testmethod void getCertificateFromOpportunityTest()
    {
        List<User> integratorUser = SCS_TestDataFactory.createUsers(SCS_TestDataFactory.getSystemIntegratorProfile(), 1);
        System.runAs(integratorUser[0]){
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorClass());
            List<Opportunity> opptylist=[SELECT Id FROM Opportunity LIMIT 1];
            Test.startTest();
           
            List<Certificate__c> ctlist = [select id from certificate__c limit 1];
            List<Opportunity_Certificate__c> oclist = new List<Opportunity_Certificate__C>();
            oclist = [Select id, certificate__C from Opportunity_Certificate__c limit 1];
            Certificate__c cc = [select id from certificate__c where id=:ctlist[0].id];
            Opportunity_Certificate__c opc = [Select certificate__c from Opportunity_Certificate__c where id=:oclist[0].id];
            
            System.debug('cc:' + cc);
            SCSGlobal_CreateCertificateHelper.getCertificateFromOpportunity(10,1,opptylist[0].Id);
            SCSGlobal_CreateCertificateHelper.getFieldsListFromFieldSet('SQF');
            //createCertificateAndOC(Certificate__c cert, Opportunity_Certificate__c oppCert, String existingCertId)
			Certificate__c cert = new Certificate__c();
            Opportunity_Certificate__c oppCert = new Opportunity_Certificate__c();
            SCSGlobal_CreateCertificateHelper.createCertificateAndOC(cert, oppCert, cc.id);
            Test.stopTest();
        }
    }
    
    public static testmethod void getCertificateFromOpportunityTest2()
    {
        List<User> integratorUser = SCS_TestDataFactory.createUsers(SCS_TestDataFactory.getSystemIntegratorProfile(), 1);
        System.runAs(integratorUser[0]){
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorClass());
            List<Opportunity> opptylist=[SELECT Id FROM Opportunity LIMIT 1];
            Test.startTest();
           
            List<Certificate__c> ctlist = [select id from certificate__c limit 1];
            List<Opportunity_Certificate__c> oclist = new List<Opportunity_Certificate__C>();
            oclist = [Select id, certificate__C from Opportunity_Certificate__c limit 1];
            Certificate__c cc = [select id from certificate__c where id=:ctlist[0].id];
            Opportunity_Certificate__c opc = [Select certificate__c from Opportunity_Certificate__c where id=:oclist[0].id];
            
            System.debug('cc:' + cc);
            SCSGlobal_CreateCertificateHelper.getCertificateFromOpportunity(10,1,opptylist[0].Id);
            SCSGlobal_CreateCertificateHelper.getFieldsListFromFieldSet('SQF');
            SCSGlobal_CreateCertificateHelper.getCertificateFieldsfromFieldSet('SQF');
            //createCertificateAndOC(Certificate__c cert, Opportunity_Certificate__c oppCert, String existingCertId)
			//Certificate__c cert = new Certificate__c();
            Opportunity_Certificate__c oppCert = new Opportunity_Certificate__c();
            SCSGlobal_CreateCertificateHelper.createCertificateAndOC(cc, oppCert, cc.id);
             SCSGlobal_CreateCertificateHelper.checkProjectExist(opptylist[0].Id);
            Test.stopTest();
        }
    }
}