force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>SCS Global Services departments</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/CustomerSite.recordType-meta.xml
<RecordType>
    <fullName>CustomerSite</fullName>
    <active>true</active>
    <label>Customer Site</label>
</RecordType>

force-app/main/default/objects/Certificate__c/Certificate__c.object-meta.xml
<CustomObject>
    <description>Certificate issued to Client</description>
    <label>Certificate</label>
    <nameField>
        <displayFormat>CRT-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certificates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certificate__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Certificates</relationshipLabel>
    <relationshipName>Certificates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Certificate__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Certificates</relationshipLabel>
    <relationshipName>Certificates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Certified_Sites__c/Certified_Sites__c.object-meta.xml
<CustomObject>
    <label>Certified Site</label>
    <nameField>
        <displayFormat>CS-{0000000}</displayFormat>
        <label>Certified Sites Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certified Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certified_Sites__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Certified Sites (Customer)</relationshipLabel>
    <relationshipName>Certified_Sites1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Certified_Sites__c/fields/Certificate__c.field-meta.xml
<CustomField>
    <fullName>Certificate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Certificate</label>
    <referenceTo>Certificate__c</referenceTo>
    <relationshipLabel>Certified Sites</relationshipLabel>
    <relationshipName>Certified_Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Certified_Sites__c/fields/CustomerSite__c.field-meta.xml
<CustomField>
    <fullName>CustomerSite__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Site</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer Site</value>
        </filterItems>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>Account.ParentId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Certified Sites</relationshipLabel>
    <relationshipName>Certified_Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Certified_Species__c/Certified_Species__c.object-meta.xml
<CustomObject>
    <description>FSC</description>
    <label>Certified Species</label>
    <nameField>
        <label>Certified Species Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certified Species</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certified_Species__c/fields/Species__c.field-meta.xml
<CustomField>
    <fullName>Species__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Species</label>
    <referenceTo>Species__c</referenceTo>
    <relationshipLabel>Certified Species</relationshipLabel>
    <relationshipName>Certified_Species</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Certified_volume__c/Certified_volume__c.object-meta.xml
<CustomObject>
    <label>Certified volume</label>
    <nameField>
        <displayFormat>CV-{0000}</displayFormat>
        <label>Certified volume Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certified Volumes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certified_volume__c/fields/Opportunity_Certificate__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Certificate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Certificate</label>
    <referenceTo>Opportunity_Certificate__c</referenceTo>
    <relationshipLabel>Certified Volumes</relationshipLabel>
    <relationshipName>Certified_Volumes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CertifiedProducts__c/CertifiedProducts__c.object-meta.xml
<CustomObject>
    <label>Certified Product</label>
    <nameField>
        <displayFormat>CRTP-{0000000}</displayFormat>
        <label>Certified Products Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certified Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CertifiedProducts__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Certified Products</relationshipLabel>
    <relationshipName>Certified_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CertifiedProducts__c/fields/Certificate__c.field-meta.xml
<CustomField>
    <fullName>Certificate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Certificate</label>
    <referenceTo>Certificate__c</referenceTo>
    <relationshipLabel>Certified Products</relationshipLabel>
    <relationshipName>Certified_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CertifiedProducts__c/recordTypes/SQF.recordType-meta.xml
<RecordType>
    <fullName>SQF</fullName>
    <active>true</active>
    <label>SQF</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Bundle_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Bundle_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bundle Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>Bundle Opportunity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Previous_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Previous_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Previous Opportunity</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Opportunity.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Bundle_Opportunity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities (Previous Opportunity)</relationshipLabel>
    <relationshipName>PreviousOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Programc__c.field-meta.xml
<CustomField>
    <fullName>Programc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>The selected program is deprecated, please select another program</errorMessage>
        <filterItems>
            <field>Program__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Deprecated</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Food_and_Agriculture.recordType-meta.xml
<RecordType>
    <fullName>Food_and_Agriculture</fullName>
    <active>true</active>
    <businessProcess>SCS Global Services Sales Process</businessProcess>
    <label>Food and Agriculture</label>
</RecordType>

force-app/main/default/objects/Opportunity_Certificate__c/Opportunity_Certificate__c.object-meta.xml
<CustomObject>
    <label>Opportunity Certificate</label>
    <nameField>
        <displayFormat>OC-{0000}</displayFormat>
        <label>Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Certificates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Certificate__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunity Certificates</relationshipLabel>
    <relationshipName>Opportunity_Certificates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Certificate__c/fields/Certificate__c.field-meta.xml
<CustomField>
    <fullName>Certificate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Certificate</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Certificate__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Certificate__c</referenceTo>
    <relationshipLabel>Opportunity Certificates</relationshipLabel>
    <relationshipName>Opportunity_Certificates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Species__c/Species__c.object-meta.xml
<CustomObject>
    <description>FSC</description>
    <label>Species</label>
    <nameField>
        <label>Species Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Species</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/createRenewalOpportunityCertificate_Test.cls
/***************
Class: createRenewalOpportunityCertificate_Test
Description : Test class for createRenewalOpportunityCertificate
Author: Amitava Dutta
*******************/
@isTest
public class createRenewalOpportunityCertificate_Test {

    @TestSetup
    static void makeData(){
     
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorClass());
        Id accRT_Id = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Customer').getRecordTypeId();
        Id accRTS_Id = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('CustomerSite').getRecordTypeId();
        Id oppRT_Id = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Food_and_Agriculture').getRecordTypeId();
        Id oppChRT_Id = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Food_and_Agriculture').getRecordTypeId();
        

        List<Account> accList = SCS_TestDataFactory.createAccounts(accRT_Id,1);
        accList[0].name = 'cust_acc';
        accList[0].BillingCountry= 'United States';
        insert accList;   
        
        List<Account> accListS = SCS_TestDataFactory.createAccounts(accRTS_Id,1);
        accListS[0].BillingCountry= 'United Kingdom';
        accListS[0].ParentId = accList[0].id;
        
        insert accListS;  
        
        List<Program__c> proList = SCS_TestDataFactory.createPrograms(1);
        proList[0].name = 'SQF';
        insert proList; 

        List<Opportunity> oppList = SCS_TestDataFactory.createOpportunity('Enquiry',accList[0].Id,null,oppRT_Id,Date.Today(),1);
        oppList[0].CloseDate = Date.Today().addYears(1);
        //oppList[0].Programc__c = proList[0].Id;
        insert oppList; 
        System.debug('OPPLIST' +  oppList);
        	
        List<Opportunity> oppListCh = SCS_TestDataFactory.createOpportunity('Enquiry',accList[0].Id,null,oppChRT_Id,Date.Today(),1);
        
        oppListCh[0].previous_opportunity__c = oppList[0].id;
        //System.debug('OPPLIST' +  oppListCh[0].Bundle_Opportunity__c);
        
        insert oppListCh;
        
        List<Certificate__c> certList = SCS_TestDataFactory.createCertificate(1);
        insert certList;
        
        List<Opportunity_certificate__c> opcerlist = SCS_TestDataFactory.createOppsCertificate(certList[0], oppList);
        insert opcerlist;

        List<CertifiedProducts__c> certProdList = SCS_TestDataFactory.createOppCertifiedProds(opcerlist[0].Id, 1);
        insert certProdList;

        List<Species__c> specList = SCS_TestDataFactory.createSpecies(1);
        insert specList;

        List<Certified_Species__c> certSpecList = SCS_TestDataFactory.createCertifiedSpecies(certProdList[0].Id,specList[0].Id,1);
        insert certSpecList;

        List<Certified_volume__c> certVolSpecList = SCS_TestDataFactory.createCertifiedVolume(opcerlist[0].Id,1);
        insert certVolSpecList;
        
        List<Certified_Sites__c> cstlist = SCS_TestDataFactory.createCertifiedSites(opcerlist);
        cstlist[0].CustomerSite__c = accListS[0].Id;
        cstList[0].Account__c = accList[0].id;
        insert cstlist;
        

    }
    static testMethod void createRenewalOpportunityCertificate()
    {
       test.startTest();
       Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorClass());
       Opportunity opm = [select id,name,previous_opportunity__c from opportunity where previous_opportunity__c !=null limit 1 ] ;
       List<String> opids = new List<string>(); opids.add(opm.id);
       createRenewalOpportunityCertificate.createRenewalOpportunityCertificateAndCertifiedSites(opids);
        
        
       test.stopTest(); 
    }
}