force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>SCS Global Services departments</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Goal__c/Goal__c.object-meta.xml
<CustomObject>
    <label>Goal</label>
    <nameField>
        <displayFormat>G-{00000}</displayFormat>
        <label>Goal Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Goal__c/fields/Programc__c.field-meta.xml
<CustomField>
    <fullName>Programc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Goals</relationshipLabel>
    <relationshipName>Goals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Goal__c/recordTypes/Program_Goal.recordType-meta.xml
<RecordType>
    <fullName>Program_Goal</fullName>
    <active>true</active>
    <label>Program Goal</label>
</RecordType>

force-app/main/default/objects/inspire1__Project__c/inspire1__Project__c.object-meta.xml
<CustomObject>
    <description>Inspire Planner - This object captures the detail of the project record</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/inspire1__Project__c/recordTypes/Bundle_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Bundle_Opportunity</fullName>
    <active>true</active>
    <label>Bundle Opportunity</label>
</RecordType>

force-app/main/default/objects/inspire1__Project__c/recordTypes/ECS.recordType-meta.xml
<RecordType>
    <fullName>ECS</fullName>
    <active>true</active>
    <label>ECS</label>
</RecordType>

force-app/main/default/objects/inspire1__Project__c/recordTypes/SCS_Standard.recordType-meta.xml
<RecordType>
    <fullName>SCS_Standard</fullName>
    <active>true</active>
    <description>RT for SCS Standard Records</description>
    <label>SCS Standard</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Engagement_Type__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Type__c</fullName>
    <label>Engagement Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Program_List__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Engagement_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/fileforcem1__Sharepoint_Folder_Id__c.field-meta.xml
<CustomField>
    <fullName>fileforcem1__Sharepoint_Folder_Id__c</fullName>
    <description>Field that holds SharePoint&apos;s folder Id.</description>
    <inlineHelpText>Field that holds SharePoint&apos;s folder Id.</inlineHelpText>
    <label>SharePoint Folder Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Programc__c.field-meta.xml
<CustomField>
    <fullName>Programc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>The selected program is deprecated, please select another program</errorMessage>
        <filterItems>
            <field>Program__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Deprecated</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Opportunity with or without products
Total Opportunity Amount</description>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Bundle_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Bundle_Opportunity</fullName>
    <active>true</active>
    <businessProcess>SCS Global Services Sales Process</businessProcess>
    <label>Bundle Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/ECS.recordType-meta.xml
<RecordType>
    <fullName>ECS</fullName>
    <active>true</active>
    <businessProcess>SCS Global Services Sales Process</businessProcess>
    <label>ECS</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/SCS_Standard.recordType-meta.xml
<RecordType>
    <fullName>SCS_Standard</fullName>
    <active>true</active>
    <businessProcess>SCS Standard Sales Process</businessProcess>
    <label>SCS Standard</label>
</RecordType>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Standard__c/Standard__c.object-meta.xml
<CustomObject>
    <label>Standard</label>
    <nameField>
        <label>Standard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standards</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Standard__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Standards</relationshipLabel>
    <relationshipName>Standards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Engagement_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1st Surveillance</fullName>
    </customValue>
    <customValue>
        <fullName>2nd Surveillance</fullName>
    </customValue>
    <customValue>
        <fullName>3rd Party Verification</fullName>
    </customValue>
    <customValue>
        <fullName>3rd Surveillance</fullName>
    </customValue>
    <customValue>
        <fullName>4th Surveillance</fullName>
    </customValue>
    <customValue>
        <fullName>ACDR only</fullName>
    </customValue>
    <customValue>
        <fullName>Action Plan Review</fullName>
    </customValue>
    <customValue>
        <fullName>AIM Initial</fullName>
    </customValue>
    <customValue>
        <fullName>AIM Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <customValue>
        <fullName>Annual Surveillance</fullName>
    </customValue>
    <customValue>
        <fullName>CAP</fullName>
    </customValue>
    <customValue>
        <fullName>Certification</fullName>
    </customValue>
    <customValue>
        <fullName>Closure of Findings</fullName>
    </customValue>
    <customValue>
        <fullName>Complaint Resolution</fullName>
    </customValue>
    <customValue>
        <fullName>Conformance Surveillance</fullName>
    </customValue>
    <customValue>
        <fullName>Consulting</fullName>
    </customValue>
    <customValue>
        <fullName>Due Diligence</fullName>
    </customValue>
    <customValue>
        <fullName>Each Additional</fullName>
    </customValue>
    <customValue>
        <fullName>Evaluation</fullName>
    </customValue>
    <customValue>
        <fullName>Expansion of Scope</fullName>
    </customValue>
    <customValue>
        <fullName>Expedited Audit</fullName>
    </customValue>
    <customValue>
        <fullName>Extension</fullName>
    </customValue>
    <customValue>
        <fullName>Field Assessment</fullName>
    </customValue>
    <customValue>
        <fullName>FIP Services</fullName>
    </customValue>
    <customValue>
        <fullName>Follow-up</fullName>
    </customValue>
    <customValue>
        <fullName>FSA Farm Management Group Claims</fullName>
    </customValue>
    <customValue>
        <fullName>FSA Option 1</fullName>
    </customValue>
    <customValue>
        <fullName>FSA Option 2</fullName>
    </customValue>
    <customValue>
        <fullName>FSA Option 3</fullName>
    </customValue>
    <customValue>
        <fullName>Initial</fullName>
        <default>true</default>
        <label>Initial</label>
    </customValue>
    <masterLabel>Engagement Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SCS_ProjectTrigger_Test.cls
@isTest
public class SCS_ProjectTrigger_Test {
    @testSetup 
    static void setup() {
        Id accRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Customer').getRecordTypeId();
        Id oppRTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('ECS').getRecordTypeId();
        Id oppSCSStandrdRTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('SCS_Standard').getRecordTypeId();
        Id goalRTId = Schema.SObjectType.Goal__c.getRecordTypeInfosByDeveloperName().get('Program_Goal').getRecordTypeId();
        Id bundelOppRTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Bundle_Opportunity').getRecordTypeId();
        System.runAs( SCS_TestDataFactory.getWebIntegratorUser()){
            List<Account> accountList = SCS_TestDataFactory.createAccounts(accRTId,1);
            accountList[0].BillingCountry= 'United States';
            insert accountList;
            
            List<Program__c> proList = SCS_TestDataFactory.createPrograms(2);
            proList[0].name = 'SQF';
            proList[1].name = 'IRMA';
            insert proList; 
            //Create standard...
            List<Standard__c> standards = SCS_TestDataFactory.createStandard(proList[0].Id,1);
            insert standards;
            List<Campaign> campaign = SCS_TestDataFactory.createCampaing(1);
            insert campaign;
            List<Opportunity> oppList = SCS_TestDataFactory.createOpportunity('Enquiry',accountList[0].Id,proList[0].Id,oppRTId ,Date.newInstance(2025,1,5),11);
            oppList[0].Type = 'New Business';
            oppList[0].TotalAmount__c = 1000;
            oppList[0].CampaignId  = campaign[0].Id;
            oppList[1].Type = 'New Business';
            oppList[1].TotalAmount__c = 1000;
            oppList[1].CampaignId = campaign[0].Id;
            oppList[2].Type = 'New Business';
            oppList[2].TotalAmount__c = 1000;
            oppList[2].CampaignId = campaign[0].Id;
            oppList[3].Type = 'Existing Business';
            oppList[3].TotalAmount__c = 1000;
            oppList[3].CampaignId = campaign[0].Id;
            oppList[4].Type = 'Existing Business';
            oppList[4].TotalAmount__c = 1000;
            oppList[4].CampaignId = campaign[0].Id;
            oppList[5].Type = 'Existing Business';
            oppList[5].TotalAmount__c = 1000;
            oppList[5].CampaignId = campaign[0].Id;
            oppList[6].Type = 'New Business';
            oppList[6].TotalAmount__c = 1000;
            oppList[6].CampaignId = campaign[0].Id;
            oppList[6].RecordTypeId = oppSCSStandrdRTId;
            oppList[6].NextStep ='BUNDLE';
            oppList[6].Programc__c = proList[0].Id;
            oppList[6].Engagement_Type__c ='Initial';
            oppList[7].Type = 'New Business';
            oppList[7].TotalAmount__c = 1000;
            oppList[7].RecordTypeId = bundelOppRTId;
            oppList[7].CampaignId = campaign[0].Id;
            oppList[7].NextStep ='BUNDLE';
            oppList[8].TotalAmount__c = 1000;
            oppList[8].Type = 'Existing Business';
            oppList[8].CampaignId = campaign[0].Id;
            oppList[9].TotalAmount__c = 1000;
            oppList[9].Type = 'Existing Business';
            oppList[9].StageName = 'Closed Won';
            oppList[9].CampaignId = campaign[0].Id;
            oppList[10].TotalAmount__c = 1000;
            oppList[10].Type = 'Existing Business';
            oppList[10].StageName = 'Closed Lost';
            oppList[10].CampaignId = campaign[0].Id;
            insert oppList;
            List<Goal__c> goalList = SCS_TestDataFactory.createGoalRecord(goalRTId,proList[1].id,'Q1','2025',1);  
            insert goalList;
            
             //Create Project...
            List<inspire1__Project__c> projects = SCS_TestDataFactory.createProject(accountList[0].Id, oppList[0].Id, 1);
            insert projects;
        }
        
    }
    
    
    
    @isTest 
    static void testOpportunitysFiles() {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorClass());
        System.runAs(SCS_TestDataFactory.getWebIntegratorUser()){
            Set<Id> accIdSet = new Set<Id>();
            Set<Id> opptyIdSet = new Set<Id>();
            Set<Id> prjIdSet = new Set<Id>();
            List<Account> accList =[SELECT Id, Name FROM Account];
            List<Opportunity> recordList =[SELECT Id,Name,StageName,Type FROM Opportunity];
            List<Opportunity> opptyList = new List<Opportunity>();
            
            for(Account acc : accList){
                accIdSet.add(acc.Id);
            }
            
            for(Opportunity opp : recordList){
                opp.fileforcem1__Sharepoint_Folder_Id__c = '13221314213123123';
                opptyIdSet.add(opp.Id);
                opptyList.add(opp);
            }
            update opptyList;
            List<inspire1__Project__c> projects = [SELECT Id, Name FROM inspire1__Project__c];
            for(inspire1__Project__c prj : projects){
                prjIdSet.add(prj.Id);
            }
            System.assertEquals(11,recordList.size(),'External Record should not be blank');
            
            sFilesCallout.createFoldersonSharePoint(opptyIdSet);
            sFilesCallout.createFoldersonSharePointForProject(prjIdSet);
            delete projects;
        }
        Test.stopTest();  
    }
    
}