force-app/main/default/objects/Account/fields/AllOCSCSharePointFolderId__c.field-meta.xml
<CustomField>
    <fullName>AllOCSCSharePointFolderId__c</fullName>
    <label>AllOCSCSharePointFolderId</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/AllOCSGSSharePointFolderId__c.field-meta.xml
<CustomField>
    <fullName>AllOCSGSSharePointFolderId__c</fullName>
    <label>AllOCSGSSharePointFolderId</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/AllOCSSSharePointFolderId__c.field-meta.xml
<CustomField>
    <fullName>AllOCSSSharePointFolderId__c</fullName>
    <label>AllOCSSSharePointFolderId</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <defaultValue>&apos;Net 30&apos;</defaultValue>
    <inlineHelpText>If you are changing the value to Net 45 or Net 60 then make sure to click on &quot;Submit for approval&quot; from the top right corner dropdown. The value will be changed only post approval of the Accounting team.</inlineHelpText>
    <label>Payment Terms</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SC_SharePoint_Folder_Id__c.field-meta.xml
<CustomField>
    <fullName>SC_SharePoint_Folder_Id__c</fullName>
    <label>SC SharePoint Folder Id</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/SharePoint_Folder_Id__c.field-meta.xml
<CustomField>
    <fullName>SharePoint_Folder_Id__c</fullName>
    <label>SGS SharePoint Folder Id</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/SS_SharePoint_Folder_Id__c.field-meta.xml
<CustomField>
    <fullName>SS_SharePoint_Folder_Id__c</fullName>
    <label>SS SharePoint Folder Id</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>SCS Global Services departments</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Certificate__c/Certificate__c.object-meta.xml
<CustomObject>
    <description>Certificate issued to Client</description>
    <label>Certificate</label>
    <nameField>
        <displayFormat>CRT-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certificates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certificate__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Certificates</relationshipLabel>
    <relationshipName>Certificates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Certificate__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Certificates</relationshipLabel>
    <relationshipName>Certificates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/inspire1__Project__c/inspire1__Project__c.object-meta.xml
<CustomObject>
    <description>Inspire Planner - This object captures the detail of the project record</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/inspire1__Project__c/fields/SharePoint_Folder_Id__c.field-meta.xml
<CustomField>
    <fullName>SharePoint_Folder_Id__c</fullName>
    <description>Field that holds SharePoint&apos;s folder Id.</description>
    <label>SharePoint Folder Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/inspire1__Project__c/recordTypes/ECS.recordType-meta.xml
<RecordType>
    <fullName>ECS</fullName>
    <active>true</active>
    <label>ECS</label>
</RecordType>

force-app/main/default/objects/inspire1__Project__c/recordTypes/SCS_Consulting.recordType-meta.xml
<RecordType>
    <fullName>SCS_Consulting</fullName>
    <active>true</active>
    <label>SCS Consulting</label>
</RecordType>

force-app/main/default/objects/inspire1__Project__c/recordTypes/SCS_Standard.recordType-meta.xml
<RecordType>
    <fullName>SCS_Standard</fullName>
    <active>true</active>
    <description>RT for SCS Standard Records</description>
    <label>SCS Standard</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Salesforce Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Entity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IsConverted__c.field-meta.xml
<CustomField>
    <fullName>IsConverted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsConverted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Programc__c.field-meta.xml
<CustomField>
    <fullName>Programc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>The selected program is deprecated, please select another program</errorMessage>
        <filterItems>
            <field>Program__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Deprecated</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Opportunity with or without products
Total Opportunity Amount</description>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/ECS.recordType-meta.xml
<RecordType>
    <fullName>ECS</fullName>
    <active>true</active>
    <businessProcess>SCS Global Services Sales Process</businessProcess>
    <label>ECS</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/SCS_Consulting.recordType-meta.xml
<RecordType>
    <fullName>SCS_Consulting</fullName>
    <active>true</active>
    <businessProcess>SCS Standard Sales Process</businessProcess>
    <label>SCS Consulting</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/SCS_Standard.recordType-meta.xml
<RecordType>
    <fullName>SCS_Standard</fullName>
    <active>true</active>
    <businessProcess>SCS Standard Sales Process</businessProcess>
    <label>SCS Standard</label>
</RecordType>

force-app/main/default/objects/Opportunity_Certificate__c/Opportunity_Certificate__c.object-meta.xml
<CustomObject>
    <label>Opportunity Certificate</label>
    <nameField>
        <displayFormat>OC-{0000}</displayFormat>
        <label>Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Certificates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Certificate__c/fields/Certificate__c.field-meta.xml
<CustomField>
    <fullName>Certificate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Certificate</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Certificate__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Certificate__c</referenceTo>
    <relationshipLabel>Opportunity Certificates</relationshipLabel>
    <relationshipName>Opportunity_Certificates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Certificate__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Certificates</relationshipLabel>
    <relationshipName>Opportunity_Certificates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Certificate__c/fields/SharePoint_Folder_Id__c.field-meta.xml
<CustomField>
    <fullName>SharePoint_Folder_Id__c</fullName>
    <label>SharePoint Folder Id</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Entity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Entity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ECS</fullName>
    </customValue>
    <customValue>
        <fullName>Food and Agriculture</fullName>
    </customValue>
    <customValue>
        <fullName>Natural Resources</fullName>
    </customValue>
    <customValue>
        <fullName>SCS Consulting</fullName>
    </customValue>
    <customValue>
        <fullName>SCS Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Research and Development</fullName>
    </customValue>
    <customValue>
        <fullName>Advanced Technical Programs</fullName>
    </customValue>
    <masterLabel>Entity</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/sfilesBatchOCFolderTest.cls
/************************************************************************************************************************************************
Apex Class Name : sfilesBatchOCFolderTest
Version         : 1.0
Created Date    : 
Function        : This test class is used to cover the 'sfilesBatchOCFolder' apex class.
Modification Log:
-------------------------------------------------------------------------------------------------------------------------------------------------
* Developer                                 Date                                Description
* -----------------------------------------------------------------------------------------------------------------------------------------------
Sohit Tripathi                        	10/07/2023                            Initial version
**************************************************************************************************************************************************/
@isTest
public class sfilesBatchOCFolderTest {
    
    @testSetup 
    static void setup() {
        Id accRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Customer').getRecordTypeId();
        Id oppRTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('ECS').getRecordTypeId();
        Id oppSCSStandrdRTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('SCS_Standard').getRecordTypeId();
        Id consOpRTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('SCS_Consulting').getRecordTypeId();
        Id prjRTId = Schema.SObjectType.inspire1__Project__c.getRecordTypeInfosByDeveloperName().get('ECS').getRecordTypeId();
        Id prjStandardRTId = Schema.SObjectType.inspire1__Project__c.getRecordTypeInfosByDeveloperName().get('SCS_Standard').getRecordTypeId();
        Id prjConsultingRTId = Schema.SObjectType.inspire1__Project__c.getRecordTypeInfosByDeveloperName().get('SCS_Consulting').getRecordTypeId();
        System.runAs( SCS_TestDataFactory.getWebIntegratorUser()){
            List<Account> accountList = SCS_TestDataFactory.createAccounts(accRTId,2);
            accountList[0].BillingCountry= 'United States';
            accountList[0].Payment_Terms__c = 'Net 30';
            accountList[0].SharePoint_Folder_Id__c = 'DFDV345533234324234';
            accountList[0].AllOCSGSSharePointFolderId__c = 'JHM7876867888GH';
            accountList[0].SS_SharePoint_Folder_Id__c = 'JHM7876867888GH';
            accountList[0].AllOCSSSharePointFolderId__c = 'JHM7876867888GH';
            accountList[0].SC_SharePoint_Folder_Id__c = 'JHM7876867888GH';
            accountList[0].AllOCSCSharePointFolderId__c = 'JHM7876867888GH';
            insert accountList;
            
            List<Program__c> proList = SCS_TestDataFactory.createPrograms(3);
            proList[0].name = 'SQF';
            proList[0].Entity__c = 'ECS';
            proList[1].name = 'Materiality Assessments';
            proList[1].Entity__c = 'SCS Consulting';
            proList[2].name = 'RSB';
            proList[2].Entity__c = 'SCS Standard';
            insert proList; 
            
            List<Campaign> campaign = SCS_TestDataFactory.createCampaing(1);
            insert campaign;
            
            List<Opportunity> oppList = SCS_TestDataFactory.createOpportunity('Enquiry', accountList[0].Id, proList[0].Id, oppRTId ,Date.newInstance(2025,1,5), 3);
            oppList[0].Type = 'New Business';
            oppList[0].TotalAmount__c = 1000;
            oppList[0].CampaignId  = campaign[0].Id;
            oppList[0].IsConverted__c = True;
            oppList[1].Type = 'New Business';
            oppList[1].TotalAmount__c = 1000;
            oppList[1].CampaignId  = campaign[0].Id;
            oppList[1].IsConverted__c = True;
            oppList[1].RecordTypeId = oppSCSStandrdRTId;
            oppList[1].Programc__c = proList[2].Id;
            oppList[2].Type = 'New Business';
            oppList[2].TotalAmount__c = 1000;
            oppList[2].CampaignId  = campaign[0].Id;
            oppList[2].IsConverted__c = True;
            oppList[2].RecordTypeId = consOpRTId;
            oppList[2].Programc__c = proList[1].Id;
            insert oppList;
            
            List<Certificate__c> certList =new List<Certificate__c>();
            List<Opportunity_certificate__c> opcerlist = new List<Opportunity_certificate__c>();
            certList = SCS_TestDataFactory.createCertificate(1);
            insert certList;
            
            opcerlist = SCS_TestDataFactory.createOppsCertificate(certList[0], oppList);
            insert opcerlist;
        }
    }
    
    @isTest 
    static void testOpptySCSGlobalServices() {
        Test.startTest();
        System.runAs(SCS_TestDataFactory.getWebIntegratorUser()){
            List<Opportunity_certificate__c> ocList = [SELECT Id FROM Opportunity_certificate__c WHERE Opportunity__r.RecordType.DeveloperName = 'ECS'];
            sfilesBatchOCFolder batch = new sfilesBatchOCFolder();
            Database.executeBatch(batch);
        }
        Test.stopTest();
    }
    
    @isTest 
    static void testOpptySCSStandard() {
        Test.startTest();
        System.runAs(SCS_TestDataFactory.getWebIntegratorUser()){
            List<Opportunity_certificate__c> ocList = [SELECT Id FROM Opportunity_certificate__c WHERE Opportunity__r.RecordType.DeveloperName = 'SCS_Standard'];
            sfilesBatchOCFolder batch = new sfilesBatchOCFolder();
            Database.executeBatch(batch);
        }
        Test.stopTest();
    }
    
    @isTest 
    static void testOpptySCSConsulting() {
        Test.startTest();
        System.runAs(SCS_TestDataFactory.getWebIntegratorUser()){
            List<Opportunity_certificate__c> ocList = [SELECT Id FROM Opportunity_certificate__c WHERE Opportunity__r.RecordType.DeveloperName = 'SCS_Consulting'];
            sfilesBatchOCFolder batch = new sfilesBatchOCFolder();
            Database.executeBatch(batch);
        }
        Test.stopTest();
    }
}