force-app/main/default/objects/Account/fields/AllProjectSCSharePointFolderId__c.field-meta.xml
<CustomField>
    <fullName>AllProjectSCSharePointFolderId__c</fullName>
    <label>AllProjectSCSharePointFolderId</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/AllProjectSGSSharePointFolderId__c.field-meta.xml
<CustomField>
    <fullName>AllProjectSGSSharePointFolderId__c</fullName>
    <label>AllProjectSGSSharePointFolderId</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/AllProjectSSSharePointFolderId__c.field-meta.xml
<CustomField>
    <fullName>AllProjectSSSharePointFolderId__c</fullName>
    <label>AllProjectSSSharePointFolderId</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <defaultValue>&apos;Net 30&apos;</defaultValue>
    <inlineHelpText>If you are changing the value to Net 45 or Net 60 then make sure to click on &quot;Submit for approval&quot; from the top right corner dropdown. The value will be changed only post approval of the Accounting team.</inlineHelpText>
    <label>Payment Terms</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SC_SharePoint_Folder_Id__c.field-meta.xml
<CustomField>
    <fullName>SC_SharePoint_Folder_Id__c</fullName>
    <label>SC SharePoint Folder Id</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/SharePoint_Folder_Id__c.field-meta.xml
<CustomField>
    <fullName>SharePoint_Folder_Id__c</fullName>
    <label>SGS SharePoint Folder Id</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/SS_SharePoint_Folder_Id__c.field-meta.xml
<CustomField>
    <fullName>SS_SharePoint_Folder_Id__c</fullName>
    <label>SS SharePoint Folder Id</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>SCS Global Services departments</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Certificate__c/Certificate__c.object-meta.xml
<CustomObject>
    <description>Certificate issued to Client</description>
    <label>Certificate</label>
    <nameField>
        <displayFormat>CRT-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certificates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certificate__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Certificates</relationshipLabel>
    <relationshipName>Certificates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Certificate__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Certificates</relationshipLabel>
    <relationshipName>Certificates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/inspire1__Project__c/inspire1__Project__c.object-meta.xml
<CustomObject>
    <description>Inspire Planner - This object captures the detail of the project record</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/inspire1__Project__c/fields/inspire1__Account__c.field-meta.xml
<CustomField>
    <fullName>inspire1__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account the project is related to.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/inspire1__Project__c/fields/inspire1__Opportunity1__c.field-meta.xml
<CustomField>
    <fullName>inspire1__Opportunity1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity related to Project.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/inspire1__Project__c/fields/SharePoint_Folder_Id__c.field-meta.xml
<CustomField>
    <fullName>SharePoint_Folder_Id__c</fullName>
    <description>Field that holds SharePoint&apos;s folder Id.</description>
    <label>SharePoint Folder Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/inspire1__Project__c/recordTypes/ECS.recordType-meta.xml
<RecordType>
    <fullName>ECS</fullName>
    <active>true</active>
    <label>ECS</label>
</RecordType>

force-app/main/default/objects/inspire1__Project__c/recordTypes/SCS_Consulting.recordType-meta.xml
<RecordType>
    <fullName>SCS_Consulting</fullName>
    <active>true</active>
    <label>SCS Consulting</label>
</RecordType>

force-app/main/default/objects/inspire1__Project__c/recordTypes/SCS_Standard.recordType-meta.xml
<RecordType>
    <fullName>SCS_Standard</fullName>
    <active>true</active>
    <description>RT for SCS Standard Records</description>
    <label>SCS Standard</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Salesforce Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Entity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/fileforcem1__Sharepoint_Folder_Id__c.field-meta.xml
<CustomField>
    <fullName>fileforcem1__Sharepoint_Folder_Id__c</fullName>
    <description>Field that holds SharePoint&apos;s folder Id.</description>
    <inlineHelpText>Field that holds SharePoint&apos;s folder Id.</inlineHelpText>
    <label>SharePoint Folder Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IsConverted__c.field-meta.xml
<CustomField>
    <fullName>IsConverted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsConverted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Programc__c.field-meta.xml
<CustomField>
    <fullName>Programc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>The selected program is deprecated, please select another program</errorMessage>
        <filterItems>
            <field>Program__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Deprecated</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Opportunity with or without products
Total Opportunity Amount</description>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/ECS.recordType-meta.xml
<RecordType>
    <fullName>ECS</fullName>
    <active>true</active>
    <businessProcess>SCS Global Services Sales Process</businessProcess>
    <label>ECS</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/SCS_Consulting.recordType-meta.xml
<RecordType>
    <fullName>SCS_Consulting</fullName>
    <active>true</active>
    <businessProcess>SCS Standard Sales Process</businessProcess>
    <label>SCS Consulting</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/SCS_Standard.recordType-meta.xml
<RecordType>
    <fullName>SCS_Standard</fullName>
    <active>true</active>
    <businessProcess>SCS Standard Sales Process</businessProcess>
    <label>SCS Standard</label>
</RecordType>

force-app/main/default/objects/Opportunity_Certificate__c/Opportunity_Certificate__c.object-meta.xml
<CustomObject>
    <label>Opportunity Certificate</label>
    <nameField>
        <displayFormat>OC-{0000}</displayFormat>
        <label>Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Certificates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Certificate__c/fields/Certificate__c.field-meta.xml
<CustomField>
    <fullName>Certificate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Certificate</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Certificate__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Certificate__c</referenceTo>
    <relationshipLabel>Opportunity Certificates</relationshipLabel>
    <relationshipName>Opportunity_Certificates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Certificate__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Certificates</relationshipLabel>
    <relationshipName>Opportunity_Certificates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Certificate__c/fields/SharePoint_Folder_Id__c.field-meta.xml
<CustomField>
    <fullName>SharePoint_Folder_Id__c</fullName>
    <label>SharePoint Folder Id</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Entity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Entity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ECS</fullName>
    </customValue>
    <customValue>
        <fullName>Food and Agriculture</fullName>
    </customValue>
    <customValue>
        <fullName>Natural Resources</fullName>
    </customValue>
    <customValue>
        <fullName>SCS Consulting</fullName>
    </customValue>
    <customValue>
        <fullName>SCS Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Research and Development</fullName>
    </customValue>
    <customValue>
        <fullName>Advanced Technical Programs</fullName>
    </customValue>
    <masterLabel>Entity</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/sFilesCalloutTest.cls
/************************************************************************************************************************************************
Apex Class Name : sFilesCalloutTest
Version         : 1.0
Created Date    : 
Function        : This test class is used to cover the 'sFilesCallout' and 'sfilesOpportunityFolderQueable' apex class.
Modification Log:
-------------------------------------------------------------------------------------------------------------------------------------------------
* Developer                                 Date                                Description
* -----------------------------------------------------------------------------------------------------------------------------------------------
Sohit Tripathi                        	21/10/2022                            Initial version
**************************************************************************************************************************************************/
@isTest
public class sFilesCalloutTest {
    @testSetup 
    static void setup() {
        Id accRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Customer').getRecordTypeId();
        Id oppRTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('ECS').getRecordTypeId();
        Id oppSCSStandrdRTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('SCS_Standard').getRecordTypeId();
        Id consOpRTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('SCS_Consulting').getRecordTypeId();
        Id prjRTId = Schema.SObjectType.inspire1__Project__c.getRecordTypeInfosByDeveloperName().get('ECS').getRecordTypeId();
        Id prjStandardRTId = Schema.SObjectType.inspire1__Project__c.getRecordTypeInfosByDeveloperName().get('SCS_Standard').getRecordTypeId();
        Id prjConsultingRTId = Schema.SObjectType.inspire1__Project__c.getRecordTypeInfosByDeveloperName().get('SCS_Consulting').getRecordTypeId();
        System.runAs( SCS_TestDataFactory.getWebIntegratorUser()){
            List<Account> accountList = SCS_TestDataFactory.createAccounts(accRTId,2);
            accountList[0].BillingCountry= 'United States';
            accountList[0].Payment_Terms__c = 'Net 30';
            accountList[1].BillingCountry= 'United States';
            accountList[1].Payment_Terms__c = 'Net 30';
            insert accountList;
            
            List<Program__c> proList = SCS_TestDataFactory.createPrograms(3);
            proList[0].name = 'SQF';
            proList[0].Entity__c = 'ECS';
            proList[1].name = 'Materiality Assessments';
            proList[1].Entity__c = 'SCS Consulting';
            proList[2].name = 'RSB';
            proList[2].Entity__c = 'SCS Standard';
            insert proList; 

            List<Campaign> campaign = SCS_TestDataFactory.createCampaing(1);
            insert campaign;
            
            List<Opportunity> oppList = SCS_TestDataFactory.createOpportunity('Enquiry', accountList[0].Id, proList[0].Id, oppRTId ,Date.newInstance(2025,1,5), 6);
            oppList[0].Type = 'New Business';
            oppList[0].TotalAmount__c = 1000;
            oppList[0].CampaignId  = campaign[0].Id;
            oppList[0].IsConverted__c = True;
            oppList[1].Type = 'New Business';
            oppList[1].TotalAmount__c = 1000;
            oppList[1].CampaignId  = campaign[0].Id;
            oppList[1].IsConverted__c = True;
            oppList[1].RecordTypeId = oppSCSStandrdRTId;
            oppList[1].Programc__c = proList[2].Id;
            oppList[2].Type = 'New Business';
            oppList[2].TotalAmount__c = 1000;
            oppList[2].CampaignId  = campaign[0].Id;
            oppList[2].IsConverted__c = True;
            oppList[2].RecordTypeId = consOpRTId;
            oppList[2].Programc__c = proList[1].Id;
            oppList[3].Type = 'New Business';
            oppList[3].TotalAmount__c = 1000;
            oppList[3].CampaignId  = campaign[0].Id;
            oppList[3].IsConverted__c = True;
            oppList[4].Type = 'New Business';
            oppList[4].TotalAmount__c = 1000;
            oppList[4].CampaignId  = campaign[0].Id;
            oppList[4].IsConverted__c = True;
            oppList[4].RecordTypeId = oppSCSStandrdRTId;
            oppList[4].Programc__c = proList[2].Id;
            oppList[5].Type = 'New Business';
            oppList[5].TotalAmount__c = 1000;
            oppList[5].CampaignId  = campaign[0].Id;
            oppList[5].IsConverted__c = True;
            oppList[5].RecordTypeId = consOpRTId;
            oppList[5].Programc__c = proList[1].Id;
            insert oppList;
            
            //Create Project...
            List<inspire1__Project__c> projects = SCS_TestDataFactory.createProject(accountList[0].Id, oppList[0].Id, 9);
            projects[0].RecordTypeId = prjRTId;
            projects[1].inspire1__Opportunity1__c = null;
            projects[1].RecordTypeId = prjRTId;
            projects[2].inspire1__Opportunity1__c = null;
            projects[2].inspire1__Account__c = null;
            projects[2].RecordTypeId = prjRTId;
            projects[3].RecordTypeId = prjStandardRTId;
            projects[3].inspire1__Opportunity1__c = oppList[1].Id;
            projects[4].RecordTypeId = prjConsultingRTId;
            projects[4].inspire1__Opportunity1__c = oppList[2].Id;
            projects[5].RecordTypeId = prjConsultingRTId;
            projects[5].inspire1__Opportunity1__c = null;
            projects[6].RecordTypeId = prjStandardRTId;
            projects[6].inspire1__Opportunity1__c = null;
            projects[7].inspire1__Opportunity1__c = null;
            projects[7].inspire1__Account__c = null;
            projects[7].RecordTypeId = prjStandardRTId;
            projects[8].inspire1__Opportunity1__c = null;
            projects[8].inspire1__Account__c = null;
            projects[8].RecordTypeId = prjConsultingRTId;
            insert projects;
            
            List<Certificate__c> certList =new List<Certificate__c>();
    		List<Opportunity_certificate__c> opcerlist = new List<Opportunity_certificate__c>();
            certList = SCS_TestDataFactory.createCertificate(1);
        	insert certList;
        
        	opcerlist = SCS_TestDataFactory.createOppsCertificate(certList[0], oppList);
        	insert opcerlist;
        }
    }
    
    @isTest 
    static void testOpptySCSGlobalServices() {
        Test.startTest();
        System.runAs(SCS_TestDataFactory.getWebIntegratorUser()){
            //Set mock response...
            Test.setMock(HttpCalloutMock.class, new SCS_sFilesMock()); 
            List<Opportunity> oppList = [Select id, type,totalamount__c,fileforcem1__Sharepoint_Folder_Id__c from Opportunity WHERE RecordType.DeveloperName = 'ECS'];
            Set<Id> opptyIdSet = new Set<Id>();

            for(Opportunity opp : oppList){
                opptyIdSet.add(opp.Id);
            }
            sFilesCallout.createFoldersonSharePoint(opptyIdSet);
            
            List<Opportunity_certificate__c> ocList = [SELECT Id FROM Opportunity_certificate__c WHERE Opportunity__r.RecordType.DeveloperName = 'ECS'];
            Set<Id> ocIdSet = new Set<Id>();

            for(Opportunity_certificate__c oc : ocList){
                ocIdSet.add(oc.Id);
            }
            sFilesCallout.createFoldersonSharePointForOpptyCertificate(ocIdSet);
        }
        Test.stopTest();
    }
    
    @isTest 
    static void testOpptySCSStandard() {
        Test.startTest();
        System.runAs(SCS_TestDataFactory.getWebIntegratorUser()){
            //Set mock response...
            Test.setMock(HttpCalloutMock.class, new SCS_sFilesMock()); 
            List<Opportunity> oppList = [Select id, type,totalamount__c,fileforcem1__Sharepoint_Folder_Id__c from Opportunity WHERE RecordType.DeveloperName = 'SCS_Standard'];
            Set<Id> opptyIdSet = new Set<Id>();

            for(Opportunity opp : oppList){
                opptyIdSet.add(opp.Id);
            }
            sFilesCallout.createFoldersonSharePoint(opptyIdSet);
            
            List<Opportunity_certificate__c> ocList = [SELECT Id FROM Opportunity_certificate__c WHERE Opportunity__r.RecordType.DeveloperName = 'SCS_Standard'];
            Set<Id> ocIdSet = new Set<Id>();

            for(Opportunity_certificate__c oc : ocList){
                ocIdSet.add(oc.Id);
            }
            sFilesCallout.createFoldersonSharePointForOpptyCertificate(ocIdSet);
        }
        Test.stopTest();
    }
    
    @isTest 
    static void testOpptySCSConsulting() {
        Test.startTest();
        System.runAs(SCS_TestDataFactory.getWebIntegratorUser()){
            //Set mock response...
            Test.setMock(HttpCalloutMock.class, new SCS_sFilesMock()); 
            List<Opportunity> oppList = [Select id, type,totalamount__c,fileforcem1__Sharepoint_Folder_Id__c from Opportunity WHERE RecordType.DeveloperName = 'SCS_Consulting'];
            Set<Id> opptyIdSet = new Set<Id>();

            for(Opportunity opp : oppList){
                opptyIdSet.add(opp.Id);
            }
            sFilesCallout.createFoldersonSharePoint(opptyIdSet);
            
            List<Opportunity_certificate__c> ocList = [SELECT Id FROM Opportunity_certificate__c WHERE Opportunity__r.RecordType.DeveloperName = 'SCS_Consulting'];
            Set<Id> ocIdSet = new Set<Id>();

            for(Opportunity_certificate__c oc : ocList){
                ocIdSet.add(oc.Id);
            }
            sFilesCallout.createFoldersonSharePointForOpptyCertificate(ocIdSet);
        }
        Test.stopTest();
    }
    
    @isTest 
    static void testProjectSCSGlobalServices() {
        Test.startTest();
        System.runAs(SCS_TestDataFactory.getWebIntegratorUser()){
            //Set mock response...
            Test.setMock(HttpCalloutMock.class, new SCS_sFilesMock()); 
            Set<Id> opptyIdSet = new Set<Id>();
            Set<Id> prjIdSet = new Set<Id>();
            List<Opportunity> opptyList = new List<Opportunity>();
            List<Account> acctList = new List<Account>();

            List<Account> accList = [Select Id, SharePoint_Folder_Id__c, AllProjectSGSSharePointFolderId__c, SS_SharePoint_Folder_Id__c, AllProjectSSSharePointFolderId__c, SC_SharePoint_Folder_Id__c, AllProjectSCSharePointFolderId__c FROM Account];
            for(Account acc: accList){
                acc.SharePoint_Folder_Id__c = 'DFDV345533234324234';
                acc.AllProjectSGSSharePointFolderId__c = 'JHM7876867888GH';
                acctList.add(acc);
            }
            update acctList;
            
            List<Opportunity> oppList = [Select id, type,totalamount__c,fileforcem1__Sharepoint_Folder_Id__c from Opportunity WHERE RecordType.DeveloperName = 'ECS'];
            
            List<inspire1__Project__c> projects = [SELECT Id, Name, inspire1__Opportunity1__r.Account.SharePoint_Folder_Id__c, inspire1__Opportunity1__r.Account.AllProjectSGSSharePointFolderId__c FROM inspire1__Project__c WHERE inspire1__Opportunity1__c != null AND RecordType.DeveloperName = 'ECS' AND inspire1__Opportunity1__r.RecordType.DeveloperName='ECS' AND inspire1__Opportunity1__r.Account.SharePoint_Folder_Id__c != null];
            for(inspire1__Project__c prj : projects){
                prjIdSet.add(prj.Id);
            }
            
            sFilesCallout.createFoldersonSharePoint(opptyIdSet);
            sFilesCallout.createFoldersonSharePointForProject(prjIdSet);
        }
        Test.stopTest();  
    }  
    
    @isTest 
    static void testProjectSCSStandard() {
        Test.startTest();
        System.runAs(SCS_TestDataFactory.getWebIntegratorUser()){
            //Set mock response...
            Test.setMock(HttpCalloutMock.class, new SCS_sFilesMock()); 
            Set<Id> opptyIdSet = new Set<Id>();
            Set<Id> prjIdSet = new Set<Id>();
            List<Opportunity> opptyList = new List<Opportunity>();
            List<Account> acctList = new List<Account>();
            
            List<Account> accList = [Select Id, SharePoint_Folder_Id__c, AllProjectSGSSharePointFolderId__c, SS_SharePoint_Folder_Id__c, AllProjectSSSharePointFolderId__c, SC_SharePoint_Folder_Id__c, AllProjectSCSharePointFolderId__c FROM Account];
            for(Account acc: accList){
                acc.SS_SharePoint_Folder_Id__c = 'JHM7876867888GH';
                acc.AllProjectSSSharePointFolderId__c = 'JHM7876867888GH';
                acctList.add(acc);
            }
            update acctList;
            
            List<Opportunity> oppList = [Select id, type,totalamount__c,fileforcem1__Sharepoint_Folder_Id__c from Opportunity WHERE RecordType.DeveloperName = 'SCS_Standard'];
            
            List<inspire1__Project__c> projects = [SELECT Id, Name FROM inspire1__Project__c WHERE inspire1__Opportunity1__c != null AND RecordType.DeveloperName = 'SCS_Standard' AND inspire1__Opportunity1__r.RecordType.DeveloperName='SCS_Standard'];
            for(inspire1__Project__c prj : projects){
                prjIdSet.add(prj.Id);
            }
            
            sFilesCallout.createFoldersonSharePointForProject(prjIdSet);
        }
        Test.stopTest();  
    }
    
    @isTest 
    static void testProjectSCSConsulting() {
        Test.startTest();
        System.runAs(SCS_TestDataFactory.getWebIntegratorUser()){
            //Set mock response...
            Test.setMock(HttpCalloutMock.class, new SCS_sFilesMock()); 
            Set<Id> opptyIdSet = new Set<Id>();
            Set<Id> prjIdSet = new Set<Id>();
            List<Opportunity> opptyList = new List<Opportunity>();
            List<Account> acctList = new List<Account>();
            
            List<Account> accList = [Select Id, SharePoint_Folder_Id__c, AllProjectSGSSharePointFolderId__c, SS_SharePoint_Folder_Id__c, AllProjectSSSharePointFolderId__c, SC_SharePoint_Folder_Id__c, AllProjectSCSharePointFolderId__c FROM Account];
            for(Account acc: accList){
                acc.SC_SharePoint_Folder_Id__c = 'JHM7876867888GH';
                acc.AllProjectSCSharePointFolderId__c = 'JHM7876867888GH';
                acctList.add(acc);
            }
            update acctList;
            
            List<Opportunity> oppList = [Select id, type,totalamount__c,fileforcem1__Sharepoint_Folder_Id__c from Opportunity WHERE RecordType.DeveloperName = 'SCS_Consulting'];
            
            List<inspire1__Project__c> projects = [SELECT Id, Name FROM inspire1__Project__c WHERE inspire1__Opportunity1__c != null AND RecordType.DeveloperName = 'SCS_Consulting' AND inspire1__Opportunity1__r.RecordType.DeveloperName='SCS_Consulting'];
            for(inspire1__Project__c prj : projects){
                prjIdSet.add(prj.Id);
            }
            
            sFilesCallout.createFoldersonSharePointForProject(prjIdSet);
        }
        Test.stopTest();  
    }
    
    @isTest 
    static void testAccount() {
        Set<Id> prjIdSet = new Set<Id>();
        List<Account> acctList = new List<Account>();

            List<Account> accList = [Select Id, SharePoint_Folder_Id__c, AllProjectSGSSharePointFolderId__c, SS_SharePoint_Folder_Id__c, AllProjectSSSharePointFolderId__c, SC_SharePoint_Folder_Id__c, AllProjectSCSharePointFolderId__c FROM Account];
            for(Account acc: accList){
                acc.SharePoint_Folder_Id__c = 'DFDV345533234324234';
                acc.AllProjectSGSSharePointFolderId__c = 'JHM7876867888GH';
                acctList.add(acc);
            }
            update acctList;
        List<inspire1__Project__c> projects = [SELECT Id, Name FROM inspire1__Project__c WHERE inspire1__Account__c != null AND inspire1__Opportunity1__c = null];
        for(inspire1__Project__c prj : projects){
            prjIdSet.add(prj.Id);
        }
        sFilesCallout.createFoldersonSharePointForProject(prjIdSet);
    }
    
    @isTest 
    static void testAccountStandard() {
        Set<Id> prjIdSet = new Set<Id>();
        List<Account> acctList = new List<Account>();
        
        List<Account> accList = [Select Id, SharePoint_Folder_Id__c, AllProjectSGSSharePointFolderId__c, SS_SharePoint_Folder_Id__c, AllProjectSSSharePointFolderId__c, SC_SharePoint_Folder_Id__c, AllProjectSCSharePointFolderId__c FROM Account];
        for(Account acc: accList){
            acc.SS_SharePoint_Folder_Id__c = 'JHM7876867888GH';
            acc.AllProjectSSSharePointFolderId__c = 'JHM7876867888GH';
            acctList.add(acc);
        }
        update acctList;
        List<inspire1__Project__c> projects = [SELECT Id, Name, inspire1__Account__r.SS_SharePoint_Folder_Id__c, inspire1__Account__r.AllProjectSSSharePointFolderId__c FROM inspire1__Project__c WHERE inspire1__Account__c != null AND inspire1__Opportunity1__c = null AND RecordType.DeveloperName = 'SCS_Standard'];
        System.debug('projects313--'+projects);
        for(inspire1__Project__c prj : projects){
            prjIdSet.add(prj.Id);
        }
        sFilesCallout.createFoldersonSharePointForProject(prjIdSet);
    }
    
    @isTest 
    static void testAccountConsulting() {
        Set<Id> prjIdSet = new Set<Id>();
        List<Account> acctList = new List<Account>();
        
        List<Account> accList = [Select Id, SharePoint_Folder_Id__c, AllProjectSGSSharePointFolderId__c, SS_SharePoint_Folder_Id__c, AllProjectSSSharePointFolderId__c, SC_SharePoint_Folder_Id__c, AllProjectSCSharePointFolderId__c FROM Account];
        for(Account acc: accList){
            acc.SC_SharePoint_Folder_Id__c = 'JHM7876867888GH';
            acc.AllProjectSCSharePointFolderId__c = 'JHM7876867888GH';
            acctList.add(acc);
        }
        update acctList;
        List<inspire1__Project__c> projects = [SELECT Id, Name FROM inspire1__Project__c WHERE inspire1__Account__c != null AND inspire1__Opportunity1__c = null AND RecordType.DeveloperName = 'SCS_Consulting'];
        for(inspire1__Project__c prj : projects){
            prjIdSet.add(prj.Id);
        }
        sFilesCallout.createFoldersonSharePointForProject(prjIdSet);
    }
    
    @isTest 
    static void testProjectSGS() {
        Set<Id> prjIdSet = new Set<Id>();
        List<inspire1__Project__c> projects = [SELECT Id, Name FROM inspire1__Project__c WHERE inspire1__Account__c = null AND inspire1__Opportunity1__c = null];
        for(inspire1__Project__c prj : projects){
            prjIdSet.add(prj.Id);
        }
        sFilesCallout.createFoldersonSharePointForProject(prjIdSet);
    }
    
    @isTest 
    static void testProjectSS() {
        Set<Id> prjIdSet = new Set<Id>();
        List<inspire1__Project__c> projects = [SELECT Id, Name FROM inspire1__Project__c WHERE inspire1__Account__c = null AND inspire1__Opportunity1__c = null AND RecordType.DeveloperName = 'SCS_Standard'];
        for(inspire1__Project__c prj : projects){
            prjIdSet.add(prj.Id);
        }
        sFilesCallout.createFoldersonSharePointForProject(prjIdSet);
    }
    
    @isTest 
    static void testProjectSC() {
        Set<Id> prjIdSet = new Set<Id>();
        List<inspire1__Project__c> projects = [SELECT Id, Name FROM inspire1__Project__c WHERE inspire1__Account__c = null AND inspire1__Opportunity1__c = null AND RecordType.DeveloperName = 'SCS_Consulting'];
        for(inspire1__Project__c prj : projects){
            prjIdSet.add(prj.Id);
        }
        sFilesCallout.createFoldersonSharePointForProject(prjIdSet);
    }
    
    public class SCS_sFilesMock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest request) {
            HttpResponse response = new HttpResponse();
            response.setHeader('Content-Type', 'application/json');
            response.setBody('{"ApiActionStatus":null,"CreatedBy":null, "CreatedDateTime":null, "CustomFields":null, "Description":null, "DisplayName":null, "DriveFolderId":null, "Format":null, "FormattedLastModified":null, "Id":"01ZEWS4T24FTSQMPOYZND3Z4VEGORXFNLU", "Index":null, "ModifiedBy":null, "Name":"007AAbb", "NameWithoutExt":"007AAbb", "NextLink":null, "OpenUrl":"https://scsglobalservices.sharepoint.com/Shared%20Documents/Salesforce%20sFiles/SANDBOX/QA/007AAbb", "ParentId":"01ZEWS4T7GSH5FJ4YC7NDIRHROT7HKKVF7", "ParentPath":"Salesforce%20sFiles%2FSANDBOX%2FQA", "RootLevel":null, "SalesforceId":null, "SecurityFields":null, "SharepointGuid":null, "SharepointListId":null, "Size":"0 bytes", "Type":"Folder", "Url":"/Shared%20Documents/Salesforce%20sFiles/SANDBOX/QA/007AAbb", "items":null}');
            response.setStatusCode(201);
            return response; 
        }
    }
    
    
}