force-app/main/default/objects/Account/fields/External_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Record_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Record Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>SCS Global Services departments</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Contact/fields/External_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Record_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Record Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/inspire1__Project__c/inspire1__Project__c.object-meta.xml
<CustomObject>
    <description>Inspire Planner - This object captures the detail of the project record</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/inspire1__Project__c/recordTypes/ECS.recordType-meta.xml
<RecordType>
    <fullName>ECS</fullName>
    <active>true</active>
    <label>ECS</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/External_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Record_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Record Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Opportunity with or without products
Total Opportunity Amount</description>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/ECS.recordType-meta.xml
<RecordType>
    <fullName>ECS</fullName>
    <active>true</active>
    <businessProcess>SCS Global Services Sales Process</businessProcess>
    <label>ECS</label>
</RecordType>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/External_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Record_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Record Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/External_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Record_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Record Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SCS_TaskTrigger_Test.cls
/*
@Author : MAANTIC
@CreatedDate : 19th Oct 2022
@Description : Task trigger test.
*/
/****************************** NEW ORG CODE *****************************************************/

@isTest
public class SCS_TaskTrigger_Test {
    //Setup data...
    @testSetup static void setup() {
        //Create Sales user...
        Id accRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Customer').getRecordTypeId();
        Id oppRTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('ECS').getRecordTypeId();
        Id conRTId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Customer').getRecordTypeId();
        
        List<User> users = SCS_TestDataFactory.createUsers(SCS_TestDataFactory.getSystemIntegratorProfile(), 1);
        users[0].Username = 'salesuser@scsuser.com';
        insert users;
        
        System.runAs(users[0]){
            //Set Mock response...
            Test.setMock(HttpCalloutMock.class, new SCS_DataSyncMock()); 
            //Create Account record...
            List<Account> accountList = SCS_TestDataFactory.createAccounts(accRTId,1);
            accountList[0].BillingCountry= 'United States';
            insert accountList;
            //Create Program record...
            List<Program__c> proList = SCS_TestDataFactory.createPrograms(1);
            proList[0].name = 'SQF';
            insert proList;
            //Create Campaign record... 
            List<Campaign> campaign = SCS_TestDataFactory.createCampaing(1);
            insert campaign;
            //Create Contact record...
            List<Contact> conList = SCS_TestDataFactory.createContacts(accountList[0].Id,conRTId,1);
            insert conList;
            //Create Opportunity record...
            List<Opportunity> oppList = SCS_TestDataFactory.createOpportunity('Enquiry',accountList[0].Id,proList[0].Id,oppRTId ,Date.today(),1);
            oppList[0].Type = 'New Business';
            oppList[0].TotalAmount__c = 1000;
            oppList[0].CampaignId  = campaign[0].Id;
            insert oppList;
            
            //Create Project...
            List<inspire1__Project__c> projects = SCS_TestDataFactory.createProject(accountList[0].Id, oppList[0].Id, 1);
            insert projects;
            
            //Create task...
            Task tsk = new Task ();
            tsk.Subject = 'OppoTask';
            tsk.WhoId = conList[0].Id;
            tsk.WhatId = oppList[0].Id;
            tsk.Priority = 'Normal';
            tsk.Status = 'Open';
            insert tsk;
            
            Task tsk2 = new Task ();
            tsk2.Subject = 'OppoTask2';
            tsk2.WhoId = conList[0].Id;
            tsk2.WhatId = projects[0].Id;
            tsk2.Priority = 'Normal';
            tsk2.Status = 'Open';
            insert tsk2;
            
            Task tsk3 = new Task ();
            tsk3.Subject = 'OppoTask3';
            tsk3.WhoId = conList[0].Id;
            tsk3.WhatId = accountList[0].Id;
            tsk3.Priority = 'Normal';
            tsk3.Status = 'Open';
            insert tsk3;
        }
        
    }
    
    @isTest static void testTask() {
        Test.startTest();
        //Query web integrator user...
        User usr =[SELECT Id FROM User WHERE Username = 'salesuser@scsuser.com' LIMIT 1];
        System.runAs(usr){
            //Set mock response...
            Test.setMock(HttpCalloutMock.class, new SCS_DataSyncMock());
            //Get Campaign ...
            List<Task> recordList =[SELECT Id,External_Record_Id__c FROM Task  WHERE Subject ='OppoTask'];
            //Update campaign records...
            update recordList;
            //Verify the response...
            //System.assertEquals('SCSTESTId',recordList[0].External_Record_Id__c,'External Record should not be blank');
            //Delete record to cover delete event in trigger...
            Database.Delete(recordList,false);
            //Un-Delete record to cover delete event in trigger...
            undelete recordList;
        }
        Test.stopTest();  
    }
    
    @isTest static void testTask2() {
        Test.startTest();
        //Query web integrator user...
        User usr =[SELECT Id FROM User WHERE Username = 'salesuser@scsuser.com' LIMIT 1];
        System.runAs(usr){
            //Set mock response...
            Test.setMock(HttpCalloutMock.class, new SCS_DataSyncMock());
            //Get Campaign ...
            List<Task> recordList =[SELECT Id,External_Record_Id__c FROM Task  WHERE Subject ='OppoTask2'];
            update recordList;
        }
        Test.stopTest();  
    }
    
    @isTest static void testTask3() {
        Test.startTest();
        //Query web integrator user...
        User usr =[SELECT Id FROM User WHERE Username = 'salesuser@scsuser.com' LIMIT 1];
        System.runAs(usr){
            //Set mock response...
            Test.setMock(HttpCalloutMock.class, new SCS_DataSyncMock());
            //Get Campaign ...
            List<Task> recordList =[SELECT Id,External_Record_Id__c FROM Task  WHERE Subject ='OppoTask3'];
            update recordList;
        }
        Test.stopTest();  
    }
    
    public class SCS_DataSyncMock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest request) {
            HttpResponse response = new HttpResponse();
            response.setHeader('Content-Type', 'application/json');
            response.setBody('{"id":"SCSTESTId","success":true,"errors":[],"created":true}');
            response.setStatusCode(201);
            return response; 
        }
    }
    
}