force-app/main/default/objects/Account/fields/External_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Record_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Record Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/fw1__Entity__c.field-meta.xml
<CustomField>
    <fullName>fw1__Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity</label>
    <referenceTo>fw1__Entity__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/External_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Record_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Record Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/fw1__Entity__c/fw1__Entity__c.object-meta.xml
<CustomObject>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/fw1__Entity__c/fields/fw1__Payment_Center_Setting__c.field-meta.xml
<CustomField>
    <fullName>fw1__Payment_Center_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Center Setting</label>
    <referenceTo>fw1__Payment_Center_Setting__c</referenceTo>
    <relationshipLabel>Entities</relationshipLabel>
    <relationshipName>Entities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/fw1__Invoice__c/fw1__Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/fw1__Invoice__c/fields/External_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Record_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Record Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/fw1__Invoice__c/fields/fw1__Account__c.field-meta.xml
<CustomField>
    <fullName>fw1__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/fw1__Invoice__c/fields/fw1__Contact__c.field-meta.xml
<CustomField>
    <fullName>fw1__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.fw1__Account__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/fw1__Invoice__c/fields/fw1__Entity__c.field-meta.xml
<CustomField>
    <fullName>fw1__Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity</label>
    <referenceTo>fw1__Entity__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/fw1__Invoice__c/fields/fw1__Opportunity__c.field-meta.xml
<CustomField>
    <fullName>fw1__Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/fw1__Invoice__c/fields/fw1__Payment_Profile__c.field-meta.xml
<CustomField>
    <fullName>fw1__Payment_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Payment profile to be used for Auto-BillPay installments</inlineHelpText>
    <label>Payment Profile</label>
    <referenceTo>fw1__PaymentProfile__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/fw1__Invoice__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <formula>fw1__Opportunity__r.Programc__r.Name</formula>
    <label>Program</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fw1__Invoice_Line__c/fw1__Invoice_Line__c.object-meta.xml
<CustomObject>
    <label>Invoice Line</label>
    <nameField>
        <label>Line Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/fw1__Invoice_Line__c/fields/External_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Record_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Record Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/fw1__Invoice_Line__c/fields/fw1__Invoice__c.field-meta.xml
<CustomField>
    <fullName>fw1__Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>fw1__Invoice__c</referenceTo>
    <relationshipLabel>Invoice Lines</relationshipLabel>
    <relationshipName>Invoice_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/fw1__Payment_Center_Setting__c/fw1__Payment_Center_Setting__c.object-meta.xml
<CustomObject>
    <label>Payment Center Setting</label>
    <nameField>
        <label>Payment Center Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Center Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/fw1__PaymentProfile__c/fw1__PaymentProfile__c.object-meta.xml
<CustomObject>
    <label>Payment Profile</label>
    <nameField>
        <label>Payment Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/fw1__PaymentProfile__c/fields/fw1__Account__c.field-meta.xml
<CustomField>
    <fullName>fw1__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Profiles</relationshipLabel>
    <relationshipName>Payment_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/fw1__PaymentProfile__c/fields/fw1__Contact__c.field-meta.xml
<CustomField>
    <fullName>fw1__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.fw1__Account__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payment Profiles</relationshipLabel>
    <relationshipName>Payment_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/External_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Record_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Record Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/fw2__Entity__c.field-meta.xml
<CustomField>
    <fullName>fw2__Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Following entities are valid- SCS Global, SCS Consulting, Ivory Coast and SCS Standards</inlineHelpText>
    <label>Entity</label>
    <referenceTo>fw1__Entity__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Price Books</relationshipLabel>
    <relationshipName>Price_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/External_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Record_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Record Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Program__c/fields/SCS_Global_QB_Entity__c.field-meta.xml
<CustomField>
    <fullName>SCS_Global_QB_Entity__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SCS Global (QB Entity)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/External_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Record_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Record Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/FnA_InvoiceLineSchedular_Test.cls
/**************************************************** New ORG CODE ***************************************************************** 
* Class Name        : FnA_InvoiceLineSchedular_Test
* Related Class Name: FnA_InvoiceLineSchedular
* Division          : FnA
* Version           : 1.0
* Code reviewed By  : Amitava Dutta
* Functionality     : This schedular use to sync fw1__Invoice_Line__c in evey 20 minutes from new org to old org.And batch size must be 1.

* Modification Log  :
-------------------------------------------------------------------------------------------------------------------------------------------------
* Developer Name                     Date                                Description
* -----------------------------------------------------------------------------------------------------------------------------------------------
* Umesh Kumar                        30-01-2023                          Initial version 
************************************************************************************************************************************/

@isTest
public class FnA_InvoiceLineSchedular_Test {
    //Setup data...
    @testSetup static void setup() {
        //Create web integrator user...
        List<User> userList = SCS_TestDataFactory.createUser('Sales User',1);
        userList[0].Username ='salesuser@scsuser.com';
        insert userList;
        System.runAs(userList[0]){
            //Set Mock response...
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorClass());
            //Insert account...
            List<Account> accList = SCS_TestDataFactory.createAccounts(SNM_TestConstant.customerAccRTId,1);
            insert accList;
            
            //Insert Contact...
            List<Contact> contacts = SCS_TestDataFactory.createContacts(accList[0].Id,SNM_TestConstant.customerConRTId,1);
            insert contacts;
            
            //Insert Program...
            List<Program__c> programs = SCS_TestDataFactory.createPrograms(1);
            programs[0].name = 'SQF';
            programs[0].SCS_Global_QB_Entity__c = true;
            insert programs;
            
            //Create payment Center Setting...
            List<fw1__Payment_Center_Setting__c> pcs = SCS_TestDataFactory.createPaymentCenterSettings(1);
            insert pcs;
            //Create scs global entity...
            List<fw1__Entity__c> entitys = SCS_TestDataFactory.createEntity(1);
            entitys[0].fw1__Payment_Center_Setting__c = pcs[0].Id;
            insert entitys;
            //Insert Campaign...
            List<Campaign> camp = SCS_TestDataFactory.createCampaing(1);
            insert camp;
            //Insert Opportunity...
            List<Opportunity> opportunity = SCS_TestDataFactory.createOpportunity('Closed Won', accList[0].Id,programs[0].Id,SNM_TestConstant.eCSOppoRTId,Date.Today(),1);
            opportunity[0].fw2__Entity__c = entitys[0].Id;
            opportunity[0].CampaignId = camp[0].Id;
            opportunity[0].Billing_Contact__c = contacts[0].Id;
            insert opportunity;
            //Insert payment Profile...
            List<fw1__PaymentProfile__c> paymentProfile = SCS_TestDataFactory.createPaymentProfiles(accList[0].Id,entitys[0].Id,1);
            insert paymentProfile;
            //Insert Invoice...
            List<fw1__Invoice__c> invoice = SCS_TestDataFactory.createInvoice(1);
            invoice[0].fw1__Entity__c = entitys[0].Id;
            invoice[0].fw1__Payment_Profile__c = paymentProfile[0].Id;
            invoice[0].fw1__Account__c = accList[0].Id;
            invoice[0].fw1__Contact__c = contacts[0].Id;
            invoice[0].fw1__Opportunity__c = opportunity[0].Id;
            insert invoice;
            //
            PriceBook2 pb2=new PriceBook2();
            pb2.Name = 'test';
            pb2.IsActive = true;      
            insert pb2;
            //Insert product...
            List<Product2> prodListDummy = SCS_TestDataFactory.createProduct(1,'P - Professional Fees','USD');
            insert prodListDummy;
            //Insert Invoice line...
            List<fw1__Invoice_Line__c> invoiceLine = SCS_TestDataFactory.createInvoiceLines(prodListDummy[0].Id,pb2.Id,invoice[0].Id,1);
            invoiceLine[0].Name = 'IL';
            insert invoiceLine;
            
            FnA_InvoiceLineSchedular obj = new FnA_InvoiceLineSchedular();
            obj.execute(null);
            
        }
        
    }
    
    @isTest static void testInvoiceLineSchedular() {
        Test.startTest();
        //Query web integrator user...
        User usr =[SELECT Id FROM User WHERE Username = 'salesuser@scsuser.com' LIMIT 1];
        System.runAs(usr){
            //Set mock response...
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorClass());
            //Get records ...
            //List<fw1__Invoice_Line__c> recordList =[SELECT Id,Name,External_Record_Id__c FROM fw1__Invoice_Line__c];
            //Verify the response...
            //System.assertEquals('external-Id',recordList[0].External_Record_Id__c,'External Record should not be blank');
        }
        Test.stopTest();  
    }
    
}