force-app/main/default/objects/Account/fields/External_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Record_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Record Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/fw1__Entity__c.field-meta.xml
<CustomField>
    <fullName>fw1__Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity</label>
    <referenceTo>fw1__Entity__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>SCS Global Services departments</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/fw1__Entity__c/fw1__Entity__c.object-meta.xml
<CustomObject>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/fw1__Entity__c/fields/fw1__Payment_Center_Setting__c.field-meta.xml
<CustomField>
    <fullName>fw1__Payment_Center_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Center Setting</label>
    <referenceTo>fw1__Payment_Center_Setting__c</referenceTo>
    <relationshipLabel>Entities</relationshipLabel>
    <relationshipName>Entities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/fw1__Payment_Center_Setting__c/fw1__Payment_Center_Setting__c.object-meta.xml
<CustomObject>
    <label>Payment Center Setting</label>
    <nameField>
        <label>Payment Center Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Center Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/fw1__PaymentProfile__c/fw1__PaymentProfile__c.object-meta.xml
<CustomObject>
    <label>Payment Profile</label>
    <nameField>
        <label>Payment Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SCS_PaymentProfileTrigger_Test.cls
/*
@Author : MAANTIC
@CreatedDate : SEP 2022
@Description : This test class for SCS_PaymentProfileTrigger trigger.
*/


@isTest
public class SCS_PaymentProfileTrigger_Test {
    static Id accRT_Id = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Customer').getRecordTypeId();
    //Setup data...
    @testSetup static void setup() {
        
        System.runAs( SCS_TestDataFactory.getWebIntegratorUser() ){
            //Set Mock response...
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorClass());
            //Create Account record...
            List<Account> accList = SCS_TestDataFactory.createAccounts(accRT_Id,1);
            accList[0].BillingCountry= 'United States';
            insert accList;
            //Create payment center setting...
            List<fw1__Payment_Center_Setting__c> pcs = SCS_TestDataFactory.createPaymentCenterSettings(1); 
            insert pcs;
            //Create Entity record...
            List<fw1__Entity__c> entitys = SCS_TestDataFactory.createEntitys(pcs[0].Id,1);
            insert entitys;
            //Create payment profile...
            List<fw1__PaymentProfile__c> paymentProfile = SCS_TestDataFactory.createPaymentProfiles(accList[0].Id,entitys[0].Id,1);
            paymentProfile[0].Name = 'PProfile';
            insert paymentProfile;
            
        }
         
    }
    
    @isTest static void testPaymentProfile() {
        Test.startTest();
        
        System.runAs(SCS_TestDataFactory.getWebIntegratorUser()){
            //Set mock response...
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorClass());
            //Get record ...
            List<fw1__PaymentProfile__c> recordList =[SELECT Id,Name,External_Record_Id__c FROM fw1__PaymentProfile__c  WHERE Name = 'PProfile'];
            //Update records...
            update recordList;
            //Verify the response...
            //System.assertEquals('SCSTESTId',recordList[0].External_Record_Id__c,'External Record should not be blank');
            //Delete record to cover delete event in trigger...
            Database.Delete(recordList,false);
            //Un-Delete record to cover delete event in trigger...
            undelete recordList;
        }
        Test.stopTest();  
    }
    
}