force-app/main/default/objects/Account/fields/External_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Record_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Record Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/External_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Record_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Record Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/External_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Record_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Record Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Site_Covered__c/Site_Covered__c.object-meta.xml
<CustomObject>
    <description>List of Customer Sites covered for the Opportunity and related Project</description>
    <label>Site Covered</label>
    <nameField>
        <displayFormat>SC-{0000000}</displayFormat>
        <label>Site Covered Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sites Covered</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/External_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Record_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Record Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SNM_SiteCoveredTrigger_Test.cls
/**************************************************** NEW ORG CODE ***************************************************************** 
* Test Class Name   : SNM_SiteCoveredTrigger_Test
* Test Class For    : SNM_SiteCoveredTrigger,SNM_SiteCoveredTriggerHandler
* Division          : Sales and marketing
* Version           : 1.0
* Code reviewed By  : Amitava Dutta
* Functionality     : Test site covered sync functionality from new org to old org...

* Modification Log  :
-------------------------------------------------------------------------------------------------------------------------------------------------
* Developer Name                     Date                                Description
* -----------------------------------------------------------------------------------------------------------------------------------------------
* Umesh Kumar                        21-10-2022                          Initial version 
************************************************************************************************************************************/

@isTest
public class SNM_SiteCoveredTrigger_Test {
    //Setup data...
    @testSetup static void setup() {
        //Create web integrator user...
        List<User> userList = SCS_TestDataFactory.createUser('SCS Integration',1);
        userList[0].Username ='salesuser@scsuser.com';
        insert userList;
        System.runAs(userList[0]){
            //Set Mock response...
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorClass()); 
            //Create Account record...
            List<Account> accList = SCS_TestDataFactory.createAccounts(SNM_TestConstant.customerAccRTId,1);
            insert accList;
            //Create Program record...
            List<Program__c> programs = SCS_TestDataFactory.createPrograms(1);
            programs[0].Name = 'SQF';
            insert programs;
            //Create Campaign...
            List<Campaign> campaign = SCS_TestDataFactory.createCampaing(1);
            insert campaign;
            //Create Opportunity record...
            List<Opportunity> oppList = SCS_TestDataFactory.createOpportunity('Enquiry',accList[0].Id,programs[0].Id,SNM_TestConstant.eCSOppoRTId,Date.today(),1);
            oppList[0].CampaignId  = campaign[0].Id;
            insert oppList;
            //Insert site covered...
            List<Site_Covered__c> oppoSite = SCS_TestDataFactory.createSiteCovered(oppList[0].Id,1);
            insert oppoSite;
            
        }
        
    }
    
    @isTest static void testSiteCovered() {
        Test.startTest();
        //Query web integrator user...
        User usr =[SELECT Id FROM User WHERE Username = 'salesuser@scsuser.com' LIMIT 1];
        System.runAs(usr){
            //Set mock response...
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorClass());
            //Get record ...
            List<Site_Covered__c> recordList =[SELECT Id,Name,External_Record_Id__c FROM Site_Covered__c];
            //Update  records...
            update recordList;
            //Verify the response...
            System.assertEquals('external-Id',recordList[0].External_Record_Id__c,'External Record should not be blank');
            //Delete record to cover delete event in trigger...
            Database.Delete(recordList,false);
            //Un-Delete record to cover delete event in trigger...
            undelete recordList;
        }
        Test.stopTest();  
    }
    
}