force-app/main/default/objects/Account/fields/fw1__Entity__c.field-meta.xml
<CustomField>
    <fullName>fw1__Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity</label>
    <referenceTo>fw1__Entity__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <defaultValue>&apos;Net 30&apos;</defaultValue>
    <inlineHelpText>If you are changing the value to Net 45 or Net 60 then make sure to click on &quot;Submit for approval&quot; from the top right corner dropdown. The value will be changed only post approval of the Accounting team.</inlineHelpText>
    <label>Payment Terms</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SC_SharePoint_Folder_Id__c.field-meta.xml
<CustomField>
    <fullName>SC_SharePoint_Folder_Id__c</fullName>
    <label>SC SharePoint Folder Id</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>SCS Global Services departments</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Certificate__c/Certificate__c.object-meta.xml
<CustomObject>
    <description>Certificate issued to Client</description>
    <label>Certificate</label>
    <nameField>
        <displayFormat>CRT-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certificates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certificate__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Certificates</relationshipLabel>
    <relationshipName>Certificates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/fw1__Entity__c/fw1__Entity__c.object-meta.xml
<CustomObject>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Goal__c/Goal__c.object-meta.xml
<CustomObject>
    <label>Goal</label>
    <nameField>
        <displayFormat>G-{00000}</displayFormat>
        <label>Goal Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Goal__c/fields/Programc__c.field-meta.xml
<CustomField>
    <fullName>Programc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Goals</relationshipLabel>
    <relationshipName>Goals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Goal__c/recordTypes/Program_Goal.recordType-meta.xml
<RecordType>
    <fullName>Program_Goal</fullName>
    <active>true</active>
    <label>Program Goal</label>
</RecordType>

force-app/main/default/objects/inspire1__Project__c/inspire1__Project__c.object-meta.xml
<CustomObject>
    <description>Inspire Planner - This object captures the detail of the project record</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/inspire1__Project__c/fields/inspire1__Opportunity1__c.field-meta.xml
<CustomField>
    <fullName>inspire1__Opportunity1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity related to Project.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/inspire1__Project__c/recordTypes/Bundle_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Bundle_Opportunity</fullName>
    <active>true</active>
    <label>Bundle Opportunity</label>
</RecordType>

force-app/main/default/objects/inspire1__Project__c/recordTypes/ECS.recordType-meta.xml
<RecordType>
    <fullName>ECS</fullName>
    <active>true</active>
    <label>ECS</label>
</RecordType>

force-app/main/default/objects/inspire1__Project__c/recordTypes/SCS_Consulting.recordType-meta.xml
<RecordType>
    <fullName>SCS_Consulting</fullName>
    <active>true</active>
    <label>SCS Consulting</label>
</RecordType>

force-app/main/default/objects/inspire1__Project__c/recordTypes/SCS_Standard.recordType-meta.xml
<RecordType>
    <fullName>SCS_Standard</fullName>
    <active>true</active>
    <description>RT for SCS Standard Records</description>
    <label>SCS Standard</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/AllProjectSharePointFolderId__c.field-meta.xml
<CustomField>
    <fullName>AllProjectSharePointFolderId__c</fullName>
    <label>AllProjectSharePointFolderId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Engagement_Type__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Type__c</fullName>
    <label>Engagement Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Program_List__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Engagement_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Salesforce Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Entity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/fileforcem1__Sharepoint_Folder_Id__c.field-meta.xml
<CustomField>
    <fullName>fileforcem1__Sharepoint_Folder_Id__c</fullName>
    <description>Field that holds SharePoint&apos;s folder Id.</description>
    <inlineHelpText>Field that holds SharePoint&apos;s folder Id.</inlineHelpText>
    <label>SharePoint Folder Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IsConverted__c.field-meta.xml
<CustomField>
    <fullName>IsConverted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsConverted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Programc__c.field-meta.xml
<CustomField>
    <fullName>Programc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>The selected program is deprecated, please select another program</errorMessage>
        <filterItems>
            <field>Program__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Deprecated</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Opportunity with or without products
Total Opportunity Amount</description>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Bundle_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Bundle_Opportunity</fullName>
    <active>true</active>
    <businessProcess>SCS Global Services Sales Process</businessProcess>
    <label>Bundle Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/ECS.recordType-meta.xml
<RecordType>
    <fullName>ECS</fullName>
    <active>true</active>
    <businessProcess>SCS Global Services Sales Process</businessProcess>
    <label>ECS</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/SCS_Consulting.recordType-meta.xml
<RecordType>
    <fullName>SCS_Consulting</fullName>
    <active>true</active>
    <businessProcess>SCS Standard Sales Process</businessProcess>
    <label>SCS Consulting</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/SCS_Standard.recordType-meta.xml
<RecordType>
    <fullName>SCS_Standard</fullName>
    <active>true</active>
    <businessProcess>SCS Standard Sales Process</businessProcess>
    <label>SCS Standard</label>
</RecordType>

force-app/main/default/objects/Opportunity_Certificate__c/Opportunity_Certificate__c.object-meta.xml
<CustomObject>
    <label>Opportunity Certificate</label>
    <nameField>
        <displayFormat>OC-{0000}</displayFormat>
        <label>Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Certificates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Certificate__c/fields/Certificate__c.field-meta.xml
<CustomField>
    <fullName>Certificate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Certificate</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Certificate__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Certificate__c</referenceTo>
    <relationshipLabel>Opportunity Certificates</relationshipLabel>
    <relationshipName>Opportunity_Certificates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Entity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Standard__c/Standard__c.object-meta.xml
<CustomObject>
    <label>Standard</label>
    <nameField>
        <label>Standard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standards</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Standard__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Standards</relationshipLabel>
    <relationshipName>Standards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Engagement_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1st Surveillance</fullName>
    </customValue>
    <customValue>
        <fullName>2nd Surveillance</fullName>
    </customValue>
    <customValue>
        <fullName>3rd Party Verification</fullName>
    </customValue>
    <customValue>
        <fullName>3rd Surveillance</fullName>
    </customValue>
    <customValue>
        <fullName>4th Surveillance</fullName>
    </customValue>
    <customValue>
        <fullName>ACDR only</fullName>
    </customValue>
    <customValue>
        <fullName>Action Plan Review</fullName>
    </customValue>
    <customValue>
        <fullName>AIM Initial</fullName>
    </customValue>
    <customValue>
        <fullName>AIM Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <customValue>
        <fullName>Annual Surveillance</fullName>
    </customValue>
    <customValue>
        <fullName>CAP</fullName>
    </customValue>
    <customValue>
        <fullName>Certification</fullName>
    </customValue>
    <customValue>
        <fullName>Closure of Findings</fullName>
    </customValue>
    <customValue>
        <fullName>Complaint Resolution</fullName>
    </customValue>
    <customValue>
        <fullName>Conformance Surveillance</fullName>
    </customValue>
    <customValue>
        <fullName>Consulting</fullName>
    </customValue>
    <customValue>
        <fullName>Due Diligence</fullName>
    </customValue>
    <customValue>
        <fullName>Each Additional</fullName>
    </customValue>
    <customValue>
        <fullName>Evaluation</fullName>
    </customValue>
    <customValue>
        <fullName>Expansion of Scope</fullName>
    </customValue>
    <customValue>
        <fullName>Expedited Audit</fullName>
    </customValue>
    <customValue>
        <fullName>Extension</fullName>
    </customValue>
    <customValue>
        <fullName>Field Assessment</fullName>
    </customValue>
    <customValue>
        <fullName>FIP Services</fullName>
    </customValue>
    <customValue>
        <fullName>Follow-up</fullName>
    </customValue>
    <customValue>
        <fullName>FSA Farm Management Group Claims</fullName>
    </customValue>
    <customValue>
        <fullName>FSA Option 1</fullName>
    </customValue>
    <customValue>
        <fullName>FSA Option 2</fullName>
    </customValue>
    <customValue>
        <fullName>FSA Option 3</fullName>
    </customValue>
    <customValue>
        <fullName>Initial</fullName>
        <default>true</default>
        <label>Initial</label>
    </customValue>
    <masterLabel>Engagement Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Entity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ECS</fullName>
    </customValue>
    <customValue>
        <fullName>Food and Agriculture</fullName>
    </customValue>
    <customValue>
        <fullName>Natural Resources</fullName>
    </customValue>
    <customValue>
        <fullName>SCS Consulting</fullName>
    </customValue>
    <customValue>
        <fullName>SCS Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Research and Development</fullName>
    </customValue>
    <customValue>
        <fullName>Advanced Technical Programs</fullName>
    </customValue>
    <masterLabel>Entity</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/sFilesBatchtoCreateFoldersTest.cls
/************************************************************************************************************************************************
Apex Class Name : sFilesBatchtoCreateFoldersTest
Version         : 1.0
Created Date    : 
Function        : This test class is used to cover the 'sFilesBatchtoCreateFolders', 'sFilesBatchtoUploadFiles' and 'sFilesBatchQueabletoUploadFiles' apex class.
Modification Log:
-------------------------------------------------------------------------------------------------------------------------------------------------
* Developer                                 Date                                Description
* -----------------------------------------------------------------------------------------------------------------------------------------------
Sohit Tripathi                          19/01/2023                            Initial version
**************************************************************************************************************************************************/
@isTest
public class sFilesBatchtoCreateFoldersTest{
    @testSetup 
    static void setup() {
        Id accRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Customer').getRecordTypeId();
        Id oppRTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('ECS').getRecordTypeId();
        Id oppSCSStandrdRTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('SCS_Standard').getRecordTypeId();
        Id goalRTId = Schema.SObjectType.Goal__c.getRecordTypeInfosByDeveloperName().get('Program_Goal').getRecordTypeId();
        Id bundelOppRTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Bundle_Opportunity').getRecordTypeId();
        id contRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Customer').getRecordTypeId();
        id consOpRTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('SCS_Consulting').getRecordTypeId();
        System.runAs( SCS_TestDataFactory.getWebIntegratorUser()){
            List<Account> accountList = SCS_TestDataFactory.createAccounts(accRTId,1);
            accountList[0].BillingCountry= 'United States';
            accountList[0].SC_SharePoint_Folder_Id__c = '255222XDF';
            accountList[0].Payment_Terms__c = 'Net 30';
            insert accountList;
            
            List<Contact> blcont = SCS_TestDataFactory.createContacts(accountList[0].id, contRecTypeId, 1);
            insert blcont;
            
            List<Program__c> proList = SCS_TestDataFactory.createPrograms(2);
            proList[0].name = 'SQF';
            proList[0].Entity__c = 'ECS';
            proList[1].name = 'IRMA';
            proList[1].Entity__c = 'SCS Standard';
            insert proList; 
            //Create standard...
            List<Standard__c> standards = SCS_TestDataFactory.createStandard(proList[0].Id,1);
            insert standards;
            List<Campaign> campaign = SCS_TestDataFactory.createCampaing(1);
            insert campaign;
            List<fw1__Entity__c> entList=SCS_TestDataFactory.createEntity(1);
            insert entList;
            List<Opportunity> oppList = SCS_TestDataFactory.createOpportunity('Enquiry', accountList[0].Id, proList[0].Id, oppRTId ,Date.newInstance(2023,1,5), 2);
            oppList[0].Type = 'New Business';
            oppList[0].TotalAmount__c = 1000;
            oppList[0].CampaignId  = campaign[0].Id;
            oppList[0].IsConverted__c = True;
            
            oppList[1].Type = 'New Business';
            oppList[1].RecordTypeId = oppSCSStandrdRTId;
            oppList[1].Programc__c = proList[1].Id;
            oppList[1].IsConverted__c = True;
            oppList[1].Engagement_Type__c = 'Initial';
            insert oppList;
            
            //Create Project...
            List<inspire1__Project__c> projects = SCS_TestDataFactory.createProject(accountList[0].Id, oppList[1].Id, 2);
            projects[1].inspire1__Opportunity1__c = oppList[0].Id;
            insert projects;
            
            List<Certificate__c> certList =new List<Certificate__c>();
            List<Opportunity_certificate__c> opcerlist = new List<Opportunity_certificate__c>();
            certList = SCS_TestDataFactory.createCertificate(1);
            insert certList;
        
            opcerlist = SCS_TestDataFactory.createOppsCertificate(certList[0], oppList);
            insert opcerlist;
        }
        
    }
    
    @isTest 
    static void testOpportunitySCSStandard() {
        Test.startTest();
        System.runAs(SCS_TestDataFactory.getWebIntegratorUser()){
            //Set mock response...
            Test.setMock(HttpCalloutMock.class, new SCS_sFilesMock()); 
            Set<Id> accIdSet = new Set<Id>();
            Set<Id> opptyIdSet = new Set<Id>();
            set<id> opptySCSSet = new Set<Id>();
            set<id> opptySCSSt = new Set<Id>();
            
            Set<Id> prjIdSet = new Set<Id>();
            List<Account> accList =[SELECT Id, Name FROM Account];
            Id oppSCSStandrdRTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('SCS_Standard').getRecordTypeId();
           
            List<Opportunity> recordListST = [SELECT Id,Name,StageName,RecordTypeId,Type FROM Opportunity WHERE RecordTypeId =:oppSCSStandrdRTId];
            SYstem.debug('recordListST 92-- '+recordListST);
            List<Opportunity> opptyList = new List<Opportunity>();
            List<Opportunity> opptyListSCS = new List<Opportunity>();
            List<Opportunity> opptyListST = new List<Opportunity>();
            List<ContentVersion> converList = new List<ContentVersion>();
            
            for(Account acc : accList){
                accIdSet.add(acc.Id);
            }
            
            for(Opportunity oppst:recordListST)
            {
                oppst.fileforcem1__Sharepoint_Folder_Id__c = '13221314213123123';
                opptySCSSt.add(oppst.Id);
                opptyListST.add(oppst);
            }
            update opptyListST;
            List<inspire1__Project__c> projects = [SELECT Id, Name FROM inspire1__Project__c WHERE inspire1__Opportunity1__r.fileforcem1__Sharepoint_Folder_Id__c != null];
            for(inspire1__Project__c prj : projects){
                prjIdSet.add(prj.Id);
            }
            
            ContentVersion contentVersion = new ContentVersion(
                Title = 'Penguins',
                PathOnClient = 'Penguins.jpg',
                VersionData = Blob.valueOf('Test Content'),
                IsMajorVersion = true,
                FirstPublishLocationId = opptyListST[0].Id
            );
            insert contentVersion;
            converList.add(contentVersion);
            
            List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
            
            //create ContentDocumentLink  record 
            ContentDocumentLink cdl = New ContentDocumentLink();
            cdl.LinkedEntityId = opptyListST[0].id;
            cdl.ContentDocumentId = documents[0].Id;
            cdl.shareType = 'V';
            //insert cdl;
            
            sFilesBatchtoCreateFolders obj = new sFilesBatchtoCreateFolders();
            DataBase.executeBatch(obj); 
            
            sFilesBatchtoUploadFiles obh = new sFilesBatchtoUploadFiles();
            DataBase.executeBatch(obh); 
            
            System.enqueuejob(new sFilesBatchQueabletoUploadFiles(converList, opptySCSSt));
            
        }
        Test.stopTest();  
    }
    
    @isTest 
    static void testOpportunitySCSGlobalServices() {
        Test.startTest();
        System.runAs(SCS_TestDataFactory.getWebIntegratorUser()){
            //Set mock response...
            Test.setMock(HttpCalloutMock.class, new SCS_sFilesMock()); 
            Id oppRTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('ECS').getRecordTypeId();
            Set<Id> accIdSet = new Set<Id>();
            Set<Id> opptyIdSet = new Set<Id>();
            Set<Id> prjIdSet = new Set<Id>();
            List<Account> accList = [SELECT Id, Name FROM Account];
            List<Program__c> proList = [Select Id, Name FROM Program__c];

            List<Opportunity> opActList = [Select id, type,totalamount__c,fileforcem1__Sharepoint_Folder_Id__c from Opportunity WHERE RecordTypeId =:oppRTId];
            List<Opportunity> opptyList = new List<Opportunity>();
            
            for(Account acc : accList){
                accIdSet.add(acc.Id);
            }
            
            for(Opportunity opp : opActList){
                opp.AllProjectSharePointFolderId__c = '4534567444';
                opptyIdSet.add(opp.Id);
                opptyList.add(opp);
            }
            update opptyList;
            List<inspire1__Project__c> projects = [SELECT Id, Name FROM inspire1__Project__c WHERE inspire1__Opportunity1__r.AllProjectSharePointFolderId__c != null];
            for(inspire1__Project__c prj : projects){
                prjIdSet.add(prj.Id);
            }
            
            sFilesCallout.createFoldersonSharePoint(opptyIdSet);
            sFilesCallout.createFoldersonSharePointForProject(prjIdSet);
        }
        Test.stopTest();  
    }
    
    
    
    public class SCS_sFilesMock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest request) {
            HttpResponse response = new HttpResponse();
            response.setHeader('Content-Type', 'application/json');
            response.setBody('{"ApiActionStatus":null,"CreatedBy":null, "CreatedDateTime":null, "CustomFields":null, "Description":null, "DisplayName":null, "DriveFolderId":null, "Format":null, "FormattedLastModified":null, "Id":"01ZEWS4T24FTSQMPOYZND3Z4VEGORXFNLU", "Index":null, "ModifiedBy":null, "Name":"007AAbb", "NameWithoutExt":"007AAbb", "NextLink":null, "OpenUrl":"https://scsglobalservices.sharepoint.com/Shared%20Documents/Salesforce%20sFiles/SANDBOX/QA/007AAbb", "ParentId":"01ZEWS4T7GSH5FJ4YC7NDIRHROT7HKKVF7", "ParentPath":"Salesforce%20sFiles%2FSANDBOX%2FQA", "RootLevel":null, "SalesforceId":null, "SecurityFields":null, "SharepointGuid":null, "SharepointListId":null, "Size":"0 bytes", "Type":"Folder", "Url":"/Shared%20Documents/Salesforce%20sFiles/SANDBOX/QA/007AAbb", "items":null}');
            response.setStatusCode(201);
            return response; 
        }
    }
    
    
}