force-app/main/default/objects/Account/fields/fw1__Entity__c.field-meta.xml
<CustomField>
    <fullName>fw1__Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity</label>
    <referenceTo>fw1__Entity__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Quickbooks_ID__c.field-meta.xml
<CustomField>
    <fullName>Quickbooks_ID__c</fullName>
    <label>Quickbooks ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>SCS Global Services departments</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/fw1__Credit_Memo__c/fw1__Credit_Memo__c.object-meta.xml
<CustomObject>
    <label>Credit Memo</label>
    <nameField>
        <displayFormat>CM-{0000000000}</displayFormat>
        <label>Credit Memo Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Memos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/fw1__Credit_Memo__c/fields/fw1__Account__c.field-meta.xml
<CustomField>
    <fullName>fw1__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Credit Memos</relationshipLabel>
    <relationshipName>Credit_Memos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/fw1__Credit_Memo__c/fields/fw1__Contact__c.field-meta.xml
<CustomField>
    <fullName>fw1__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.fw1__Account__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Credit Memos</relationshipLabel>
    <relationshipName>Credit_Memos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/fw1__Credit_Memo__c/fields/fw1__Entity__c.field-meta.xml
<CustomField>
    <fullName>fw1__Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity</label>
    <referenceTo>fw1__Entity__c</referenceTo>
    <relationshipLabel>Credit Memos</relationshipLabel>
    <relationshipName>Credit_Memos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/fw1__Credit_Memo__c/fields/fw1__Generated_From__c.field-meta.xml
<CustomField>
    <fullName>fw1__Generated_From__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Generated From</label>
    <referenceTo>fw1__Invoice__c</referenceTo>
    <relationshipLabel>Credit Memos</relationshipLabel>
    <relationshipName>Credit_Memos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/fw1__Credit_Memo__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <formula>fw1__Generated_From__r.Program__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fw1__Credit_Memo__c/fields/Quickbooks_ID__c.field-meta.xml
<CustomField>
    <fullName>Quickbooks_ID__c</fullName>
    <externalId>true</externalId>
    <label>Quickbooks ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fw1__Credit_Memo_Line__c/fw1__Credit_Memo_Line__c.object-meta.xml
<CustomObject>
    <label>Credit Memo Line</label>
    <nameField>
        <label>Line Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Memo Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/fw1__Credit_Memo_Line__c/fields/fw1__Credit_Memo__c.field-meta.xml
<CustomField>
    <fullName>fw1__Credit_Memo__c</fullName>
    <label>Credit Memo</label>
    <referenceTo>fw1__Credit_Memo__c</referenceTo>
    <relationshipLabel>Credit Memo Lines</relationshipLabel>
    <relationshipName>Credit_Memo_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/fw1__Entity__c/fw1__Entity__c.object-meta.xml
<CustomObject>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/fw1__Entity__c/fields/fw1__Payment_Center_Setting__c.field-meta.xml
<CustomField>
    <fullName>fw1__Payment_Center_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Center Setting</label>
    <referenceTo>fw1__Payment_Center_Setting__c</referenceTo>
    <relationshipLabel>Entities</relationshipLabel>
    <relationshipName>Entities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/fw1__Invoice__c/fw1__Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/fw1__Invoice__c/fields/fw1__Account__c.field-meta.xml
<CustomField>
    <fullName>fw1__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/fw1__Invoice__c/fields/fw1__Contact__c.field-meta.xml
<CustomField>
    <fullName>fw1__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.fw1__Account__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/fw1__Invoice__c/fields/fw1__Entity__c.field-meta.xml
<CustomField>
    <fullName>fw1__Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity</label>
    <referenceTo>fw1__Entity__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/fw1__Invoice__c/fields/fw1__Opportunity__c.field-meta.xml
<CustomField>
    <fullName>fw1__Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/fw1__Invoice__c/fields/fw1__Payment_Profile__c.field-meta.xml
<CustomField>
    <fullName>fw1__Payment_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Payment profile to be used for Auto-BillPay installments</inlineHelpText>
    <label>Payment Profile</label>
    <referenceTo>fw1__PaymentProfile__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/fw1__Invoice__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <formula>fw1__Opportunity__r.Programc__r.Name</formula>
    <label>Program</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fw1__Invoice__c/fields/Quickbooks_ID__c.field-meta.xml
<CustomField>
    <fullName>Quickbooks_ID__c</fullName>
    <label>Quickbooks ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fw1__Payment_Center_Setting__c/fw1__Payment_Center_Setting__c.object-meta.xml
<CustomObject>
    <label>Payment Center Setting</label>
    <nameField>
        <label>Payment Center Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Center Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/fw1__PaymentProfile__c/fw1__PaymentProfile__c.object-meta.xml
<CustomObject>
    <label>Payment Profile</label>
    <nameField>
        <label>Payment Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/fw1__PaymentProfile__c/fields/fw1__Account__c.field-meta.xml
<CustomField>
    <fullName>fw1__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Profiles</relationshipLabel>
    <relationshipName>Payment_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/fw1__PaymentProfile__c/fields/fw1__Contact__c.field-meta.xml
<CustomField>
    <fullName>fw1__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.fw1__Account__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payment Profiles</relationshipLabel>
    <relationshipName>Payment_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/fw2__Entity__c.field-meta.xml
<CustomField>
    <fullName>fw2__Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Following entities are valid- SCS Global, SCS Consulting, Ivory Coast and SCS Standards</inlineHelpText>
    <label>Entity</label>
    <referenceTo>fw1__Entity__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/ECS.recordType-meta.xml
<RecordType>
    <fullName>ECS</fullName>
    <active>true</active>
    <businessProcess>SCS Global Services Sales Process</businessProcess>
    <label>ECS</label>
</RecordType>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/SCS_Global_QB_Entity__c.field-meta.xml
<CustomField>
    <fullName>SCS_Global_QB_Entity__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SCS Global (QB Entity)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/FnA_ScheduleCreditMemoLine_Test.cls
@isTest
public class FnA_ScheduleCreditMemoLine_Test {
    
    @TestSetup
    static void makeData(){
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorClass());
        
        Id oppRT_Id = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('ECS').getRecordTypeId();
        Id accRT_Id = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Customer').getRecordTypeId();
        Id contactRT_Id = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Customer').getRecordTypeId();
        
        List<Account> accList = SCS_TestDataFactory.createAccounts(accRT_Id,1);
        accList[0].Type ='Customer';
        accList[0].Quickbooks_ID__c ='QUICKBOOKID';
        insert accList;
        
        List<Contact> contacts = SCS_TestDataFactory.createContacts(accList[0].Id,contactRT_Id,1);
        insert contacts;
        
        List<Program__c> programs = SCS_TestDataFactory.createPrograms(1);
        programs[0].name = 'SQF';
        programs[0].SCS_Global_QB_Entity__c = true;
        insert programs;
        
        List<fw1__Payment_Center_Setting__c> pcs = SCS_TestDataFactory.createPaymentCenterSettings(1);
        insert pcs;
        
        List<fw1__Entity__c> entitys = SCS_TestDataFactory.createEntity(1);
        entitys[0].fw1__Payment_Center_Setting__c = pcs[0].Id;
        entitys[0].Name = 'SCS Global';
        insert entitys;
        
        List<Campaign> camp = SCS_TestDataFactory.createCampaing(1);
        insert camp;
        
        List<Opportunity> opportunity = SCS_TestDataFactory.createOpportunity('Closed Won', accList[0].Id,programs[0].Id,oppRT_Id,Date.Today(),1);
        opportunity[0].fw2__Entity__c = entitys[0].Id;
        opportunity[0].CampaignId = camp[0].Id;
        opportunity[0].Billing_Contact__c = contacts[0].Id;
        insert opportunity;
        
        List<fw1__PaymentProfile__c> paymentProfile = SCS_TestDataFactory.createPaymentProfiles(accList[0].Id,entitys[0].Id,1);
        insert paymentProfile;
        
        List<fw1__Invoice__c> invoice = SCS_TestDataFactory.createInvoice(1);
        invoice[0].fw1__Entity__c = entitys[0].Id;
        invoice[0].fw1__Payment_Profile__c = paymentProfile[0].Id;
        invoice[0].fw1__Account__c = accList[0].Id;
        invoice[0].fw1__Contact__c = contacts[0].Id;
        invoice[0].fw1__Opportunity__c = opportunity[0].Id;
        insert invoice;
        
        List<fw1__Credit_Memo__c> creditMemo = SCS_TestDataFactory.createCreditMemo(1,accList[0].Id);
        creditMemo[0].fw1__Contact__c = contacts[0].Id;
        creditMemo[0].fw1__Entity__c = entitys[0].Id;
        creditMemo[0].fw1__Generated_From__c = invoice[0].Id;
        insert creditMemo;
        
        List<Product2> prodListDummy = SCS_TestDataFactory.createProduct(1,'P - Professional Fees','USD');
        insert prodListDummy;
        
        List<fw1__Credit_Memo_Line__c> creditMemoLine = SCS_TestDataFactory.createCreditMemoLines(creditMemo[0].Id,prodListDummy[0].Id,1);
        creditMemoLine[0].Name = 'CMLINE';
        insert creditMemoLine;
        
    }
    
    @isTest static void creditMemoTest(){
        List<User> integratorUser = SCS_TestDataFactory.createUsers(SCS_TestDataFactory.getSystemIntegratorProfile(), 1);
        System.runAs(integratorUser[0]){
            Test.startTest();
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorClass());
            FnA_ScheduleCreditMemoLine obj = new FnA_ScheduleCreditMemoLine ();
            obj.execute(null);
            Test.stopTest();
        }
        
    }
    
}