force-app/main/default/objects/Account/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Indonesian</fullName>
            </value>
            <value>
                <fullName>Japanese</fullName>
            </value>
            <value>
                <fullName>Local Language</fullName>
            </value>
            <value>
                <fullName>Portuguese</fullName>
            </value>
            <value>
                <fullName>Swahili</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Conflict_of_Interest__c/Conflict_of_Interest__c.object-meta.xml
<CustomObject>
    <label>Conflict of Interest</label>
    <nameField>
        <displayFormat>COI-{0000000}</displayFormat>
        <label>Conflict of Interest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conflict of Interests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Conflict_of_Interest__c/fields/Auditor__c.field-meta.xml
<CustomField>
    <fullName>Auditor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Auditor (External)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Auditor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Conflict of Interests</relationshipLabel>
    <relationshipName>Conflict_of_Interests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Conflict_of_Interest__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Conflict of Interests</relationshipLabel>
    <relationshipName>Conflict_of_Interests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Auditor__c.field-meta.xml
<CustomField>
    <fullName>Auditor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auditor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/inspire1__Project__c/inspire1__Project__c.object-meta.xml
<CustomObject>
    <description>Inspire Planner - This object captures the detail of the project record</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/inspire1__Project__c/fields/Schedule_Automation__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Automation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Schedule Automation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/inspire1__Project_Tasks__c/inspire1__Project_Tasks__c.object-meta.xml
<CustomObject>
    <description>Inspire Planner - This object captures the tasks related to the project.</description>
    <label>Project Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/inspire1__Project_Tasks__c/fields/inspire1__Duration__c.field-meta.xml
<CustomField>
    <fullName>inspire1__Duration__c</fullName>
    <description>Captures project duration (days).</description>
    <label>Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/inspire1__Project_Tasks__c/fields/inspire1__DurationUnit__c.field-meta.xml
<CustomField>
    <fullName>inspire1__DurationUnit__c</fullName>
    <description>Identifies if task is managed in days or hours.</description>
    <label>Duration Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>h</fullName>
            </value>
            <value>
                <fullName>d</fullName>
                <default>true</default>
                <label>d</label>
            </value>
            <value>
                <fullName>w</fullName>
            </value>
            <value>
                <fullName>mo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/inspire1__Project_Tasks__c/fields/inspire1__Project__c.field-meta.xml
<CustomField>
    <fullName>inspire1__Project__c</fullName>
    <label>Project</label>
    <referenceTo>inspire1__Project__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Inspire_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/inspire1__Project_Tasks__c/fields/inspire1__RowNumber__c.field-meta.xml
<CustomField>
    <fullName>inspire1__RowNumber__c</fullName>
    <description>Row number of task.</description>
    <label>Row Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/inspire1__Project_Tasks__c/fields/inspire1__Status__c.field-meta.xml
<CustomField>
    <fullName>inspire1__Status__c</fullName>
    <description>Captures current status of task.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/inspire1__Project_Tasks__c/fields/inspire1__sysAssignedToIDs__c.field-meta.xml
<CustomField>
    <fullName>inspire1__sysAssignedToIDs__c</fullName>
    <description>Index field used to capture IDs of Assigned To resource and related Salesforce Task.</description>
    <label>sysAssignedToIDs</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/inspire1__Project_Tasks__c/fields/IsParent__c.field-meta.xml
<CustomField>
    <fullName>IsParent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsParent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/inspire1__Project_Tasks__c/fields/Lag__c.field-meta.xml
<CustomField>
    <fullName>Lag__c</fullName>
    <label>Lag (Days)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/inspire1__Project_Tasks__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <label>Parent</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/inspire1__Project_Tasks__c/fields/Schedule_Automation__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Automation__c</fullName>
    <formula>inspire1__Project__r.Schedule_Automation__c</formula>
    <label>Schedule Automation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/inspire1__Project_Tasks__c/fields/Task_Category__c.field-meta.xml
<CustomField>
    <fullName>Task_Category__c</fullName>
    <label>Task Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Certificate Decision</fullName>
            </value>
            <value>
                <fullName>Conduct Audit</fullName>
            </value>
            <value>
                <fullName>Final Invoice Sent</fullName>
            </value>
            <value>
                <fullName>Final Payment Received</fullName>
            </value>
            <value>
                <fullName>Initial Invoice Sent</fullName>
            </value>
            <value>
                <fullName>Initial Payment Received</fullName>
            </value>
            <value>
                <fullName>WO Sent</fullName>
            </value>
            <value>
                <fullName>WO Signed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Final_Invoice_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Final_Invoice_Payment_Date__c</fullName>
    <label>Final Invoice Payment Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Final_Invoice_Send_Date__c.field-meta.xml
<CustomField>
    <fullName>Final_Invoice_Send_Date__c</fullName>
    <label>Final Invoice Send Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Initial_Invoice_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Initial_Invoice_Payment_Date__c</fullName>
    <label>Initial Invoice Payment Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Initial_Invoice_Send_Date__c.field-meta.xml
<CustomField>
    <fullName>Initial_Invoice_Send_Date__c</fullName>
    <label>Initial Invoice Send Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Portuguese</fullName>
            </value>
            <value>
                <fullName>Japanese</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>Indonesian</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Programc__c.field-meta.xml
<CustomField>
    <fullName>Programc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>The selected program is deprecated, please select another program</errorMessage>
        <filterItems>
            <field>Program__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Deprecated</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Opportunity with or without products
Total Opportunity Amount</description>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/WO_Sent_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>WO_Sent_Date_Time__c</fullName>
    <label>WO Sent Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/WO_Signed_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>WO_Signed_Date_Time__c</fullName>
    <label>WO Signed Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/SCS_Global_QB_Entity__c.field-meta.xml
<CustomField>
    <fullName>SCS_Global_QB_Entity__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SCS Global (QB Entity)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Standard__c/Standard__c.object-meta.xml
<CustomObject>
    <label>Standard</label>
    <nameField>
        <label>Standard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standards</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Standard__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Portuguese</fullName>
            </value>
            <value>
                <fullName>Japanese</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>Indonesian</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Standard__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Standards</relationshipLabel>
    <relationshipName>Standards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SCS_ProjectTaskTrigger_Test.cls
/****************************************************New ORG CODE ***************************************************************** 
* Class  Name       : SCS_ProjectTaskTrigger_Test
* Division          : Food and Agriculture
* Version           : 1.1
* Code reviewed By  : N/A
* JIRA Ticket       : SF20FA-1420
* Functionality     : This test class .

* Modification Log  :
-------------------------------------------------------------------------------------------------------------------------------------------------
* Developer Name                     Date                                Description
* -----------------------------------------------------------------------------------------------------------------------------------------------
* Umesh Kumar                        11-04-2023                          Initial version
* Umesh Kumar                        30-05-2023                          modified for coi...
* Umesh Kumar                        22-06-2023                          modified for coi...
************************************************************************************************************************************/

@isTest
public class SCS_ProjectTaskTrigger_Test {
    //Setup data...
    @testSetup static void setup() {
        //Create Sales user...
        System.runAs(SCS_TestDataFactory.getWebIntegratorUser()){
            //Create Account...
            List<Account> accountList = SCS_TestDataFactory.createAccounts(SNM_TestConstant.customerAccRTId,1);
            accountList[0].BillingCountry= 'United States';
            insert accountList;
            
            //Create Contact...
            List<Contact> conList = SCS_TestDataFactory.createContacts(accountList[0].Id,SNM_TestConstant.auditorConRTId,1);
            conList[0].Auditor__c = true;
            insert conList;
            
            //Create Program...
            List<Program__c> proList = SCS_TestDataFactory.createPrograms(1);
            proList[0].name = 'SQF';
            proList[0].SCS_Global_QB_Entity__c = true;
            insert proList;
            
            //Create standard...
            List<Standard__c> standards = SCS_TestDataFactory.createStandard(proList[0].Id,1);
            standards[0].Language__c = 'English';
            insert standards;
            
            //Create Campaign...
            List<Campaign> campaign = SCS_TestDataFactory.createCampaing(1);
            insert campaign;
            
            //Create Opportunity...
            List<Opportunity> oppList = SCS_TestDataFactory.createOpportunity('Enquiry',accountList[0].Id,null,SNM_TestConstant.eCSOppoRTId ,System.today(),1);
            oppList[0].Type = 'New Business';
            oppList[0].TotalAmount__c = 1000;
            oppList[0].CampaignId  = campaign[0].Id;
            oppList[0].Programc__c = proList[0].Id;
            oppList[0].Language__c = 'English';
            oppList[0].WO_Sent_Date_Time__c  = System.today();
            oppList[0].WO_Signed_Date_Time__c  = System.today();
            oppList[0].Initial_Invoice_Send_Date__c  = System.today();
            oppList[0].Initial_Invoice_Payment_Date__c = System.today();
            oppList[0].Final_Invoice_Send_Date__c = System.today();
            oppList[0].Final_Invoice_Payment_Date__c = System.today();
            insert oppList;
            
            //Create Project...
            List<inspire1__Project__c> projects = SCS_TestDataFactory.createProject(accountList[0].Id, oppList[0].Id,1);
            projects[0].RecordTypeId = SNM_TestConstant.ecsRT_Project;
            projects[0].Program__c = proList[0].Id;
            projects[0].Schedule_Automation__c = true;
            insert projects;
            
            //Create Project Task...
            List<inspire1__Project_Tasks__c> projectTask = SCS_TestDataFactory.createProjectTask(projects[0].Id,7);
            projectTask[0].inspire1__RowNumber__c =1;
            projectTask[0].inspire1__sysAssignedToIDs__c ='005';
            projectTask[1].Task_Category__c = 'WO Signed';
            projectTask[1].Lag__c ='1';
            projectTask[2].Task_Category__c = 'Initial Invoice Sent';
            projectTask[2].Lag__c ='1';
            projectTask[3].Task_Category__c = 'Initial Payment Received';
            projectTask[3].Lag__c ='1';
            projectTask[4].Task_Category__c = 'Final Invoice Sent';
            projectTask[4].Lag__c ='1';
            projectTask[5].Task_Category__c = 'Final Payment Received';
            projectTask[5].Lag__c ='1';
            projectTask[5].inspire1__Duration__c =2;
            projectTask[5].inspire1__DurationUnit__c = 'd';
            projectTask[6].Task_Category__c = 'WO Sent';
            projectTask[6].Lag__c ='1';
            projectTask[6].inspire1__Duration__c =2;
            projectTask[6].inspire1__DurationUnit__c = 'd';
            insert projectTask;
            
            //Create COI ...
            List<Conflict_of_Interest__c> coiList = SCS_TestDataFactory.createCOI(conList[0].Id,accountList[0].Id,1);
            coiList[0].Program__c = proList[0].Id;
            insert coiList;
        }
        
    }
    
    @isTest static void testProjectTask() {
        Test.startTest();
        System.runAs(SCS_TestDataFactory.getWebIntegratorUser()){
             List<Contact> conList = [SELECT Id FROM Contact];
            
             List<inspire1__Project_Tasks__c> ptask =[SELECT Id,inspire1__RowNumber__c,inspire1__Status__c,IsParent__c,inspire1__sysAssignedToIDs__c FROM inspire1__Project_Tasks__c];
             ptask[0].inspire1__Status__c = 'Not Started';
             //ptask[0].IsParent__c = true;
             String rowNumber = String.valueOf(ptask[0].inspire1__RowNumber__c);
             system.debug('rowNUM'+ptask);
             ptask[1].Parent__c = rowNumber ;
             ptask[1].inspire1__Status__c = 'Not Started';
             ptask[2].Parent__c = rowNumber;
             ptask[2].inspire1__Status__c = 'Not Started';
             ptask[3].Parent__c = rowNumber;
             ptask[3].inspire1__sysAssignedToIDs__c = conList[0].Id;
             ptask[3].inspire1__Status__c = 'Not Started';
             ptask[4].Parent__c = rowNumber;
             ptask[4].inspire1__Status__c = 'Not Started';
             ptask[5].Parent__c = rowNumber;
             ptask[5].inspire1__Status__c = 'Not Started';
             ptask[6].Parent__c = rowNumber;
             ptask[6].inspire1__Status__c = 'Not Started';
             ptask[6].inspire1__sysAssignedToIDs__c ='005';
             update ptask;
            
            List<inspire1__Project_Tasks__c> parentTask =[SELECT Id,inspire1__Status__c,inspire1__sysAssignedToIDs__c FROM inspire1__Project_Tasks__c WHERE inspire1__RowNumber__c =1];
            parentTask[0].inspire1__Status__c ='Completed';
            parentTask[0].inspire1__sysAssignedToIDs__c = '';
            update parentTask;
            
            List<Opportunity> oppList =[SELECT Id,WO_Sent_Date_Time__c FROM Opportunity];
            oppList[0].WO_Sent_Date_Time__c  = System.today().adddays(2);
            update oppList;
            delete ptask;
            //Un-Delete record to cover delete event in trigger...
            undelete ptask;
            
        }
        Test.stopTest();  
    }
    
    
}