force-app/main/default/objects/Account/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Indonesian</fullName>
            </value>
            <value>
                <fullName>Japanese</fullName>
            </value>
            <value>
                <fullName>Local Language</fullName>
            </value>
            <value>
                <fullName>Portuguese</fullName>
            </value>
            <value>
                <fullName>Swahili</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Conflict_of_Interest__c/Conflict_of_Interest__c.object-meta.xml
<CustomObject>
    <label>Conflict of Interest</label>
    <nameField>
        <displayFormat>COI-{0000000}</displayFormat>
        <label>Conflict of Interest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conflict of Interests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Conflict_of_Interest__c/fields/Auditor__c.field-meta.xml
<CustomField>
    <fullName>Auditor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Auditor (External)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Auditor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Conflict of Interests</relationshipLabel>
    <relationshipName>Conflict_of_Interests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Conflict_of_Interest__c/fields/Auditor_Internal__c.field-meta.xml
<CustomField>
    <fullName>Auditor_Internal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>External Auditors is of type User in the system</inlineHelpText>
    <label>Auditor (Internal)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Conflict_of_Interests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Conflict_of_Interest__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Conflict of Interests</relationshipLabel>
    <relationshipName>Conflict_of_Interests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Auditor__c.field-meta.xml
<CustomField>
    <fullName>Auditor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auditor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/inspire1__Project__c/inspire1__Project__c.object-meta.xml
<CustomObject>
    <description>Inspire Planner - This object captures the detail of the project record</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/inspire1__Project_Tasks__c/inspire1__Project_Tasks__c.object-meta.xml
<CustomObject>
    <description>Inspire Planner - This object captures the tasks related to the project.</description>
    <label>Project Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/inspire1__Project_Tasks__c/fields/Has_Active_COI__c.field-meta.xml
<CustomField>
    <fullName>Has_Active_COI__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Active COI ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/inspire1__Project_Tasks__c/fields/inspire1__Project__c.field-meta.xml
<CustomField>
    <fullName>inspire1__Project__c</fullName>
    <label>Project</label>
    <referenceTo>inspire1__Project__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Inspire_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/inspire1__Project_Tasks__c/fields/inspire1__sysAssignedToIDs__c.field-meta.xml
<CustomField>
    <fullName>inspire1__sysAssignedToIDs__c</fullName>
    <description>Index field used to capture IDs of Assigned To resource and related Salesforce Task.</description>
    <label>sysAssignedToIDs</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Portuguese</fullName>
            </value>
            <value>
                <fullName>Japanese</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>Indonesian</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Programc__c.field-meta.xml
<CustomField>
    <fullName>Programc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>The selected program is deprecated, please select another program</errorMessage>
        <filterItems>
            <field>Program__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Deprecated</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Opportunity with or without products
Total Opportunity Amount</description>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/SCS_Global_QB_Entity__c.field-meta.xml
<CustomField>
    <fullName>SCS_Global_QB_Entity__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SCS Global (QB Entity)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SCS_COITrigger_Test.cls
/****************************************************New ORG CODE ***************************************************************** 
* Class  Name       : SCS_COITrigger_Test
* Division          : Food and Agriculture
* Version           : 1.1
* Code reviewed By  : N/A
* JIRA Ticket       : SF20FA-1312
* Functionality     : This test class .

* Modification Log  :
-------------------------------------------------------------------------------------------------------------------------------------------------
* Developer Name                     Date                                Description
* -----------------------------------------------------------------------------------------------------------------------------------------------
* Umesh Kumar                        22-06-2023                          Initial version
************************************************************************************************************************************/

@isTest
public class SCS_COITrigger_Test {
    //Setup data...
    @testSetup static void setup() {
        
        //Create Sales user...
        List<User> userList = SCS_TestDataFactory.createUser('System Administrator',1);
        userList[0].UserName ='sfdc@scsgs.com';
        insert userList;
        System.runAs(userList[0]){
            
            //Create Account...
            List<Account> accountList = SCS_TestDataFactory.createAccounts(SNM_TestConstant.customerAccRTId,1);
            accountList[0].BillingCountry= 'United States';
            insert accountList;
            
            //Create Contact...
            List<Contact> conList = SCS_TestDataFactory.createContacts(accountList[0].Id,SNM_TestConstant.auditorConRTId,1);
            conList[0].Auditor__c = true;
            insert conList;
            
            //Create Program...
            List<Program__c> proList = SCS_TestDataFactory.createPrograms(1);
            proList[0].name = 'SQF';
            proList[0].SCS_Global_QB_Entity__c = true;
            insert proList;
            
            //Create Campaign...
            List<Campaign> campaign = SCS_TestDataFactory.createCampaing(1);
            insert campaign;
            
            //Create Opportunity...
            List<Opportunity> oppList = SCS_TestDataFactory.createOpportunity('Enquiry',accountList[0].Id,null,SNM_TestConstant.eCSOppoRTId ,System.today(),1);
            oppList[0].Type = 'New Business';
            oppList[0].TotalAmount__c = 1000;
            oppList[0].CampaignId  = campaign[0].Id;
            oppList[0].Programc__c = proList[0].Id;
            oppList[0].Language__c = 'English';
            insert oppList;
            
            //Create Project...
            List<inspire1__Project__c> projects = SCS_TestDataFactory.createProject(accountList[0].Id, oppList[0].Id,1);
            projects[0].RecordTypeId = SNM_TestConstant.ecsRT_Project;
            projects[0].Program__c = proList[0].Id;
            insert projects;
            
            //Create Project Task...
            List<inspire1__Project_Tasks__c> projectTask = SCS_TestDataFactory.createProjectTask(projects[0].Id,2);
            projectTask[0].inspire1__sysAssignedToIDs__c =  conList[0].Id;
            projectTask[1].inspire1__sysAssignedToIDs__c =  userList[0].Id;
            insert projectTask;
            
            //Create salesforce task...
            List<Task> tskList = SCS_TestDataFactory.createSFTask(conList[0].Id, userList[0].Id,2);
            tskList[0].inspire1__Inspire_Task__c = projectTask[0].Id;
            tskList[1].inspire1__Inspire_Task__c = projectTask[1].Id;
            insert tskList;
            
            //Create COI...
            List<Conflict_of_Interest__c> coiList = SCS_TestDataFactory.createCOI(conList[0].Id,accountList[0].Id,2);
            coiList[0].Program__c = proList[0].Id;
            coiList[1].Program__c = proList[0].Id;
            coiList[1].Auditor__c = null;
            coiList[1].Auditor_Internal__c = userList[0].Id;
            insert coiList;
        }
        
    }
    
    @isTest static void testCOI() {
        Test.startTest();
        List<User> userList = [SELECT Id,UserName FROM User WHERE UserName = 'sfdc@scsgs.com'];
        
        System.runAs(userList[0]){
             List<Contact> conList = [SELECT Id FROM Contact];
            
             Date dt = System.today();
             List<Conflict_of_Interest__c> coi =[SELECT Id,EndDate__c FROM Conflict_of_Interest__c];
             coi[0].EndDate__c = dt.addDays(10);
             coi[1].EndDate__c = dt.addDays(10);
             update coi;
            
            delete coi;
            //Un-Delete record to cover delete event in trigger...
            undelete coi;
            List<inspire1__Project_Tasks__c> ptask =[SELECT Id FROM inspire1__Project_Tasks__c WHERE Has_Active_COI__c = true];
            System.assertEquals(2,ptask.size(),'Task count should be same');
        }
        Test.stopTest();  
    }
    
    
}