force-app/main/default/objects/Account/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Indonesian</fullName>
            </value>
            <value>
                <fullName>Japanese</fullName>
            </value>
            <value>
                <fullName>Local Language</fullName>
            </value>
            <value>
                <fullName>Portuguese</fullName>
            </value>
            <value>
                <fullName>Swahili</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>SCS Global Services departments</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Goal__c/Goal__c.object-meta.xml
<CustomObject>
    <label>Goal</label>
    <nameField>
        <displayFormat>G-{00000}</displayFormat>
        <label>Goal Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Goal__c/fields/Program_Goal__c.field-meta.xml
<CustomField>
    <fullName>Program_Goal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Goal</label>
    <referenceTo>Goal__c</referenceTo>
    <relationshipLabel>User Goals</relationshipLabel>
    <relationshipName>Goals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Programc__c.field-meta.xml
<CustomField>
    <fullName>Programc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Goals</relationshipLabel>
    <relationshipName>Goals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Goal__c/recordTypes/Program_Goal.recordType-meta.xml
<RecordType>
    <fullName>Program_Goal</fullName>
    <active>true</active>
    <label>Program Goal</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Bundle_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Bundle_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bundle Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>Bundle Opportunity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Portuguese</fullName>
            </value>
            <value>
                <fullName>Japanese</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>Indonesian</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Program_Goal__c.field-meta.xml
<CustomField>
    <fullName>Program_Goal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Goal</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Goal__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Program_Goal</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Goal__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Programc__c.field-meta.xml
<CustomField>
    <fullName>Programc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>The selected program is deprecated, please select another program</errorMessage>
        <filterItems>
            <field>Program__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Deprecated</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Opportunity with or without products
Total Opportunity Amount</description>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/User_Goal__c.field-meta.xml
<CustomField>
    <fullName>User_Goal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Goal</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Goal__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>User_Goal</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Goal__c</referenceTo>
    <relationshipLabel>Opportunities (User Goal)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Bundle_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Bundle_Opportunity</fullName>
    <active>true</active>
    <businessProcess>SCS Global Services Sales Process</businessProcess>
    <label>Bundle Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/ECS.recordType-meta.xml
<RecordType>
    <fullName>ECS</fullName>
    <active>true</active>
    <businessProcess>SCS Global Services Sales Process</businessProcess>
    <label>ECS</label>
</RecordType>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/SCS_Global_QB_Entity__c.field-meta.xml
<CustomField>
    <fullName>SCS_Global_QB_Entity__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SCS Global (QB Entity)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Standard__c/Standard__c.object-meta.xml
<CustomObject>
    <label>Standard</label>
    <nameField>
        <label>Standard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standards</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Standard__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Portuguese</fullName>
            </value>
            <value>
                <fullName>Japanese</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>Indonesian</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Standard__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Standards</relationshipLabel>
    <relationshipName>Standards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SCS_OpportunityTriggerTest.cls
/*
@Author : MAANTIC
@CreatedDate : 27th SEP 2022
@Description : This test class for SCS_OpportunityTrigger trigger.
*/
/****************************** New ORG CODE *****************************************************/

@isTest
public class SCS_OpportunityTriggerTest {
    //Setup data...
    @testSetup static void setup() {
        //Create Sales user...
        Id accRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Customer').getRecordTypeId();
        Id oppRTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('ECS').getRecordTypeId();
        Id programGoalId = Schema.SObjectType.Goal__c.getRecordTypeInfosByDeveloperName().get('Program_Goal').getRecordTypeId();
        Id bundelOppRTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Bundle_Opportunity').getRecordTypeId();
        System.runAs( SCS_TestDataFactory.getWebIntegratorUser()){
            //Set Mock response...
            Test.setMock(HttpCalloutMock.class, new SCS_DataSyncMock()); 
            //Create record...
            List<Account> accountList = SCS_TestDataFactory.createAccounts(accRTId,1);
            accountList[0].BillingCountry= 'United States';
            insert accountList;
            
            List<Program__c> proList = SCS_TestDataFactory.createPrograms(2);
            proList[0].name = 'SQF';
            proList[0].SCS_Global_QB_Entity__c = true;
            proList[1].name = 'BRCGS';
            proList[1].SCS_Global_QB_Entity__c = true;
            insert proList; 
            //Create standard...
            List<Standard__c> standards = SCS_TestDataFactory.createStandard(proList[0].Id,1);
            standards[0].Language__c = 'English';
            insert standards;
            List<Campaign> campaign = SCS_TestDataFactory.createCampaing(1);
            insert campaign;
            List<Goal__c> goalList = SCS_TestDataFactory.createGoalRecord(programGoalId,proList[0].id,'Q1','2025',1);  
            insert goalList;
            List<Opportunity> oppList = SCS_TestDataFactory.createOpportunity('Enquiry',accountList[0].Id,null, bundelOppRTId ,Date.newInstance(2025,1,5),3);
            oppList[0].Name = 'New Business-';
            oppList[0].Type = 'New Business';
            oppList[0].TotalAmount__c = 1000;
            oppList[0].CampaignId  = campaign[0].Id;
            oppList[0].RecordTypeId = oppRTId;
            oppList[0].Programc__c = proList[0].Id;
            oppList[0].Language__c = 'English';
            oppList[0].NextStep ='ECS';
            oppList[1].Type = 'New Business';
            oppList[1].TotalAmount__c = 1000;
            oppList[1].CampaignId = campaign[0].Id;
            oppList[1].NextStep ='BUNDLE';
            oppList[2].Type = 'New Business';
            oppList[2].TotalAmount__c = 1000;
            oppList[2].CampaignId = campaign[0].Id;
            oppList[2].NextStep ='BUNDLE';
            insert oppList;
        }
        
    }
    
    @isTest static void testOpportunityGoal() {
        Test.startTest();
        System.runAs(SCS_TestDataFactory.getWebIntegratorUser()){
            //Set mock response...
            Test.setMock(HttpCalloutMock.class, new SCS_DataSyncMock()); 
            //Get Campaign ...
            List<User> ownr = SCS_TestDataFactory.createUser('Sales User',1);
            ownr[0].Username='scssu.testoppogoal@gmail.com';
            insert ownr;
            List<Opportunity> recordList =[SELECT Id,Type,TotalAmount__c,Program_Goal__c FROM Opportunity WHERE NextStep ='ECS'];
            recordList[0].Type ='Existing Business';
            recordList[0].TotalAmount__c = 2000;
            recordList[0].Program_Goal__c = null;
            update recordList;
            List<Opportunity> recordList1 =[SELECT Id,User_Goal__c FROM Opportunity WHERE NextStep ='ECS'];
            recordList1[0].User_Goal__c = null;
            update recordList1;
            List<Program__c> program =[SELECT Id,Name FROM Program__c WHERE name = 'BRCGS'];
            List<Opportunity> recordList2 =[SELECT Id,User_Goal__c,Program_Goal__c FROM Opportunity WHERE NextStep ='ECS'];
            recordList2[0].User_Goal__c = null;
            recordList2[0].Program_Goal__c = null;
            update recordList2;
            List<Opportunity> recordList3 =[SELECT Id,StageName FROM Opportunity WHERE NextStep ='ECS'];
            recordList3[0].StageName = 'Closed Won';
            update recordList3;
            List<Opportunity> recordList4 =[SELECT Id,Programc__c FROM Opportunity WHERE NextStep ='ECS'];
            recordList4[0].Programc__c = program[0].Id;
            update recordList4;
            List<Opportunity> recordList5 =[SELECT Id,OwnerId FROM Opportunity WHERE NextStep ='ECS'];
            recordList5[0].OwnerId = ownr[0].Id;
            update recordList5;
            List<Opportunity> recordList6 =[SELECT Id,Type FROM Opportunity WHERE NextStep ='ECS'];
            recordList6[0].Type ='New Business';
            update recordList6;
            List<Opportunity> recordList7 =[SELECT Id,StageName FROM Opportunity WHERE NextStep ='ECS'];
            recordList7[0].StageName = 'Closed Won';
            update recordList7;
            List<Opportunity> bundleList =[SELECT Id,Name,StageName,Bundle_Opportunity__c,Record_Type_Name__c FROM Opportunity WHERE NextStep ='BUNDLE'];
            //system.debug('bundleList :'+bundleList);
            bundleList[0].Bundle_Opportunity__c = bundleList[1].Id;
            update bundleList;
            //Delete record to cover delete event in trigger...
            delete recordList;
            //Un-Delete record to cover delete event in trigger...
            undelete recordList;
            
        }
        Test.stopTest();  
    }
    
    
    
    
    public class SCS_DataSyncMock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest request) {
            HttpResponse response = new HttpResponse();
            response.setHeader('Content-Type', 'application/json');
            response.setBody('{"id":"SCSTESTId","success":true,"errors":[],"created":true}');
            response.setStatusCode(201);
            return response; 
        }
    }
    
    
}