force-app/main/default/objects/Account/fields/SharePoint_Folder_Id__c.field-meta.xml
<CustomField>
    <fullName>SharePoint_Folder_Id__c</fullName>
    <label>SGS SharePoint Folder Id</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/inspire1__Project__c/inspire1__Project__c.object-meta.xml
<CustomObject>
    <description>Inspire Planner - This object captures the detail of the project record</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/inspire1__Project__c/fields/SharePoint_Folder_Id__c.field-meta.xml
<CustomField>
    <fullName>SharePoint_Folder_Id__c</fullName>
    <description>Field that holds SharePoint&apos;s folder Id.</description>
    <label>SharePoint Folder Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/fileforcem1__Sharepoint_Folder_Id__c.field-meta.xml
<CustomField>
    <fullName>fileforcem1__Sharepoint_Folder_Id__c</fullName>
    <description>Field that holds SharePoint&apos;s folder Id.</description>
    <inlineHelpText>Field that holds SharePoint&apos;s folder Id.</inlineHelpText>
    <label>SharePoint Folder Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Certificate__c/Opportunity_Certificate__c.object-meta.xml
<CustomObject>
    <label>Opportunity Certificate</label>
    <nameField>
        <displayFormat>OC-{0000}</displayFormat>
        <label>Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Certificates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Certificate__c/fields/SharePoint_Folder_Id__c.field-meta.xml
<CustomField>
    <fullName>SharePoint_Folder_Id__c</fullName>
    <label>SharePoint Folder Id</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/sFilesBatchtoUploadFiles.cls
/************************************************************************************************************************************************
Apex Class Name : sFilesBatchtoUploadFiles
Version         : 1.0
Created Date    : 
Modification Log:
Test Class		: sFilesBatchtoUploadFilesTest
-------------------------------------------------------------------------------------------------------------------------------------------------
* Developer                                 Date                                Description
* -----------------------------------------------------------------------------------------------------------------------------------------------
Sohit Tripathi                          19/01/2023                            Initial version
Note: Need to add the query in "File_Upload_Batch_Query" custom label one by one before running the batch class. 
//String query = 'SELECT Id, Name, fileforcem1__Sharepoint_Folder_Id__c FROM Opportunity WHERE fileforcem1__Sharepoint_Folder_Id__c != null';
//String query = 'SELECT Id, Name, SharePoint_Folder_Id__c FROM inspire1__Project__c WHERE SharePoint_Folder_Id__c != null';
//String query = 'SELECT Id, Name, SharePoint_Folder_Id__c FROM Account WHERE SharePoint_Folder_Id__c != null';
//String query = 'SELECT Id, Name, SharePoint_Folder_Id__c FROM Opportunity_Certificate__c WHERE SharePoint_Folder_Id__c != null';
**************************************************************************************************************************************************/
global class sFilesBatchtoUploadFiles implements Database.Batchable<SObject>,Database.AllowsCallouts, Database.Stateful{
    public String objectName;
    global database.querylocator start(database.batchableContext bc){
        String query;
        if(!Test.isRunningTest()){
            query = Label.File_Upload_Batch_Query;
        }else if(objectName == 'Opportunity'){
            query = 'SELECT Id, Name, fileforcem1__Sharepoint_Folder_Id__c FROM Opportunity WHERE fileforcem1__Sharepoint_Folder_Id__c != null';
        }
        else if(objectName == 'Project'){
            query = 'SELECT Id, Name, SharePoint_Folder_Id__c FROM inspire1__Project__c WHERE SharePoint_Folder_Id__c != null';
        }
        else if(objectName == 'Opportunity Certificate'){
            query = 'SELECT Id, Name, SharePoint_Folder_Id__c FROM Opportunity_Certificate__c WHERE SharePoint_Folder_Id__c != null';
        }
        else{
            query = 'SELECT Id, Name, SharePoint_Folder_Id__c FROM Account WHERE SharePoint_Folder_Id__c != null';
        }
        return Database.getQueryLocator(query);
	}
    
    global void execute(database.batchableContext bc, List<sObject> sObjList){
		Set<Id> recIdSet = new Set<Id>();
        List<SObject> sObjRecordList = new List<SObject>();
        String strObjPrefix = String.valueOf(sObjList[0].Id).substring(0, 3);
        for(SObject obj : sObjList){
            sObjRecordList.add(obj);
            recIdSet.add(obj.Id);
        }
        
        if(!recIdSet.isEmpty()){
            List<ContentDocumentLink> conDocLinkList = [SELECT Id, LinkedEntityId, ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId IN:recIdSet];
            
            if(!conDocLinkList.isEmpty()){
                System.enqueuejob(new sFilesBatchQueabletoUploadFiles(conDocLinkList, sObjRecordList));
            }
        }
	}
    
    global void finish(database.batchableContext bc){
        
	}
    
    
}