force-app/main/default/objects/Certificate__c/Certificate__c.object-meta.xml
<CustomObject>
    <description>Certificate issued to Client</description>
    <label>Certificate</label>
    <nameField>
        <displayFormat>CRT-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certificates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certificate__c/fields/ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>ValidFrom__c</fullName>
    <label>Valid From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User/fields/External_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Record_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Record Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SCS_CertificateTrigger_Test.cls
/*
    Description : Test Class for SCS_CertificateTrigger, SCS_CertificateTrHandler
    Author      : Utkarsh Goswami(Maantic)
    Date        : 23nd September, 2022

    Please add @Revisions below
*/
@isTest
public with sharing class SCS_CertificateTrigger_Test {
    
    
    @TestSetup
    static void makeData(){
     
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorClass());

        List<Certificate__c> certList = SCS_TestDataFactory.createCertificate(1);
        insert certList;

    }
   
    /*
        Method to check trigger handler scenario
        Refrenced - MockHttpResponseGenerator class to provide fake response for callout
        Checked all the scenarios here to avoid multiple data creating(As callout is on trigger)
    */
    static testMethod void triggerHandlerTest(){


        List<User> integratorUser = SCS_TestDataFactory.createUsers(SCS_TestDataFactory.getSystemIntegratorProfile(), 1);
        
        System.runAs(integratorUser[0]){
            
            Test.startTest();

                Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorClass());
                List<Certificate__c> certList = [SELECT Id, Name, External_Record_Id__c FROM Certificate__c WHERE CreatedDate = TODAY LIMIT 1];
        
                //checking update scenario
                certList[0].ValidFrom__c = Date.Today().addDays(10);
                update certList[0];

            Test.stopTest();

            System.assertEquals('external-Id', certList[0].External_Record_Id__c);

            //deleting the product to cover trigger delete
            delete certList;
        }

    }

}