force-app/main/default/objects/Certificate__c/Certificate__c.object-meta.xml
<CustomObject>
    <description>Certificate issued to Client</description>
    <label>Certificate</label>
    <nameField>
        <displayFormat>CRT-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certificates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certificate__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Certificates</relationshipLabel>
    <relationshipName>Certificates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Certificate__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Certificates</relationshipLabel>
    <relationshipName>Certificates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Certificate__c/fields/Scheme_Certification_Number__c.field-meta.xml
<CustomField>
    <fullName>Scheme_Certification_Number__c</fullName>
    <label>Scheme Certification Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Certificate__c/fields/SCS_Certification_Number__c.field-meta.xml
<CustomField>
    <fullName>SCS_Certification_Number__c</fullName>
    <label>SCS Certification Number</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Certificate__c/fields/ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>ValidFrom__c</fullName>
    <label>Valid From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/inspire1__Project__c/inspire1__Project__c.object-meta.xml
<CustomObject>
    <description>Inspire Planner - This object captures the detail of the project record</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/inspire1__Project__c/fields/inspire1__Opportunity1__c.field-meta.xml
<CustomField>
    <fullName>inspire1__Opportunity1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity related to Project.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Affiliate_Opportunity_flag__c.field-meta.xml
<CustomField>
    <fullName>Affiliate_Opportunity_flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Affiliate Opportunity flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Programc__c.field-meta.xml
<CustomField>
    <fullName>Programc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>The selected program is deprecated, please select another program</errorMessage>
        <filterItems>
            <field>Program__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Deprecated</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Certificate__c/Opportunity_Certificate__c.object-meta.xml
<CustomObject>
    <label>Opportunity Certificate</label>
    <nameField>
        <displayFormat>OC-{0000}</displayFormat>
        <label>Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Certificates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Certificate__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunity Certificates</relationshipLabel>
    <relationshipName>Opportunity_Certificates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Certificate__c/fields/Certificate__c.field-meta.xml
<CustomField>
    <fullName>Certificate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Certificate</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Certificate__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Certificate__c</referenceTo>
    <relationshipLabel>Opportunity Certificates</relationshipLabel>
    <relationshipName>Opportunity_Certificates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/SCSGlobal_CreateCertificateHelper.cls
public with sharing class SCSGlobal_CreateCertificateHelper 
{   /*
    @AuraEnabled
    public static List<Certificate__c> getCertificateFromOpportunity(String opptyId)
    {
        Opportunity oppty=[SELECT AccountId, Programc__c FROM Opportunity WHERE Id=:opptyId LIMIT 1];
        return [SELECT Id,Name,Scheme_Certification_Number__c,SCS_Certification_Number__c,
                ValidFrom__c FROM Certificate__c WHERE Account__c =:oppty.AccountId AND Program__c =:oppty.Programc__c];
    }*/
     @AuraEnabled
     public static String getCertificateFromOpportunity(Integer pageSize, Integer pageNumber,String oppId){
        String jsonResult = '';
        //Offset for SOQL
        Integer offset = (pageNumber - 1) * pageSize;
        Opportunity opportunityRecord =[SELECT AccountId, Programc__c FROM Opportunity WHERE Id=:oppId LIMIT 1];
        //Total Records
		Integer totalRecords = [SELECT COUNT() FROM Certificate__c WHERE Account__c =:opportunityRecord.AccountId AND Program__c =:opportunityRecord.Programc__c];
        Integer recordEnd = pageSize * pageNumber;
        CertificateWrapper wrapperRecord =  new CertificateWrapper();  
        wrapperRecord.pageSize = pageSize;
        wrapperRecord.pageNumber = pageNumber;
        wrapperRecord.recordStart = offset + 1;
        wrapperRecord.recordEnd = totalRecords >= recordEnd ? recordEnd : totalRecords;
        wrapperRecord.totalRecords = totalRecords;
        wrapperRecord.certificates = [SELECT Id,Name,Scheme_Certification_Number__c,SCS_Certification_Number__c,ValidFrom__c FROM Certificate__c WHERE Account__c =:opportunityRecord.AccountId AND Program__c =:opportunityRecord.Programc__c Order By Name DESC LIMIT :pageSize OFFSET :offset];
        jsonResult = JSON.serialize(wrapperRecord);
        return jsonResult;
    }
    
    public class CertificateWrapper {
        public Integer pageSize {get;set;}
        public Integer pageNumber {get;set;}
        public Integer totalRecords {get;set;}
        public Integer recordStart {get;set;}
        public Integer recordEnd {get;set;}
        public List<Certificate__c> certificates {get;set;}
    }
    
    @AuraEnabled
    public static Map<String, String> getFieldsListFromFieldSet(String fieldSetName)
    {
        Map<String, String> returnMap = new Map<String, String>();
        fieldSetName=fieldSetName.replaceAll('\\W+', '_');
        System.debug(fieldSetName);
        
        //get fields from FieldSet
        SObject sObj = (SObject)(Type.forName('Schema.Opportunity_Certificate__c')?.newInstance());
        List<Schema.FieldSetMember> lstFSMember = 
            sObj?.getSObjectType()?.getDescribe()?.fieldSets.getMap().get(fieldSetName)?.getFields();
        
        returnMap.put('FIELD_LIST',JSON.serialize(lstFSMember));
        returnMap.put('OBJECT_LABEL', sObj?.getSObjectType()?.getDescribe()?.getLabel());
        System.debug(returnMap);
        return returnMap;
    }
    
    @AuraEnabled
    public static Map<String, String> getCertificateFieldsfromFieldSet(String fieldSetName){
        Map<String, String> returnMap = new Map<String, String>();
        fieldSetName=fieldSetName.replaceAll('\\W+', '_');
        System.debug(fieldSetName);
        
        //get fields from FieldSet
        SObject sObj = (SObject)(Type.forName('Schema.Certificate__c')?.newInstance());
        List<Schema.FieldSetMember> lstFSMember = 
            sObj?.getSObjectType()?.getDescribe()?.fieldSets.getMap().get(fieldSetName)?.getFields();
        
        returnMap.put('FIELD_LIST',JSON.serialize(lstFSMember));
        returnMap.put('OBJECT_LABEL', sObj?.getSObjectType()?.getDescribe()?.getLabel());
        System.debug(returnMap);
        return returnMap;
    }
    
    @AuraEnabled
    public static String createCertificateAndOC(Certificate__c cert, Opportunity_Certificate__c oppCert, String existingCertId){
        System.debug('Sohit-cert---'+cert);
        System.debug('Sohit-oppCert---'+oppCert);
        if(cert != null){
            try{
                insert cert;
            }
            catch (Exception e) {
                String errorMsg = e.getMessage();
                if(!Test.isRunningTest())
                    throw new AuraHandledException(errorMsg);
                
            }
        }
        
        if(oppCert != null){
            oppCert.Certificate__c = String.isNotBlank(existingCertId) ? existingCertId :cert.Id;
            try{
                insert oppCert;
                return oppCert.Id;
            }
            catch (Exception e) {
                String errorMsg = e.getMessage();
                throw new AuraHandledException(errorMsg);
            }
        }
        else{
            return null;
        }
    }
    
    @AuraEnabled
    public static Boolean checkProjectExist(String oppId)
    { 
        if(string.isNotBlank(oppId)){
            List<Opportunity> oppList = [Select id,name,Affiliate_Opportunity_flag__c from Opportunity where id=:oppId];    
            if( oppList[0].Affiliate_Opportunity_flag__c ){
                return true;
            }else{
                List<inspire1__Project__c> projList = [SELECT Id FROM inspire1__Project__c WHERE inspire1__Opportunity1__c =: oppId];
                return projList.size() > 0;
            }
        }
        return false;        
    }
    
}