force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Scope__c/Scope__c.object-meta.xml
<CustomObject>
    <description>Program / Project Scope</description>
    <label>Scope</label>
    <nameField>
        <displayFormat>SC-{0000000}</displayFormat>
        <label>Scope #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scope</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scope__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Scope</relationshipLabel>
    <relationshipName>Scope</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scope__c/fields/Sub_Scope__c.field-meta.xml
<CustomField>
    <fullName>Sub_Scope__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Scope</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>$Source.Program__c</field>
            <operation>equals</operation>
            <valueField>Scope__c.Program__c</valueField>
        </filterItems>
        <filterItems>
            <field>Scope__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sub Scope</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Scope__c</referenceTo>
    <relationshipLabel>Scope</relationshipLabel>
    <relationshipName>SubScope</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FnA_ScopeTriggerHandlerTest.cls
/**************************************************** OLD ORG CODE ****************************************************************************************************************
* Apex Class Name   : FnA_ScopeTriggerHandlerTest
* Related Class Name: FnA_ScopeTriggerHandler
* Version           : 1.0
* Functionality     : This is Test class to cover FnA_ScopeTrigger, FnA_ScopeTriggerHandler, SCS_ConstantRTypeReference
*/
@isTest
public class FnA_ScopeTriggerHandlerTest {
	//Setup data...
    @testSetup static void setup() {     
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorClass()); 
        
        List<Program__c> proList = SCS_TestDataFactory.createPrograms(1);        
        insert proList; 
        
        List<Scope__c> scopeList = SCS_TestDataFactory.createScope(2); 
        scopeList[0].Program__c = proList[0].Id;
        scopeList[0].RecordTypeId = SCS_ConstantRTypeReference.scope_SubScopeRTId;
        scopeList[1].RecordTypeId = SCS_ConstantRTypeReference.scope_opportunityRTId;
        scopeList[1].Program__c = proList[0].Id;
        insert scopeList; 
    }
    
    @isTest static void testInvoiceLine() {
        Test.startTest();        
        //Set Mock response...
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorClass()); 
        //Get records ...
        List<Scope__c> recordList =[SELECT Id, Name FROM Scope__c];
        recordList[1].Sub_Scope__c = recordList[0].Id;
        //Update records...
        update recordList;        
        Test.stopTest();  
        delete recordList;
    }
}