force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Contact_Role__c/Program_Contact_Role__c.object-meta.xml
<CustomObject>
    <label>Program Contact Role</label>
    <nameField>
        <displayFormat>PCR-{000}</displayFormat>
        <label>Program Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Contact_Role__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <formula>Contact__r.Account.Name</formula>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Program_Contact_Role__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Active_Flag__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Contact Roles</relationshipLabel>
    <relationshipName>Program_Contact_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Contact_Role__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Contact Roles</relationshipLabel>
    <relationshipName>Program_Contact_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Contact_Role__c/fields/Program_Role__c.field-meta.xml
<CustomField>
    <fullName>Program_Role__c</fullName>
    <label>Program Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProgramContactRole.cls
/*
    Description :   Class to query show the Program Contact Role Data used in programContactRole LWC
    Author      :   Utkarsh Goswami
    Date        :   9th Aug, 2023
*/

public class ProgramContactRole {

    @AuraEnabled(cacheable=true)
    public static List<ProgramContactRoleWrapper> getProgramContactRoleData(String programId, String accountId){
   // public static List<ProgramContactRoleWrapper> getProgramContactRoleData(){

        List<ProgramContactRoleWrapper> pcrList = new List<ProgramContactRoleWrapper>();
        ProgramContactRoleWrapper pcrObject = new ProgramContactRoleWrapper();
        
        for(Program_Contact_Role__c pr : [Select Id,Program__r.Name,Program_Role__c, AccountName__c, Contact__r.AccountId, Program__c,
                                            Contact__r.firstName, Contact__r.LastName, Contact__r.Title,
                                            Contact__r.Phone, Contact__r.Fax, Contact__r.Email, Contact__r.MobilePhone from Program_Contact_Role__c
                                            where Program__c = :programId and Contact__r.AccountId = :accountId]){
            pcrObject = new ProgramContactRoleWrapper();

            pcrObject.program = pr.Program__r.Name;                                
            pcrObject.accountName = pr.AccountName__c;                          
            pcrObject.firstName = pr.Contact__r.firstName;                              
            pcrObject.lastName = pr.Contact__r.LastName;                              
            pcrObject.title = pr.Contact__r.Title;                                
            pcrObject.phone = pr.Contact__r.Phone;                                 
            pcrObject.fax = pr.Contact__r.Fax;                                 
            pcrObject.email = pr.Contact__r.Email;                                
            pcrObject.mobile = pr.Contact__r.MobilePhone;                               
            pcrObject.programRole = pr.Program_Role__c;                               
            pcrObject.recordId = pr.Id;                               
            pcrObject.accountId = pr.Contact__r.AccountId;                               
            pcrObject.progrId = pr.Program__c;                               


            pcrList.add(pcrObject);
        }

        return pcrList;
    }


    Public Class ProgramContactRoleWrapper {

        @AuraEnabled
        public String program;
        @AuraEnabled
        public String accountName;
        @AuraEnabled
        public String firstName;
        @AuraEnabled
        public String lastName;
        @AuraEnabled
        public String title;
        @AuraEnabled
        public String phone;
        @AuraEnabled
        public String fax;
        @AuraEnabled
        public String email;
        @AuraEnabled
        public String mobile;
        @AuraEnabled
        public String programRole;
        @AuraEnabled
        public String recordId;
        @AuraEnabled
        public String accountId;
        @AuraEnabled
        public String progrId;

    }
}