force-app/main/default/objects/Lead/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Program__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Deprecated</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Recent_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Recent_Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recent Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/SCS_Global_Services.recordType-meta.xml
<RecordType>
    <fullName>SCS_Global_Services</fullName>
    <active>true</active>
    <businessProcess>SCS Standard Lead Process</businessProcess>
    <label>SCS Global Services</label>
</RecordType>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/External_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Record_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Record Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/External_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Record_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Record Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/LeadGenericTriggerHelper_Test.cls
/*
    Description : Test Class for LeadTriggerGeneric, LeadGenericTrigger
    Author      : Utkarsh Goswami(Maantic)
    Date        : 22nd September, 2022

    Please add @Revisions below
*/
@isTest
public with sharing class LeadGenericTriggerHelper_Test {

    @TestSetup
    static void makeData(){

        Id leadRT_Id = Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName().get('SCS_Global_Services').getRecordTypeId();
     
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorClass());

        List<Campaign> campList = SCS_TestDataFactory.createCampaing(1);
        insert campList;

        List<Program__c> programList = SCS_TestDataFactory.createPrograms(5);
        insert programList;

        List<Lead> ldList = SCS_TestDataFactory.createLead(1, 'New', leadRT_Id);
        for(Lead ln:ldList)
        {
            ln.LeadSource = 'Website';
        	ln.Recent_Campaign__c = campList[0].Id;
        	ln.program__c = programList[0].Id;
            
        }
        //ldList[2].LeadSource = 'Other';
        System.debug('*************MAIN LEAD' + ldList);
        insert ldList;
        //System.debug('*************' + ldList[0]);
        
    }

    /*
        Method to check trigger handler scenario
        Refrenced - MockHttpResponseGenerator class to provide fake response for callout
        Checked all the scenarios here to avoid multiple data creating(As callout is on trigger)
    */
    static testMethod void triggerHandlerTest(){

        List<User> integratorUser = SCS_TestDataFactory.createUsers(SCS_TestDataFactory.getSystemIntegratorProfile(), 1);
        String prevEmail = '';
        System.runAs(integratorUser[0]){
            
            Test.startTest();

                Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorClass());
                
                List<Lead> pb = [SELECT Id, Name,Email,program__c,External_Record_Id__c,leadsource FROM Lead WHERE CreatedDate = Today LIMIT 1];
                List<Program__c> prog = [SELECT Id,  External_Record_Id__c FROM Program__c WHERE CreatedDate = Today LIMIT 2];
        
                //checking update scenario
                pb[0].LeadSource = 'Website';
                pb[0].Program__c = prog[1].Id;
               

                prevEmail = pb[0].Email;

                update pb;

            Test.stopTest();

            //System.assertEquals(prevEmail, pb[0].Email);

            //deleting the product to cover trigger delete
            //delete pb;
        }

    }
    
}