force-app/main/default/objects/Lead/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Program__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Deprecated</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Recent_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Recent_Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recent Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/SCS_Global_Services.recordType-meta.xml
<RecordType>
    <fullName>SCS_Global_Services</fullName>
    <active>true</active>
    <businessProcess>SCS Standard Lead Process</businessProcess>
    <label>SCS Global Services</label>
</RecordType>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/External_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Record_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Record Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/External_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Record_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Record Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/EE_ChatterFeed_Test.cls
@isTest
private class EE_ChatterFeed_Test {
    @TestSetup
    static void testSetupData() { 
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorClass());
        
        Id leadRT_Id = Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName().get('SCS_Global_Services').getRecordTypeId();
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorClass());
        
        List<Campaign> campList = SCS_TestDataFactory.createCampaing(1);
        insert campList;
        
        List<Program__c> programList = SCS_TestDataFactory.createPrograms(1);
        insert programList;
        
        List<Lead> ldList = SCS_TestDataFactory.createLead(1, 'New', leadRT_Id);
        for(Lead ln:ldList)
        {
            ln.LeadSource = 'Website';
            ln.Recent_Campaign__c = campList[0].Id;
            ln.program__c = programList[0].Id;
            
        }
        insert ldList;   
    }
    
    static testMethod void triggerHandlerTest(){
        
        List<User> integratorUser = SCS_TestDataFactory.createUsers(SCS_TestDataFactory.getSystemIntegratorProfile(), 1);
        String prevEmail = '';
        System.runAs(integratorUser[0]){            
            Test.startTest();
            SCS_ChatterFeedHelper.isTest = true;
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorClass());                
            List<Lead> ldList = [SELECT Id, Name,Email,program__c,External_Record_Id__c,leadsource FROM Lead WHERE CreatedDate = Today LIMIT 1];          
            FeedItem f = new FeedItem();
            f.body = '@SFDC Support';
            f.ParentId = ldList[0].Id;
            insert f;
            
            FeedComment fComm = new FeedComment();
            fComm.CommentBody = '#resolved';
            fComm.FeedItemId = f.Id;
            insert fComm;
            
            fComm.CommentBody = '#reopened';
            update fComm;
            
            fComm.CommentBody = '#InProgress';
            update fComm;
            
            fComm.CommentBody = '#closed';
            update fComm;
            
            fComm.CommentBody = '#escalated';
            update fComm;
            
            fComm.CommentBody = '#high';
            update fComm;
            
            fComm.CommentBody = '#medium';
            update fComm;
            
            fComm.CommentBody = '#low';
            update fComm;
            
            Test.stopTest();
        }
    }
}