force-app/main/default/objects/Lead/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Program__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Deprecated</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Recent_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Recent_Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recent Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Recipient_Email__c.field-meta.xml
<CustomField>
    <fullName>Recipient_Email__c</fullName>
    <label>Recipient Email</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/SCS_HubSpotDuplicateLeadCreator.cls
/*
@Author : MAANTIC
@CreatedDate : 5th AUG 2022
@Description : Lead Trigger Handler For Hubspot.
*/

public class SCS_HubSpotDuplicateLeadCreator 
{
	@future
    public static void doCreateDuplicateLead(string JsonBody)
    {
        List<Lead> lstNewLead = new List<Lead>();
        List<Lead> newduplLead = new List<Lead>();
        lstNewLead = (List<Lead>)JSON.deserialize(JsonBody,List<Lead>.class );
        if(!lstNewLead.isEmpty()){
        for(Lead old:lstNewLead)
        {
            Lead ln = new Lead();
            ln.Program__c = old.program__c;
            ln.FirstName = old.firstname;
            ln.LastName = old.lastname;
            ln.Status = old.status;
            ln.Title = old.title;
            ln.Email = old.email;
            ln.LeadSource = old.leadsource;
            ln.Recent_Campaign__c = old.recent_campaign__c;
            ln.Company = old.Company;
            ln.Recipient_Email__c = old.Recipient_Email__c;
            newduplLead.add(ln);
            
        }
            
        Database.upsert(newduplLead,true);}
    }
    
    @future
    public static void doAddCapmaignMember(string jsonBody)
    {
        List<Lead> lstNewLead = new List<Lead>();
        List<campaignMember> newduplLead = new List<CampaignMember>();
        lstNewLead = (List<Lead>)JSON.deserialize(JsonBody,List<Lead>.class );
        if(!lstNewLead.isEmpty()){
        for(Lead old:lstNewLead)
        {
            Campaignmember cm = new Campaignmember();
            cm.CampaignId = old.Recent_Campaign__c;
            cm.Status = 'Sent';
            cm.LeadId = old.Id;
            newduplLead.add(cm);
            
        }
            
        Database.insert(newduplLead,false);}
        
        
    }
}