force-app/main/default/objects/Opportunity/fields/Bundle_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Bundle_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bundle Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>Bundle Opportunity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Engagement_Type__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Type__c</fullName>
    <label>Engagement Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Program_List__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Engagement_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Portuguese</fullName>
            </value>
            <value>
                <fullName>Japanese</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>Indonesian</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Program_List__c.field-meta.xml
<CustomField>
    <fullName>Program_List__c</fullName>
    <description>This field is populated by an apex trigger once the &quot;Program&quot; lookup field is populated. It also determines the values presented on the &quot;Engagement Type&quot; dependent field.
For internal IT use only.</description>
    <label>Program List</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advanced Technical Programs</fullName>
            </value>
            <value>
                <fullName>Alliance for Responsible Mining</fullName>
            </value>
            <value>
                <fullName>American Tree Farm System</fullName>
            </value>
            <value>
                <fullName>ASC Aquaculture</fullName>
            </value>
            <value>
                <fullName>Assure Certified</fullName>
            </value>
            <value>
                <fullName>Assure Certified Private Label</fullName>
            </value>
            <value>
                <fullName>Better Cotton Initiative (BCI)</fullName>
            </value>
            <value>
                <fullName>BIFMA level</fullName>
            </value>
            <value>
                <fullName>Biodegradable</fullName>
            </value>
            <value>
                <fullName>Biofuels</fullName>
            </value>
            <value>
                <fullName>Bonsucro</fullName>
            </value>
            <value>
                <fullName>Bonsucro Chain of Custody Certification</fullName>
            </value>
            <value>
                <fullName>Bonsucro EU Chain of Custody Certification</fullName>
            </value>
            <value>
                <fullName>Bonsucro EU Production Certification</fullName>
            </value>
            <value>
                <fullName>Bonsucro Production Certification</fullName>
            </value>
            <value>
                <fullName>Bonsucro Smallholder Certification</fullName>
            </value>
            <value>
                <fullName>BRCGS</fullName>
            </value>
            <value>
                <fullName>CanopyStyle</fullName>
            </value>
            <value>
                <fullName>Carbon Footprint Verification</fullName>
            </value>
            <value>
                <fullName>Carbon Neutral</fullName>
            </value>
            <value>
                <fullName>Carbon Offset Verification</fullName>
            </value>
            <value>
                <fullName>Carbon Offset Verification - Forestry</fullName>
            </value>
            <value>
                <fullName>Carbon Offset Verification - Other</fullName>
            </value>
            <value>
                <fullName>CDP Consulting</fullName>
            </value>
            <value>
                <fullName>Clearview</fullName>
            </value>
            <value>
                <fullName>Conflict Minerals Reporting</fullName>
            </value>
            <value>
                <fullName>Consulting</fullName>
            </value>
            <value>
                <fullName>Corporate Footprint Calculation</fullName>
            </value>
            <value>
                <fullName>Corporate Sustainability</fullName>
            </value>
            <value>
                <fullName>CSS Consulting</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Programc__c.field-meta.xml
<CustomField>
    <fullName>Programc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>The selected program is deprecated, please select another program</errorMessage>
        <filterItems>
            <field>Program__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Deprecated</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reporting_Division__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Division__c</fullName>
    <formula>TEXT(Programc__r.Reporting_Division__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Reporting Division</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Target_Audit_Date__c.field-meta.xml
<CustomField>
    <fullName>Target_Audit_Date__c</fullName>
    <label>Target Audit Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Opportunity with or without products
Total Opportunity Amount</description>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>Discount_Amount__c</fullName>
    <label>Discount Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Price Books</relationshipLabel>
    <relationshipName>Price_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Price Book Entries</relationshipLabel>
    <relationshipName>Price_Book_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <label>Division</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Reporting_Division__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Division__c</fullName>
    <label>Reporting Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Entity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scope__c/Scope__c.object-meta.xml
<CustomObject>
    <description>Program / Project Scope</description>
    <label>Scope</label>
    <nameField>
        <displayFormat>SC-{0000000}</displayFormat>
        <label>Scope #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scope</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scope__c/fields/Engagement_Type__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Type__c</fullName>
    <label>Engagement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Engagement_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scope__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
                <default>true</default>
                <label>English</label>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Portuguese</fullName>
            </value>
            <value>
                <fullName>Japanese</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>Indonesian</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scope__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Scope</relationshipLabel>
    <relationshipName>Scope</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scope__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Scope</relationshipLabel>
    <relationshipName>Scope</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scope__c/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Standard__c/Standard__c.object-meta.xml
<CustomObject>
    <label>Standard</label>
    <nameField>
        <label>Standard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standards</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Standard__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Portuguese</fullName>
            </value>
            <value>
                <fullName>Japanese</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>Indonesian</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Standard__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Standards</relationshipLabel>
    <relationshipName>Standards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Standard__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <inlineHelpText>Title as per to be displayed on Quote</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Standard_Covered__c/Standard_Covered__c.object-meta.xml
<CustomObject>
    <label>Standard Covered</label>
    <nameField>
        <displayFormat>SC-{0000000}</displayFormat>
        <label>Standard Covered Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Standard Covered</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Standard_Covered__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Standard Covered</relationshipLabel>
    <relationshipName>Standard_Covered</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Standard_Covered__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Standard Covered</relationshipLabel>
    <relationshipName>Standard_Covered</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Engagement_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1st Surveillance</fullName>
    </customValue>
    <customValue>
        <fullName>2nd Surveillance</fullName>
    </customValue>
    <customValue>
        <fullName>3rd Party Verification</fullName>
    </customValue>
    <customValue>
        <fullName>3rd Surveillance</fullName>
    </customValue>
    <customValue>
        <fullName>4th Surveillance</fullName>
    </customValue>
    <customValue>
        <fullName>ACDR only</fullName>
    </customValue>
    <customValue>
        <fullName>Action Plan Review</fullName>
    </customValue>
    <customValue>
        <fullName>AIM Initial</fullName>
    </customValue>
    <customValue>
        <fullName>AIM Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <customValue>
        <fullName>Annual Surveillance</fullName>
    </customValue>
    <customValue>
        <fullName>CAP</fullName>
    </customValue>
    <customValue>
        <fullName>Certification</fullName>
    </customValue>
    <customValue>
        <fullName>Closure of Findings</fullName>
    </customValue>
    <customValue>
        <fullName>Complaint Resolution</fullName>
    </customValue>
    <customValue>
        <fullName>Conformance Surveillance</fullName>
    </customValue>
    <customValue>
        <fullName>Consulting</fullName>
    </customValue>
    <customValue>
        <fullName>Due Diligence</fullName>
    </customValue>
    <customValue>
        <fullName>Each Additional</fullName>
    </customValue>
    <customValue>
        <fullName>Evaluation</fullName>
    </customValue>
    <customValue>
        <fullName>Expansion of Scope</fullName>
    </customValue>
    <customValue>
        <fullName>Expedited Audit</fullName>
    </customValue>
    <customValue>
        <fullName>Extension</fullName>
    </customValue>
    <customValue>
        <fullName>Field Assessment</fullName>
    </customValue>
    <customValue>
        <fullName>FIP Services</fullName>
    </customValue>
    <customValue>
        <fullName>Follow-up</fullName>
    </customValue>
    <customValue>
        <fullName>FSA Farm Management Group Claims</fullName>
    </customValue>
    <customValue>
        <fullName>FSA Option 1</fullName>
    </customValue>
    <customValue>
        <fullName>FSA Option 2</fullName>
    </customValue>
    <customValue>
        <fullName>FSA Option 3</fullName>
    </customValue>
    <masterLabel>Engagement Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Entity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ECS</fullName>
    </customValue>
    <customValue>
        <fullName>Food and Agriculture</fullName>
    </customValue>
    <customValue>
        <fullName>Natural Resources</fullName>
    </customValue>
    <customValue>
        <fullName>SCS Consulting</fullName>
    </customValue>
    <customValue>
        <fullName>SCS Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Research and Development</fullName>
    </customValue>
    <customValue>
        <fullName>Advanced Technical Programs</fullName>
    </customValue>
    <masterLabel>Entity</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AddChildOpportunityLWCController.cls
/*
@Author : MAANTIC
@CreatedDate : 26th Feb 2023
@Description : This class is used to create child opportunity and line items under bundle opportunity.
@CreatedBy : Sohit Tripathi
*/
/****************************** New ORG CODE *****************************************************/
public without sharing class AddChildOpportunityLWCController {
    
    @AuraEnabled(cacheable=true)
    public static WrapperClass getPricebookAndRecordType(String programName){
        List<Pricebook2> pricebookList = [SELECT Id, Name, Program__c, Program__r.Reporting_Division__c FROM Pricebook2 WHERE Program__r.Name =:programName AND IsActive = true];
        List<Pricebook2> allpricebookList = [SELECT Id, Name, Program__c, Program__r.Reporting_Division__c FROM Pricebook2 WHERE IsActive = true];
        Program__c prg = [SELECT Id, Name, Reporting_Division__c, Division__c FROM Program__c WHERE Name =:programName LIMIT 1];
        
        if(pricebookList != null && !pricebookList.isEmpty()){
            WrapperClass wrap = new WrapperClass();
            wrap.prg = prg != null ? prg : null;
            wrap.pricebookList = pricebookList;
            wrap.opp = null;
            wrap.pricebookName = null;
            return wrap;
        }
        else{
            WrapperClass wrap = new WrapperClass();
            wrap.prg = prg != null ? prg : null;
            wrap.pricebookList = allpricebookList;
            wrap.opp = null;
            wrap.pricebookName = null;
            return wrap;
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static PriceBookEntry getPricebookEntry(String product2Id){
        return [SELECT Id, Name, Pricebook2Id, Product2Id, UnitPrice FROM PriceBookEntry WHERE Product2Id =:product2Id LIMIT 1];
    }    
    
    @AuraEnabled(cacheable=true)
    public static List<WrapperClass> getAllOpptyWithOlis(String bundleOpptyId){
        List<Map<String ,Object>> oppMapList  = new  List<Map<String ,Object>>();
        Set<String> programNameSet = new Set<String>();
        List<WrapperClass> wrapperList = new List<WrapperClass>();
        Map<String, List<Pricebook2>> mapProgramPricebook = new Map<String, List<Pricebook2>>();
        Map<Id, List<Scope__c>> mapPrgScope = new Map<Id, List<Scope__c>>();
        List<Opportunity> oppList = [SELECT Id, TotalAmount__c, RecordTypeId, LeadSource, Target_Audit_Date__c, Pricebook2Id, Pricebook2.Name, AccountId, Name, Program_List__c, Engagement_Type__c, StageName, CloseDate, Type, HasOpportunityLineItem, Bundle_Opportunity__c, Language__c, Programc__c,
                                     (SELECT Id, Name, Quantity, Discount, Discount_Amount__c, TotalPrice, UnitPrice, Product2Id, Description FROM OpportunityLineItems ORDER BY CreatedDate ASC),
                                     (SELECT Id, name, Title__c, Description__c, Opportunity__c, Program__c, Sub_Scope__c, Sub_Scope__r.Name FROM Scope__r Where Sub_Scope__c != null),
                                     (SELECT Id, Standard__c, Opportunity__c, Program__c, Name FROM Standard_Covered__r)
                                     FROM Opportunity where Bundle_Opportunity__c =:bundleOpptyId ORDER BY CreatedDate ASC];
        if(!oppList.isEmpty()){
            for(Opportunity opp : oppList){
                programNameSet.add(opp.Program_List__c);
            }
        }
        
        List<Pricebook2> pricebookList = [SELECT Id, Name, Program__c, Program__r.Name, Program__r.Reporting_Division__c FROM Pricebook2 WHERE Program__r.Name IN:programNameSet AND IsActive = true];
        List<Pricebook2> allpricebookList = [SELECT Id, Name, Program__c, Program__r.Name, Program__r.Reporting_Division__c FROM Pricebook2 WHERE IsActive = true];
                
        if(!pricebookList.isEmpty()){
            for(Pricebook2 pb : pricebookList){
                if(!mapProgramPricebook.containsKey(pb.Program__r.Name)){
                    mapProgramPricebook.put(pb.Program__r.Name, new List<Pricebook2>{pb});
                }
                else{
                    mapProgramPricebook.get(pb.Program__r.Name).add(pb);
                }
            }
        }
        
        if(!programNameSet.isEmpty()){
            String subScopeRecType = Label.SubScopeRecordType;
            for(Scope__c sc : [SELECT Id, Name, Title__c, Description__c, Sub_Scope__c,Program__c FROM Scope__c WHERE RecordType.DeveloperName=:subScopeRecType AND Program__r.Name =:programNameSet]){
                if(!mapPrgScope.containsKey(sc.Program__c)){
                    mapPrgScope.put(sc.Program__c, new List<Scope__c>{sc});
                }
                else{
                    mapPrgScope.get(sc.Program__c).add(sc);
                }
            }
        }
        
        if(!oppList.isEmpty()){
            for(Opportunity opp : oppList){
                WrapperClass wrap = new WrapperClass();
                wrap.prg = null;
                if(mapProgramPricebook.containsKey(opp.Program_List__c) && !mapProgramPricebook.get(opp.Program_List__c).isEmpty()){
                    wrap.pricebookList = mapProgramPricebook.get(opp.Program_List__c);
                    wrap.pricebookName = opp.Pricebook2.Name;
                }
                else{
                    wrap.pricebookList = allpricebookList;
                    wrap.pricebookName = '';
                }
                wrap.opp = opp;
                if(mapPrgScope.containsKey(opp.Programc__c) && !mapPrgScope.get(opp.Programc__c).isEmpty()){
                    wrap.subScopeList = mapPrgScope.get(opp.Programc__c);
                }
                wrap.hasSubScope = opp.Scope__r.size() > 0 ? true : false;
                wrap.hasStandardCovered = opp.Standard_Covered__r.size() > 0 ? true : false;
                wrapperList.add(wrap);
            }
        }
        return wrapperList;
    }
    
    public class WrapperClass{
        @AuraEnabled
        public Program__c prg{get;set;}
        @AuraEnabled
        public List<Pricebook2> pricebookList{get;set;}
        @AuraEnabled
        public Opportunity opp{get;set;}
        @AuraEnabled
        public String pricebookName{get;set;}
        @AuraEnabled
        public List<Scope__c> subScopeList{get;set;}
        @AuraEnabled
        public Boolean hasSubScope{get;set;}
        @AuraEnabled
        public Boolean hasStandardCovered{get;set;}
    }
    
    @AuraEnabled(Cacheable=false)
    public static void upsertOpptyList(String opptyList, String oliList, String subScopeList, String standardList){
        System.debug('subScopeList--'+subScopeList);
        List<Opportunity> opptyListToUpdate = new List<Opportunity>();
        List<Opportunity> opptyListToInsert = new List<Opportunity>();
        List<Opportunity> opportunityList = new List<Opportunity>();
        List<OpportunityLineItem> opportunityLItemList = new List<OpportunityLineItem>();
        List<Scope__c> scopeList = new List<Scope__c>();
        List<Standard_Covered__c> stanCoveredList = new List<Standard_Covered__c>();
        
        if(String.isNotBlank(opptyList)){
            opportunityList = (List<Opportunity>) JSON.deserialize(opptyList, List<Opportunity>.class);
        }
        if(String.isNotBlank(oliList)){
            opportunityLItemList = (List<OpportunityLineItem>) JSON.deserialize(oliList, List<OpportunityLineItem>.class);
        }
        if(String.isNotBlank(subScopeList)){
            scopeList = (List<Scope__c>) JSON.deserialize(subScopeList, List<Scope__c>.class);
        }
        if(String.isNotBlank(standardList)){
            stanCoveredList = (List<Standard_Covered__c>) JSON.deserialize(standardList, List<Standard_Covered__c>.class);
        }
        
        try{
            if(opportunityList != null && !opportunityList.isEmpty()){
                upsert opportunityList;
            }
            
            if(opportunityLItemList != null && !opportunityLItemList.isEmpty()){
                upsert opportunityLItemList;
            }
            
            if(scopeList != null && !scopeList.isEmpty()){
                upsert scopeList;
            }
            
            if(stanCoveredList != null && !stanCoveredList.isEmpty()){
                upsert stanCoveredList;
            }
        }
        catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled(Cacheable=false)
    public static void deleteOpportunity(String recordId){
        try{
            if(recordId.startsWith('006')){
                //Delete [SELECT Id FROM Opportunity WHERE Id=:recordId];
                Opportunity opp = new Opportunity(Id = recordId, StageName = 'Closed Lost', 
                                                  Loss_Reason__c = 'Removed from Bundle Opportunity', 
                                                  Bundle_Opportunity__c = null,
                                                  CampaignId = Label.lblDefaultHSCampaign);
                update opp;
            }
            else if(recordId.startsWith('00k')){
                Delete [SELECT Id FROM OpportunityLineItem WHERE Id=:recordId];
            }
            else if(recordId.startsWith('a26')){
                Delete [SELECT Id FROM Scope__c WHERE Id=:recordId];
            }
            else{
                Delete [SELECT Id FROM Standard_Covered__c WHERE Id=:recordId];
            }
        }
        catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    
}