force-app/main/default/objects/Opportunity/fields/Commission__c.field-meta.xml
<CustomField>
    <fullName>Commission__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Commission</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/G_A__c.field-meta.xml
<CustomField>
    <fullName>G_A__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>G&amp;A</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Commission__c.field-meta.xml
<CustomField>
    <fullName>Commission__c</fullName>
    <formula>TotalAdjustedPrice__c * Opportunity.Commission__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Commission</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Revenue_Type__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Type__c</fullName>
    <label>Revenue Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>P - Professional Fees</fullName>
            </value>
            <value>
                <fullName>R - Reimbursable/Travel</fullName>
            </value>
            <value>
                <fullName>F - Fees (Accreditation)</fullName>
            </value>
            <value>
                <fullName>L - Lab Fees</fullName>
            </value>
            <value>
                <fullName>C - Commission Revenue</fullName>
            </value>
            <value>
                <fullName>M - Misc./Other</fullName>
            </value>
            <value>
                <fullName>RN - Renewal</fullName>
            </value>
            <value>
                <fullName>SCS Registry</fullName>
                <isActive>false</isActive>
                <label>SCS Registry</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Total_Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Sales_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Sales Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Revenue_Type__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Type__c</fullName>
    <description>Product revenue type.</description>
    <label>Revenue Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>P - Professional Fees</fullName>
            </value>
            <value>
                <fullName>R - Reimbursable/Travel</fullName>
            </value>
            <value>
                <fullName>F - Fees (Accreditation)</fullName>
            </value>
            <value>
                <fullName>L - Lab Fees</fullName>
            </value>
            <value>
                <fullName>C - Commission Revenue</fullName>
            </value>
            <value>
                <fullName>M - Misc./Other</fullName>
            </value>
            <value>
                <fullName>RN - Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityLineItemTriggerHelper.cls
/*
@Author : MAANTIC
@CreatedDate : 8th August 2022
@Description : Opportunity Product Object Trigger Helper use to calculate Total Sales Price..
*/

public with sharing class OpportunityLineItemTriggerHelper {
    
    public static void calculateTotalSalesPrice(Set<Id> opptyIdSet, List<OpportunityLineItem> recordList, Set<Id> recordProductList){
        Map<Id, Opportunity> mapOpportunity = new Map<Id, Opportunity>();
        Map<Id, Product2> mapProduct;
        
        if(opptyIdSet != null && !opptyIdSet.isEmpty()){
            mapOpportunity = new Map<Id, Opportunity>([SELECT Id, Commission__c, Margin__c, G_A__c FROM Opportunity WHERE Id IN:opptyIdSet]);
            mapProduct = new Map<ID, Product2>( [Select Id,Revenue_Type__c from Product2 WHERE Id IN:recordProductList] );
        }
        
        for(OpportunityLineItem record : recordList){
            Boolean revenueTypeCheck = false;
            Decimal discount = record.Discount != null ? record.Discount : 0.00;
            if(mapProduct.containsKey(record.Product2Id)){
                revenueTypeCheck = mapProduct.get(record.Product2Id).Revenue_Type__c == 'R - Reimbursable/Travel' ? true : false ;
            }
            if(revenueTypeCheck){
                record.Total_Sales_Price__c = ((record.Quantity * record.UnitPrice)-((record.Quantity * record.UnitPrice) * (discount/100)));
            }
            else{
                //Decimal discount = record.Discount != null ? record.Discount : 0.00;
                Decimal margin = mapOpportunity.get(record.OpportunityId).Margin__c != null ? mapOpportunity.get(record.OpportunityId).Margin__c : 0.00;
                Decimal commission = mapOpportunity.get(record.OpportunityId).Commission__c != null ? mapOpportunity.get(record.OpportunityId).Commission__c : 0.00;
                Decimal ga = mapOpportunity.get(record.OpportunityId).G_A__c != null ? mapOpportunity.get(record.OpportunityId).G_A__c : 0.00;
                
                record.Total_Sales_Price__c = ((record.Quantity * record.UnitPrice) + ((record.Quantity * record.UnitPrice) * (margin/100)) + ((record.Quantity * record.UnitPrice) * (commission/100)) + ((record.Quantity * record.UnitPrice) * (ga/100))) - ((record.Quantity * record.UnitPrice) * (discount/100));
            }       
        }
    }
}