force-app/main/default/objects/Opportunity/fields/Create_Sharepoint_Folder__c.field-meta.xml
<CustomField>
    <fullName>Create_Sharepoint_Folder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Create Sharepoint Folder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity_Certificate__c/Opportunity_Certificate__c.object-meta.xml
<CustomObject>
    <label>Opportunity Certificate</label>
    <nameField>
        <displayFormat>OC-{0000}</displayFormat>
        <label>Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Certificates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OpportunityCertificateTriggerHelper.cls
/*
@Author : MAANTIC
@CreatedDate : 30 November 2022
@Description : Opportunity Certificate Object Trigger Helper use to update opportunity certificate..
Date: 30/11/2022
Created By: Sohit Tripathi
*/
public with sharing class OpportunityCertificateTriggerHelper {
    
    public static void sFilesCreateOpportunityCertFolder(List<Opportunity_Certificate__c> newList, Map<Id, Opportunity_Certificate__c> oldMap){
        Set<Id> opptyCertIdSet = new Set<Id>();
        for(Opportunity_Certificate__c oppCert : newList){
            if(oldMap == null){
                if(oppCert.createdById != System.Label.SCS_CVENT_USER_Id){
                    opptyCertIdSet.add(oppCert.Id);
                }
            }
            else{
                if(oppCert.Create_Sharepoint_Folder__c != oldMap.get(oppCert.Id).Create_Sharepoint_Folder__c && oppCert.Create_Sharepoint_Folder__c == true){
                    opptyCertIdSet.add(oppCert.Id);
                }
            }
        }
        
        if(opptyCertIdSet != null && !opptyCertIdSet.isEmpty() && !(Test.isRunningTest()) ){    
            sFilesCallout.createFoldersonSharePointForOpptyCertificate(opptyCertIdSet);
        }
    }

}