force-app/main/default/objects/CertifiedProducts__c/CertifiedProducts__c.object-meta.xml
<CustomObject>
    <label>Certified Product</label>
    <nameField>
        <displayFormat>CRTP-{0000000}</displayFormat>
        <label>Certified Products Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certified Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CertifiedProducts__c/fields/OpportunityCertificate__c.field-meta.xml
<CustomField>
    <fullName>OpportunityCertificate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Certificate</label>
    <referenceTo>Opportunity_Certificate__c</referenceTo>
    <relationshipLabel>Certified Products</relationshipLabel>
    <relationshipName>Certified_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CertifiedProducts__c/fields/Output_Category__c.field-meta.xml
<CustomField>
    <fullName>Output_Category__c</fullName>
    <label>Output Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FSC 100%</fullName>
            </value>
            <value>
                <fullName>FSC Mix</fullName>
            </value>
            <value>
                <fullName>FSC Recycled</fullName>
            </value>
            <value>
                <fullName>FSC Controlled Wood</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Certificate__c/Opportunity_Certificate__c.object-meta.xml
<CustomObject>
    <label>Opportunity Certificate</label>
    <nameField>
        <displayFormat>OC-{0000}</displayFormat>
        <label>Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Certificates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Certificate__c/fields/Output_Category__c.field-meta.xml
<CustomField>
    <fullName>Output_Category__c</fullName>
    <description>FSC</description>
    <label>Output Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FSC 100%</fullName>
            </value>
            <value>
                <fullName>FSC Mix</fullName>
            </value>
            <value>
                <fullName>FSC Recycled</fullName>
            </value>
            <value>
                <fullName>FSC Controlled Wood</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Certificate__c/fields/Product_Claims__c.field-meta.xml
<CustomField>
    <fullName>Product_Claims__c</fullName>
    <label>Product Claims</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FSC 100%</fullName>
            </value>
            <value>
                <fullName>FSC Mix</fullName>
            </value>
            <value>
                <fullName>FSC Controlled Wood</fullName>
            </value>
            <value>
                <fullName>FSC Recycled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SCS_CertifiedProductHelper.cls
public with sharing class SCS_CertifiedProductHelper {
    
    //call from certified trigger handler on insert or update...
    public static void addProductClaim(List<CertifiedProducts__c> newList,Map<Id,CertifiedProducts__c> oldMap){
        Set<String> ocIdSet = new Set<String>();
        Map<String,Set<String>> catMap = new Map<String,Set<String>> ();
        List<Opportunity_Certificate__c> updatedList = new List<Opportunity_Certificate__c> ();
        for(CertifiedProducts__c record :newList) {
            if(oldMap == null || (oldMap != null && record.Output_Category__c != oldMap.get(record.Id).Output_Category__c)){
                ocIdSet.add(record.OpportunityCertificate__c);    
            }
        }
        if(! ocIdSet.isEmpty()) {
            for(CertifiedProducts__c cp:[SELECT Id,Output_Category__c,OpportunityCertificate__c FROM CertifiedProducts__c WHERE OpportunityCertificate__c IN : ocIdSet] ){
                String catStr = cp.Output_Category__c;
                if(String.isNotBlank(catStr)) {
                    if(catStr.contains(';')) {
                        for(String str : catStr.split(';')) {
                            if (!catMap.containsKey(cp.OpportunityCertificate__c)) {
                                catMap.put(cp.OpportunityCertificate__c, new Set<String>());
                            }
                            catMap.get(cp.OpportunityCertificate__c).add(str);   
                        }
                    } else {
                        if (!catMap.containsKey(cp.OpportunityCertificate__c)) {
                            catMap.put(cp.OpportunityCertificate__c, new Set<String>());
                        }
                        catMap.get(cp.OpportunityCertificate__c).add(catStr);   
                    }
                } else {
                    if (!catMap.containsKey(cp.OpportunityCertificate__c)) {
                        catMap.put(cp.OpportunityCertificate__c, new Set<String>());
                    }
                    catMap.get(cp.OpportunityCertificate__c).add(catStr); 
                } 
            } 
        }
        
        if(! catMap.isEmpty()) {
            for(String key : catMap.keySet()){
                updatedList.add(new Opportunity_Certificate__c(Id = key,Product_Claims__c = String.join(new Set <String> (catMap.get(key)), ';')));
            } 
        }
        if(! updatedList.isEmpty()){
            update updatedList;
        }
    }
    
}