force-app/main/default/objects/FSC_AAF_Table__mdt/FSC_AAF_Table__mdt.object-meta.xml
<CustomObject>
    <description>FSC</description>
    <label>FSC AAF Table</label>
    <pluralLabel>FSC AAF Table</pluralLabel>
</CustomObject>

force-app/main/default/objects/FSC_AAF_Table__mdt/fields/Fixed_Number__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Number__c</fullName>
    <defaultValue>1000000</defaultValue>
    <description>FSC</description>
    <label>Fixed Number</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FSC_AAF_Table__mdt/fields/Maximum_Turnover__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Turnover__c</fullName>
    <description>FSC</description>
    <label>Maximum Turnover</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FSC_AAF_Table__mdt/fields/Minimum_Turnover__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Turnover__c</fullName>
    <description>FSC</description>
    <label>Minimum Turnover</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FSC_AAF_Table__mdt/fields/Processor_Base_USD__c.field-meta.xml
<CustomField>
    <fullName>Processor_Base_USD__c</fullName>
    <description>FSC</description>
    <label>Processor  Base (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FSC_AAF_Table__mdt/fields/Processor_Variable_USD__c.field-meta.xml
<CustomField>
    <fullName>Processor_Variable_USD__c</fullName>
    <description>FSC</description>
    <label>Processor  Variable (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FSC_AAF_Table__mdt/fields/Trader_Base_USD__c.field-meta.xml
<CustomField>
    <fullName>Trader_Base_USD__c</fullName>
    <description>FSC</description>
    <label>Trader Base  (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FSC_AAF_Table__mdt/fields/Trader_Variable_USD__c.field-meta.xml
<CustomField>
    <fullName>Trader_Variable_USD__c</fullName>
    <description>FSC</description>
    <label>Trader  Variable  (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity_Certificate__c/Opportunity_Certificate__c.object-meta.xml
<CustomObject>
    <label>Opportunity Certificate</label>
    <nameField>
        <displayFormat>OC-{0000}</displayFormat>
        <label>Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Certificates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Certificate__c/fields/Annual_Administration_Fee_AAF__c.field-meta.xml
<CustomField>
    <fullName>Annual_Administration_Fee_AAF__c</fullName>
    <description>FSC</description>
    <label>Annual Administration Fee (AAF)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_Certificate__c/fields/Company_Type__c.field-meta.xml
<CustomField>
    <fullName>Company_Type__c</fullName>
    <description>FSC</description>
    <formula>IF ( INCLUDES(Certificate__r.SCS_Certification_Type__c, &apos;Manufacturer&apos;),&apos;Manufacturer;&apos;,null) &amp;
IF ( INCLUDES(Certificate__r.SCS_Certification_Type__c, &apos;Trader&apos;),&apos;Trader&apos;,null )</formula>
    <label>Company Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Certificate__c/fields/FPT__c.field-meta.xml
<CustomField>
    <fullName>FPT__c</fullName>
    <description>FSC</description>
    <label>FPT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_Certificate__c/fields/FPT_Calculated__c.field-meta.xml
<CustomField>
    <fullName>FPT_Calculated__c</fullName>
    <description>Use in Trader_AAF_Class, Processor_AAF_Class field</description>
    <formula>IF(ISNULL(Total_Revenue__c ),FPT__c,Total_Revenue__c)</formula>
    <label>FPT Calculated</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_Certificate__c/fields/FPT_Processor__c.field-meta.xml
<CustomField>
    <fullName>FPT_Processor__c</fullName>
    <description>FSC</description>
    <label>FPT Processor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_Certificate__c/fields/FPT_Processor_Calculated__c.field-meta.xml
<CustomField>
    <fullName>FPT_Processor_Calculated__c</fullName>
    <description>FSC</description>
    <formula>IF( ISNULL(FPT_Processor__c),Revenue_Processor__c,FPT_Processor__c)</formula>
    <label>FPT Processor  Calculated</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_Certificate__c/fields/FPT_Trader__c.field-meta.xml
<CustomField>
    <fullName>FPT_Trader__c</fullName>
    <description>FSC</description>
    <label>FPT Trader</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_Certificate__c/fields/FPT_Trader_Calculated__c.field-meta.xml
<CustomField>
    <fullName>FPT_Trader_Calculated__c</fullName>
    <description>FSC</description>
    <formula>IF( ISNULL(FPT_Trader__c),Revenue_Trader__c,FPT_Trader__c)</formula>
    <label>FPT Trader Calculated</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_Certificate__c/fields/FSC_Certificate_Type__c.field-meta.xml
<CustomField>
    <fullName>FSC_Certificate_Type__c</fullName>
    <description>FSC</description>
    <label>FSC Certificate Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single Certificate</fullName>
            </value>
            <value>
                <fullName>Multi Certificate</fullName>
            </value>
            <value>
                <fullName>Group Certificate</fullName>
            </value>
            <value>
                <fullName>Project Certificate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Certificate__c/fields/Processor_AAF_Class__c.field-meta.xml
<CustomField>
    <fullName>Processor_AAF_Class__c</fullName>
    <formula>IF(ISPICKVAL(FSC_Certificate_Type__c, &apos;Group Certificate&apos;) &amp;&amp;  INCLUDES(Certificate__r.SCS_Certification_Type__c, &apos;Manufacturer&apos;),
IF(FPT_Processor_Calculated__c  &lt;= $CustomMetadata.FSC_AAF_Table__mdt.Class_1.Maximum_Turnover__c,&apos;Class 1&apos;,
 IF(FPT_Processor_Calculated__c  &lt;= $CustomMetadata.FSC_AAF_Table__mdt.Class_2.Maximum_Turnover__c,&apos;Class 2&apos;,
 IF(FPT_Processor_Calculated__c  &lt;= $CustomMetadata.FSC_AAF_Table__mdt.Class_3.Maximum_Turnover__c,&apos;Class 3&apos;,
 IF(FPT_Processor_Calculated__c  &lt;= $CustomMetadata.FSC_AAF_Table__mdt.Class_4.Maximum_Turnover__c,&apos;Class 4&apos;,
 IF(FPT_Processor_Calculated__c  &lt;= $CustomMetadata.FSC_AAF_Table__mdt.Class_5.Maximum_Turnover__c,&apos;Class 5&apos;,
 IF(FPT_Processor_Calculated__c  &lt;= $CustomMetadata.FSC_AAF_Table__mdt.Class_6.Maximum_Turnover__c,&apos;Class 6&apos;,
 IF(FPT_Processor_Calculated__c  &gt; $CustomMetadata.FSC_AAF_Table__mdt.Class_7.Minimum_Turnover__c,&apos;Class 7&apos;,&apos;&apos;))))))), 
IF(ISPICKVAL(FSC_Certificate_Type__c, &apos;Project Certificate&apos;) &amp;&amp; INCLUDES(Certificate__r.SCS_Certification_Type__c, &apos;Manufacturer&apos;),
IF(Project_Cost__c  &lt;= $CustomMetadata.FSC_AAF_Table__mdt.Class_1.Maximum_Turnover__c,&apos;Class 1&apos;,
 IF(Project_Cost__c  &lt;= $CustomMetadata.FSC_AAF_Table__mdt.Class_2.Maximum_Turnover__c,&apos;Class 2&apos;,
 IF(Project_Cost__c  &lt;= $CustomMetadata.FSC_AAF_Table__mdt.Class_3.Maximum_Turnover__c,&apos;Class 3&apos;,
 IF(Project_Cost__c  &lt;= $CustomMetadata.FSC_AAF_Table__mdt.Class_4.Maximum_Turnover__c,&apos;Class 4&apos;,
 IF(Project_Cost__c  &lt;= $CustomMetadata.FSC_AAF_Table__mdt.Class_5.Maximum_Turnover__c,&apos;Class 5&apos;,
 IF(Project_Cost__c  &lt;= $CustomMetadata.FSC_AAF_Table__mdt.Class_6.Maximum_Turnover__c,&apos;Class 6&apos;,
 IF(Project_Cost__c  &gt; $CustomMetadata.FSC_AAF_Table__mdt.Class_7.Minimum_Turnover__c,&apos;Class 7&apos;,&apos;&apos;))))))),
IF(INCLUDES(Certificate__r.SCS_Certification_Type__c, &apos;Manufacturer&apos;),
IF(FPT_Calculated__c  &lt;= $CustomMetadata.FSC_AAF_Table__mdt.Class_1.Maximum_Turnover__c,&apos;Class 1&apos;,
 IF(FPT_Calculated__c  &lt;= $CustomMetadata.FSC_AAF_Table__mdt.Class_2.Maximum_Turnover__c,&apos;Class 2&apos;,
 IF(FPT_Calculated__c  &lt;= $CustomMetadata.FSC_AAF_Table__mdt.Class_3.Maximum_Turnover__c,&apos;Class 3&apos;,
 IF(FPT_Calculated__c  &lt;= $CustomMetadata.FSC_AAF_Table__mdt.Class_4.Maximum_Turnover__c,&apos;Class 4&apos;,
 IF(FPT_Calculated__c  &lt;= $CustomMetadata.FSC_AAF_Table__mdt.Class_5.Maximum_Turnover__c,&apos;Class 5&apos;,
 IF(FPT_Calculated__c  &lt;= $CustomMetadata.FSC_AAF_Table__mdt.Class_6.Maximum_Turnover__c,&apos;Class 6&apos;,
 IF(FPT_Calculated__c  &gt; $CustomMetadata.FSC_AAF_Table__mdt.Class_7.Minimum_Turnover__c,&apos;Class 7&apos;,&apos;&apos;))))))),&apos;&apos;)))</formula>
    <label>Processor AAF Class</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Certificate__c/fields/Project_Cost__c.field-meta.xml
<CustomField>
    <fullName>Project_Cost__c</fullName>
    <description>FSC</description>
    <label>Project Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_Certificate__c/fields/Revenue_Processor__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Processor__c</fullName>
    <description>FSC</description>
    <label>Revenue Processor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_Certificate__c/fields/Revenue_Trader__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Trader__c</fullName>
    <description>FSC</description>
    <label>Revenue Trader</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_Certificate__c/fields/Total_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Total_Revenue__c</fullName>
    <description>FSC</description>
    <label>Total Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_Certificate__c/fields/Trader_AAF_Class__c.field-meta.xml
<CustomField>
    <fullName>Trader_AAF_Class__c</fullName>
    <description>FSC</description>
    <formula>IF(ISPICKVAL(FSC_Certificate_Type__c, &apos;Group Certificate&apos;) &amp;&amp;  INCLUDES(Certificate__r.SCS_Certification_Type__c, &apos;Trader&apos;),
 IF(FPT_Trader_Calculated__c  &lt;= $CustomMetadata.FSC_AAF_Table__mdt.Class_1.Maximum_Turnover__c,&apos;Class 1&apos;,
 IF(FPT_Trader_Calculated__c  &lt;= $CustomMetadata.FSC_AAF_Table__mdt.Class_2.Maximum_Turnover__c,&apos;Class 2&apos;,
 IF(FPT_Trader_Calculated__c  &lt;= $CustomMetadata.FSC_AAF_Table__mdt.Class_3.Maximum_Turnover__c,&apos;Class 3&apos;,
 IF(FPT_Trader_Calculated__c  &lt;= $CustomMetadata.FSC_AAF_Table__mdt.Class_4.Maximum_Turnover__c,&apos;Class 4&apos;,
 IF(FPT_Trader_Calculated__c  &lt;= $CustomMetadata.FSC_AAF_Table__mdt.Class_5.Maximum_Turnover__c,&apos;Class 5&apos;,
 IF(FPT_Trader_Calculated__c  &lt;= $CustomMetadata.FSC_AAF_Table__mdt.Class_6.Maximum_Turnover__c,&apos;Class 6&apos;,
 IF(FPT_Trader_Calculated__c  &gt; $CustomMetadata.FSC_AAF_Table__mdt.Class_7.Minimum_Turnover__c,&apos;Class 7&apos;,&apos;&apos;))))))), 
IF(ISPICKVAL(FSC_Certificate_Type__c, &apos;Project Certificate&apos;) &amp;&amp; INCLUDES(Certificate__r.SCS_Certification_Type__c, &apos;Trader&apos;),
IF(Project_Cost__c  &lt;= $CustomMetadata.FSC_AAF_Table__mdt.Class_1.Maximum_Turnover__c,&apos;Class 1&apos;,
 IF(Project_Cost__c  &lt;= $CustomMetadata.FSC_AAF_Table__mdt.Class_2.Maximum_Turnover__c,&apos;Class 2&apos;,
 IF(Project_Cost__c  &lt;= $CustomMetadata.FSC_AAF_Table__mdt.Class_3.Maximum_Turnover__c,&apos;Class 3&apos;,
 IF(Project_Cost__c  &lt;= $CustomMetadata.FSC_AAF_Table__mdt.Class_4.Maximum_Turnover__c,&apos;Class 4&apos;,
 IF(Project_Cost__c  &lt;= $CustomMetadata.FSC_AAF_Table__mdt.Class_5.Maximum_Turnover__c,&apos;Class 5&apos;,
 IF(Project_Cost__c  &lt;= $CustomMetadata.FSC_AAF_Table__mdt.Class_6.Maximum_Turnover__c,&apos;Class 6&apos;,
 IF(Project_Cost__c  &gt; $CustomMetadata.FSC_AAF_Table__mdt.Class_7.Minimum_Turnover__c,&apos;Class 7&apos;,&apos;&apos;))))))),
IF(INCLUDES(Certificate__r.SCS_Certification_Type__c, &apos;Trader&apos;),
IF(FPT_Calculated__c  &lt;= $CustomMetadata.FSC_AAF_Table__mdt.Class_1.Maximum_Turnover__c,&apos;Class 1&apos;,
 IF(FPT_Calculated__c  &lt;= $CustomMetadata.FSC_AAF_Table__mdt.Class_2.Maximum_Turnover__c,&apos;Class 2&apos;,
 IF(FPT_Calculated__c  &lt;= $CustomMetadata.FSC_AAF_Table__mdt.Class_3.Maximum_Turnover__c,&apos;Class 3&apos;,
 IF(FPT_Calculated__c  &lt;= $CustomMetadata.FSC_AAF_Table__mdt.Class_4.Maximum_Turnover__c,&apos;Class 4&apos;,
 IF(FPT_Calculated__c  &lt;= $CustomMetadata.FSC_AAF_Table__mdt.Class_5.Maximum_Turnover__c,&apos;Class 5&apos;,
 IF(FPT_Calculated__c  &lt;= $CustomMetadata.FSC_AAF_Table__mdt.Class_6.Maximum_Turnover__c,&apos;Class 6&apos;,
 IF(FPT_Calculated__c  &gt; $CustomMetadata.FSC_AAF_Table__mdt.Class_7.Minimum_Turnover__c,&apos;Class 7&apos;,&apos;&apos;))))))),&apos;&apos;)))</formula>
    <label>Trader AAF Class</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FSC_AAFCalculation.cls
public with sharing class FSC_AAFCalculation {
    
    //Calculate AAF on OC creation...
    public static void culationAAFOnCreation(List<Opportunity_Certificate__c> newList) {
        Map <String,FSC_AAF_Table__mdt> cmdMap = getCMDRecord();
        for(Opportunity_Certificate__c record : newList ){
            Decimal  revenue;
            if(record.FSC_Certificate_Type__c == 'Project Certificate') {
                record.FPT_Processor__c = null;
                record.FPT_Trader__c = null;
                record.Revenue_Processor__c = null;
                record.Revenue_Trader__c = null;
                record.FPT__c = null;
                record.Total_Revenue__c = null;
                revenue = record.Project_Cost__c;
            } else if(record.FSC_Certificate_Type__c == 'Group Certificate') {
                record.FPT__c = null;
                record.Total_Revenue__c = null;
                record.Project_Cost__c = null;
                revenue = record.Company_Type__c.contains('Manufacturer') ? record.FPT_Processor_Calculated__c : record.FPT_Trader_Calculated__c;
            } else {
                record.FPT_Processor__c = null;
                record.FPT_Trader__c = null;
                record.Revenue_Processor__c = null;
                record.Revenue_Trader__c = null;
                record.Project_Cost__c = null;
                revenue = record.FPT_Calculated__c;
            }
            //String aafClass = record.Company_Type__c.contains('Manufacturer') ? record.Processor_AAF_Class__c : record.Trader_AAF_Class__c;
            String aafClass = String.isBlank(record.Processor_AAF_Class__c) ? record.Trader_AAF_Class__c: record.Processor_AAF_Class__c;
            Decimal aaf;
            if(cmdMap.containsKey(aafClass) ) {
                FSC_AAF_Table__mdt cmdRecord = cmdMap.get(aafClass);
                Decimal excessTurnover  =  revenue - cmdRecord.Minimum_Turnover__c;
                Decimal baseFee = record.Company_Type__c.contains('Manufacturer') ? cmdRecord.Processor_Base_USD__c : cmdRecord.Trader_Base_USD__c;
                Decimal variableFee = record.Company_Type__c.contains('Manufacturer') ? cmdRecord.Processor_Variable_USD__c : cmdRecord.Trader_Variable_USD__c;
                aaf = baseFee +((excessTurnover/cmdRecord.Fixed_Number__c) *variableFee);   
            } 
            record.Annual_Administration_Fee_AAF__c = revenue == null ? null:aaf;
        }
    }
    
    //Calculate AAF on OC updation...
    public static void culationAAFOnUpdate(List<Opportunity_Certificate__c> newList,Map<Id,Opportunity_Certificate__c> oldMap) {
        List<Opportunity_Certificate__c> modifiedList = new List<Opportunity_Certificate__c> ();
        for(Opportunity_Certificate__c record : newList ) {
            Opportunity_Certificate__c oldRecord = oldMap.get(record.Id); 
            if(record.Project_Cost__c != oldRecord.Project_Cost__c || record.FPT_Calculated__c != oldRecord.FPT_Calculated__c ||
               record.FPT_Processor_Calculated__c != oldRecord.FPT_Processor_Calculated__c || record.FPT_Trader_Calculated__c != oldRecord.FPT_Trader_Calculated__c ||
               record.FSC_Certificate_Type__c != oldRecord.FSC_Certificate_Type__c) {
                   modifiedList.add(record); 
               }
        }
        if(! modifiedList.isEmpty()) {
            culationAAFOnCreation(modifiedList); 
        }
    }
    
    //Get Fields record from custom meta data...
    public static Map <String,FSC_AAF_Table__mdt> getCMDRecord() {
        Map <String,FSC_AAF_Table__mdt> cmdMap = new Map <String,FSC_AAF_Table__mdt>();
        for (FSC_AAF_Table__mdt record : [SELECT MasterLabel,Minimum_Turnover__c,Maximum_Turnover__c,Processor_Base_USD__c,Processor_Variable_USD__c,Trader_Base_USD__c,Trader_Variable_USD__c,Fixed_Number__c FROM FSC_AAF_Table__mdt]) {
            cmdMap.put(record.MasterLabel,record); 
        }
        return cmdMap;
    }
    
}