force-app/main/default/objects/FSC_Field_Mapping__mdt/FSC_Field_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>USE IN FSC</description>
    <label>FSC Field Mapping</label>
    <pluralLabel>FSC Field Mapping</pluralLabel>
</CustomObject>

force-app/main/default/objects/FSC_Field_Mapping__mdt/fields/Field_Type__c.field-meta.xml
<CustomField>
    <fullName>Field_Type__c</fullName>
    <label>Field Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FSC_Field_Mapping__mdt/fields/FSC_Field_API__c.field-meta.xml
<CustomField>
    <fullName>FSC_Field_API__c</fullName>
    <description>FSC</description>
    <label>FSC Field API</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FSC_Field_Mapping__mdt/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>FSC</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FSC_Field_Mapping__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>FSC</description>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FSC_Field_Mapping__mdt/fields/SF_Field_API__c.field-meta.xml
<CustomField>
    <fullName>SF_Field_API__c</fullName>
    <description>FSC</description>
    <label>SF Field API</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FSC_Field_Mapping__mdt/fields/SF_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>SF_Object_Name__c</fullName>
    <description>FSC</description>
    <label>SF Object Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SCS_FSCIntegrationHelper.cls
public with sharing class SCS_FSCIntegrationHelper {
    
    //Get Fields record from custom meta data...
    public static Map<String, List <FSC_Field_Mapping__mdt>> getCMDRecord() {
        Map <String, List <FSC_Field_Mapping__mdt>> cmdMap = new Map <String, List <FSC_Field_Mapping__mdt>>();
        for (FSC_Field_Mapping__mdt record : [SELECT FSC_Field_API__c,SF_Field_API__c,Field_Type__c,SF_Object_Name__c FROM FSC_Field_Mapping__mdt WHERE Is_Active__c = true ORDER BY Order__c ASC]) {
            if (!cmdMap.containsKey(record.SF_Object_Name__c)) {
                cmdMap.put(record.SF_Object_Name__c, new List <FSC_Field_Mapping__mdt>());
            }
            cmdMap.get(record.SF_Object_Name__c).add(record); 
        }
        return cmdMap;
    }
    
    //get field value from specific object
    public static String getQuery (String objectName,Map<String, List <FSC_Field_Mapping__mdt>> cmdMap) {
        Set<String> fieldSet = new Set<String> ();
        Set<String> childFieldSet = new Set<String> ();
        if(cmdMap.containsKey(objectName)){
            for(FSC_Field_Mapping__mdt  record : cmdMap.get(objectName)) {
                fieldSet.add(record.SF_Field_API__c);
            }
        }
        String qry = 'SELECT ' + String.join(new List <String> (fieldSet), ', ');
        return qry;
    }
    
    //get field value from specific object
    public static String getConvertedValue (String value,String dataType) {
        value = dataType == 'Date' ? value.removeEnd(' 00:00:00') : value;
        return value;
    }
    
    
    //get field value from specific object
    public static String getFieldValue (SObject record, String fieldName) {
        String valueToReturn = '';
        List<String> objRelList = fieldName.replace('.', '@@').split('@@');
        SObject tempObj = record;
        for (Integer k = 0; k < objRelList.size() - 1; k++){
            tempObj = tempObj.getSObject(objRelList[k]);
        }
        if(tempObj != null && objRelList != null && objRelList.size() > 0){
            if (tempObj.get(objRelList[objRelList.size()-1]) != null) {
                valueToReturn = String.valueOf(tempObj.get (objRelList[objRelList.size()-1]));
            }
        }
        return valueToReturn;
    }
    
}