force-app/main/default/objects/Activity/fields/Client_Activity__c.field-meta.xml
<CustomField>
    <fullName>Client_Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Activity</label>
    <referenceTo>Client_Activity__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_Activity__c/Client_Activity__c.object-meta.xml
<CustomObject>
    <label>Client Activity</label>
    <nameField>
        <label>Client Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/External_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Record_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Record Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Scope__c/Scope__c.object-meta.xml
<CustomObject>
    <description>Program / Project Scope</description>
    <label>Scope</label>
    <nameField>
        <displayFormat>SC-{0000000}</displayFormat>
        <label>Scope #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scope</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scope__c/fields/Sub_Scope__c.field-meta.xml
<CustomField>
    <fullName>Sub_Scope__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Scope</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>$Source.Program__c</field>
            <operation>equals</operation>
            <valueField>Scope__c.Program__c</valueField>
        </filterItems>
        <filterItems>
            <field>Scope__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sub Scope</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Scope__c</referenceTo>
    <relationshipLabel>Scope</relationshipLabel>
    <relationshipName>SubScope</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scope__c/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/User/fields/External_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Record_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Record Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/FnA_ScopeTriggerHandler.cls
/**************************************************** NEW ORG CODE ***************************************************************** 
* Trigger Name      : FnA_ScopeTriggerHandler
* Related Class Name: SCS_SFToSFConnector
* Division          : Food and agriculture
* Version           : 1.0
* Code reviewed By  : Amitava Dutta
* JIRA Ticket       : SF20FA-136
* JIRA Link         : https://scsglobalservices.atlassian.net/jira/software/projects/SF20FA/boards/56?assignee=61b19c2cb43d5b006ad59a59&selectedIssue=SF20FA-136
* Functionality     : This trigger use to sync scope into client activity and opportunity client activity from new org to old org on after insert or after update.

* Modification Log  :
-------------------------------------------------------------------------------------------------------------------------------------------------
* Developer Name                     Date                                Description
* -----------------------------------------------------------------------------------------------------------------------------------------------
* Umesh Kumar                        15-12-2022                          Initial version 
************************************************************************************************************************************/



public with sharing class FnA_ScopeTriggerHandler implements ITriggerHandler {
    //Call before insert...
    public void beforeInsert(List<Sobject> newList) {
        //Convert List<Sobject> into List<Scope__c>...
        List<Scope__c> recordList = (List<Scope__c>) newList;
        for(Scope__c record : recordList){
            //If record is clone then blank out the external record id...
            if(record.isClone()){
                record.External_Record_Id__c = null;
            }
        }
    }
    //Call after insert...
    public void afterInsert(List<Sobject> newList , Map<Id, Sobject> newMap) {
        //Convert List<Sobject> into List<Scope__c>...
        List<Scope__c> recordList = (List<Scope__c>) newList;
        //Filter record list...
        List<Scope__c> filterList = new List<Scope__c>();
        String objectName = '';
        //Loop each record...
        for(Scope__c record : recordList){
            //Check last modified user is not equal to web integrator user...
            if(record.LastModifiedById != System.Label.Web_Integrator){
                //Add filter record into list..
                filterList.add(record); 
                //Check current record type is equal to Sub Scope...
                if(record.RecordTypeId == SCS_ConstantRTypeReference.scope_SubScopeRTId) {
                    objectName = 'Client_Activity__c';
                    //Check current record type is equal to opportunity...
                } else if(record.RecordTypeId == SCS_ConstantRTypeReference.scope_opportunityRTId && String.isNotBlank(record.Sub_Scope__c)){
                    objectName = 'OpportunityClientActivity__c';
                }
            }
        }
        //Call SF connector to sync data from old org to new org...
        if(!System.isFuture() && !filterList.isEmpty() && objectName != ''){
            SCS_SFToSFConnector.sFToSFConnector(JSON.serialize(filterList),objectName,'PATCH','');
        }
    }
    //Call before update...
    public void beforeUpdate(List<Sobject> newList, Map<Id, Sobject> newMap, List<Sobject> oldList, Map<Id, Sobject> oldMap) {}
    //Call after update...
    public void afterUpdate(List<Sobject> newList,Map<Id,Sobject> newMap,List<Sobject> oldList, Map<Id,Sobject> oldMap) {
        //Convert List<Sobject> into List<Scope__c>...
        List<Scope__c> recordList = (List<Scope__c>) newList;
        //Filter record list...
        List<Scope__c> filterList = new List<Scope__c>();
        String objectName = '';
        //Loop each record...
        for(Scope__c record : recordList){
            //Check last modified user is not equal to web integrator user...
            if(record.LastModifiedById != System.Label.Web_Integrator){
                //Add filter record into list..
                filterList.add(record); 
                //Check current record type is equal to Sub Scope...
                if(record.RecordTypeId == SCS_ConstantRTypeReference.scope_SubScopeRTId) {
                    objectName = 'Client_Activity__c';
                    //Check current record type is equal to opportunity...
                } else if(record.RecordTypeId == SCS_ConstantRTypeReference.scope_opportunityRTId && String.isNotBlank(record.Sub_Scope__c)){
                    objectName = 'OpportunityClientActivity__c';
                }
            }
        }
        //Call SF connector to sync data from old org to new org...
        if(!System.isFuture() && !filterList.isEmpty() && objectName != ''){
            SCS_SFToSFConnector.sFToSFConnector(JSON.serialize(filterList),objectName,'PATCH','');
        }
    }
    //Call before Delete...
    public void beforeDelete(List<Sobject> oldList , Map<Id, Sobject> oldMap) {
        
    }
    //Call after Delete...
    public void afterDelete(List<Sobject> oldList , Map<Id, Sobject> oldMap) {
        
    }
    //Call after UnDelete...
    public void afterUnDelete(List<Sobject> newList, Map<Id, Sobject> newMap) {
        
    }
    
    
}